### ISSUE TITLE
modified eventsmetadata.json files are no longer loaded by the game

### ISSUE THREAD

**Issue by DeathWrench** [WolvenKit/WolvenKit#1015]
I read somewhere that this mod (https://www.nexusmods.com/cyberpunk2077/mods/4563) stopped working along with another mod (https://www.nexusmods.com/cyberpunk2077/mods/1272) that edits the same file. At the time I didn't think much of it but made RedMod versions as a substitute. Still, I was curious as to why they weren't working since all they seemed to do is replace words like combat with kombat. I figured, they should still work. It wasn't until I tried making my own mod that edits this file did I realize that the game does not load the modified file. Doesn't matter if you install it as a redmod archive or put it in the archive/pc/mod folder. I'm trying to replace some songs on the radio and the length of the songs I'm trying to replace is tied to this file. Currently the songs will always cut out _unless_ they are shorter than the songs length specified within that file. 

I'm requesting a temporary solution to fix this problem. Perhaps by replacing the file within the audio_1_general.archive itself.

I tried to make a project out of the audio_1_general.archive, replace the eventsmetadata.json file then build it. But the file size is different to the original. Loading the game with this replaced file makes all the radios mute. 
![image](https://user-images.githubusercontent.com/45341450/203291649-2d8b725c-35b3-408f-a766-19ca8286b8bd.png)

**Comment by dragonzkiller** [comment]
Closing as this is not a WolvenKit issue. Please discuss this on the various discords if you have any questions regarding this topic.

**Comment by DeathWrench** [comment]
Please re-open this, it's not an issue, correct; but a feature request.
![image](https://user-images.githubusercontent.com/45341450/203804935-71ee63ed-8ab5-42e1-aa10-5d1e96c82c70.png)

**Comment by Traderain** [comment]
Hey
This can be done much cleaner with proper redmod audio mod. Check for reference here: https://wiki.redmodding.org/cyberpunk-2077-modding/modding-know-how/frameworks/redmod/quick-guide#audio-modding

**Comment by dragonzkiller** [comment]
Not only is trade, correct, it's not a feature that is meant for wolvenkit anyway. If it indeed did change with one of the latest updates, then it's an engine-level change which we do not "fix" or add features to with wkit. Those are for red4ext-based mods like psiberx's ARCHIVE XL. Feel free to ask more in our discord

**Comment by DeathWrench** [comment]
> Hey This can be done much cleaner with proper redmod audio mod. Check for reference here: https://wiki.redmodding.org/cyberpunk-2077-modding/modding-know-how/frameworks/redmod/quick-guide#audio-modding

There's currently a bug with this method when replacing radio songs this way. I posted in the CDPR forums hoping someone might notice. https://forums.cdprojektred.com/index.php?threads/redmod-audio-bug-when-replacing-radio-songs.11110040/
If you switch stations back and forth while a modded song is playing, it starts over from the beginning. This is why I'm trying the .wem method and trying to edit this eventsmetadata.json file.
