### ISSUE TITLE
Mesh import nukes materials

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1034]
**Describe the bug**
There is some fuckery going on with import/export and the mesh materials. 
[head.zip](https://github.com/WolvenKit/WolvenKit/files/10241165/head.zip)

**To Reproduce**
1. Rename "h0_001_ma_a__takemura.mesh" (default mesh from the game) to "takemura_neck_no_chrome.mesh"
2. Import "takemura_neck_no_chrome.glb"
3. Open the mesh: materialEntries and localMaterialBuffer/Materials will be down to two entries.
4. Take takemura_neck.mesh
5. Import that glb: material properties will be retained.

**Expected behavior**
Since I exported everything from the same blend file with the same settings, materials should not be overwritten.

**Desktop (please complete the following information):**
 - OS: Windows 10x64
 - Version WKit Nightly 11-11 to 12-15

**Comment by seberoth** [comment]
Imported "takemura_neck_no_chrome.glb" both with and without materials. Both resulted in the "same" file where there were 13 entries (like the original) materialEntries and localMaterialBuffer/Materials:
![grafik](https://user-images.githubusercontent.com/456881/211245955-98ad1c84-4ca5-43f7-8a2a-0cf6d3445204.png)

**Comment by seberoth** [comment]
@manavortex Is this still a issue?

**Comment by manavortex** [comment]
No! I think it happened because it always auto-imported the exported json :))
