### ISSUE TITLE
WolvenKit does not start

### ISSUE THREAD

**Issue by 38-35-44-44-0d-0a** [WolvenKit/WolvenKit#1052]
Everytime i try to start WolvenKit nothing happens after the Splash Screen. I can find the Process in the Task Manager but no Window opens.

 - OS: Win 10 Pro 21H2
[applog20230106.txt](https://github.com/WolvenKit/WolvenKit/files/10362384/applog20230106.txt)

**Comment by rfuzzo** [comment]
So you have net7 installed?

**Comment by 38-35-44-44-0d-0a** [comment]
Yes i have 7.0.1 x64 installed

**Comment by rfuzzo** [comment]
can you check your log file? You can access it under `%appdata%/redmodding/wolvenkit`.

**Comment by 38-35-44-44-0d-0a** [comment]
I already attached it to the original post

**Comment by rfuzzo** [comment]
stale
