### ISSUE TITLE
[BOT] CyberpunkSaveReader Fails to Parse Equipment-EX `OutfitSlot`

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#1064]
[Issue create with https://github.com/rfuzzo/LizzyFuzzy] 
 Author: Lizzy Fuzzy 
 Equipment-EX adds a new `OutfitSlot` field, this breaks save file parsing.

**Comment by seberoth** [comment]
Please provide the save which is causing the error

**Comment by effs** [comment]
<img width="362" alt="Screenshot 2023-01-10 at 8 31 06" src="https://user-images.githubusercontent.com/13802421/211478148-71e7d98c-6a8f-4a6d-bb24-90bcb56a8ed2.png">

**Comment by effs** [comment]
And this is a CyberCAT issue! Closing here..
