### ISSUE TITLE
remove winforms dependency

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#1065]
[Issue create with https://github.com/rfuzzo/LizzyFuzzy] 
 Author: rfuzzo 
 this. Find an alternative for the folder picker

**Comment by dragonzkiller** [comment]
From our discussions on discord, this isn't possible anymore as long as we're using naudio and the newest syncfusion. I removed the winforms requirement for the dialogs with #1217 which would have closed this if not for the aforementioned packages 

We can keep it open if it's really an issue and maybe someday we'll get to it, but I feel like it'll just sit here unclosed for eternity

**Comment by rfuzzo** [comment]
Yeah let’s close it, I *guess* this will be obsolete when we move to WINUI (but who knows)
