### ISSUE TITLE
Installer problems

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#1073]
[Issue create with https://github.com/rfuzzo/LizzyFuzzy] 
 Author: rfuzzo 
 - [x] fix the installer update check
 - [ ]  fix the installer not installing

**Comment by rfuzzo** [comment]
If anyone wants to help me with the remaining issue here:

- [ ] Find a way to run the powershell appx-install command and catch the output. 
- [ ] another way could be to make the installer framework-independent (WINUI self-contained) and use winget

**Comment by Syrrr** [comment]
I pushed the commit that runs the Windows-native App Installer to install the msixbundle file.

**Comment by rfuzzo** [comment]
I believe this is fixed with Syrr's commit
