### ISSUE TITLE
Import/Export: auto-trigger refresh on open

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1089]
Since the auto-refresh fell victim to its poor performance, the import and export tab require constant manual refreshing. 

## Please auto-trigger the refresh button (or the equivalent function call) on panel open.

No idea if it's the same function in C#, but here's where I'd put it?

Case 1: User has the panels open, but not pinned
User clicks on the panel button and previously minimized panel opens => refresh upon open/render

Case 2: User has panel(s) open/pinned, but they share the same place in the view
User clicks on panel button to switch between import/export => refresh upon switch

**Comment by rfuzzo** [comment]
this is fixed on main
