### ISSUE TITLE
Support AMM custom files via RESOURCES

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1098]
AppearanceMenuMod's files are stored deep within the bowels of CET: 
```
Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods\AppearanceMenuMod\Collabs
  - Custom Entities
  - Custom Appearances
  - Custom Props
```
I frequently find myself copying the files I'm working on to WKit's packed folder (that isn't even visible from the GUI anymore) and keeping them open in a text editor forever.  

It would be great if the RESOURCES part of Wkit supported those files!

**Comment by ArasakaApart** [comment]
I think this works fine?
![image](https://user-images.githubusercontent.com/17293117/213303120-59faf488-bd5b-4aeb-a287-6c3d8c34dbae.png)
![image](https://user-images.githubusercontent.com/17293117/213303147-7b0432ed-1cbc-4ffc-bf22-d3f39fefbc5b.png)

**Comment by manavortex** [comment]
Oh, I had no idea :D 

in that case: Could they be added to the "New File" menu?

**Comment by rfuzzo** [comment]
Not in scope
