### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by philippTheCat** [WolvenKit/WolvenKit#111]
^title

**Comment by Traderain** [comment]
I agree but we should supress CS1591

**Comment by saurabhs** [comment]
I may take this, but how you guys are planning to suppress CS0649, <variable> is never assigned to, and will always have its default value 0? Remove/comment out it from class/struct for now?

**Comment by NamStalker** [comment]
Can I pick this up? It looks like the broken build for their PR request is stale.

**Comment by rfuzzo** [comment]
outdated with Wkit 8
