### ISSUE TITLE
Project Explorer: Tabs don't remember tree folding state between switches

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1111]
When I switch from e.g. the "archive" tab to the "raw" tab in the project explorer, the root folder will always be shown as collapsed. It would be great if the tabs could remember their tree state even after changes.

![image](https://user-images.githubusercontent.com/965785/214641855-9c0ee04c-babc-4bbd-ad50-bee084c9a45e.png)

**Comment by seberoth** [comment]
Is fixed
