### ISSUE TITLE
breaking meshes after 8.8.1

### ISSUE THREAD

**Issue by jamiecross1477** [WolvenKit/WolvenKit#1126]
**Describe the bug**

Certain meshes become unusable after changing the material path (path to custom .mi)

**To Reproduce**

*no judgement as this mod contains nudity please.

open "smallben.mesh" 
go to preloadLocalMaterialInstances
open the material and change the path to  "base\jamie\bradley_melnick\mesh\erect.mi" (or anything else)
save mesh
close mesh

mesh is now unusable

you can also export and reimport the mesh and it will also break.

**Expected behavior**

prior to 8.8.1, the meshes would save correctly and load in game

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

Download:
https://we.tl/t-eHvO4umvy4

Sorry, it was a large file

**Comment by rfuzzo** [comment]
the file is not available anymore, and I don't have the old download either :/

**Comment by seberoth** [comment]
Should be fixed.
