### ISSUE TITLE
unknown file paths

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#1130]
[Issue create with https://github.com/rfuzzo/LizzyFuzzy] 
 Author: rfuzzo 
 sometimes unhashed files are not displayed in the cr2w editor. Link: https://discord.com/channels/717692382849663036/786891742829215745/1070095793236742245

**Comment by dragonzkiller** [comment]
Related to #1062

**Comment by seberoth** [comment]
@dragonzkiller Are you sure? Just looks like any other unresolvable path to me.
The text field is emtpy, the hash is filled.

Could argue to show the hash in the treeview if its not resolveable
