### ISSUE TITLE
Error Importing Files

### ISSUE THREAD

**Issue by XilaMonstrr** [WolvenKit/WolvenKit#1135]
Cannot import a wide variety of texture files. I get the following errors.
They are particularly prolific in: environment/decorations/containers

[error (1).txt](https://github.com/WolvenKit/WolvenKit/files/10571901/error.1.txt)
[error.txt](https://github.com/WolvenKit/WolvenKit/files/10571902/error.txt)

**Comment by rfuzzo** [comment]
thanks, I made a fix so that it imports, but both your images are TexGroup Data... So, I'm not sure what to expect
