### ISSUE TITLE
Mesh Preview only considers PreloadLocalMaterials

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1142]
**Describe the bug**
When rendering materials for the mesh preview, RDTMeshViewModel only considers those under `PreloadLocalMaterialInstances`. Many meshes have them under `LocalMaterialBuffer.Materials`. 

I tried fixing that by implementing a simple getter function and caching the list outside of the loop(s), but the second case cast would fail with lots of exceptions:

```
   
private CArray<CMaterialInstance> getMaterialsFromList(CMesh data)
{
    var ret = new CArray<CMaterialInstance>() ;

    if (data.PreloadLocalMaterialInstances != null && data.PreloadLocalMaterialInstances.Count > 0)
    {
        for (var i = 0; i < data.PreloadLocalMaterialInstances.Count; i++)
        {
            ret[i] = data.PreloadLocalMaterialInstances[i]?.GetValue() as CMaterialInstance;
        }
    } 
    else if (data.LocalMaterialBuffer != null && data.LocalMaterialBuffer.Materials.Count > 0)
    {

        for (var i = 0; i < data.LocalMaterialBuffer.Materials.Count; i++) {
             ret[i] =  data.LocalMaterialBuffer.Materials[i] as CMaterialInstance;             
        }
    }

    
    return ret;
}
```

If static access to `PreloadLocalMaterialInstances` is replaced with the (cached) function above, it should work…?

**Comment by seberoth** [comment]
It looks like it already uses both sources.
First it will check `LocalMaterialBuffer` and if it isn't there, it will use `PreloadLocalMaterialInstances`

If it doesn't work, pls reopen this with a sample file path / a sample file attached
