### ISSUE TITLE
Import from JSON not working for multiple selected files

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1143]
**To Reproduce**
1. Export multiple files to JSON
2. Delete the originals
3. Select multiple files as JSON
4. Right-click and select "Import from JSON"

**Expected behavior**
All files should be processed

**Actual behavior**
Only the first file gets processed

Win x64, Nightly 2023-01-23

**Comment by seberoth** [comment]
Isn't it more like a feature request then a bug report?
As far as I can see it always worked like that

**Comment by rfuzzo** [comment]
Hmm I'd consider it a bug. The viewmodel actually has all the stuff to let it work correctly

**Comment by manavortex** [comment]
It fails silently, so I thought it was a bug. Might disable the option for multiselect if it's working as intended?
