### ISSUE TITLE
QoL feature: Default directory for mod project creation

### ISSUE THREAD

**Issue by DoctorPresto** [WolvenKit/WolvenKit#1154]
Currently on every new project, Wolvenkit has you specify a creation location for the project files. It would be nice if you could set a default location in settings which would auto populate this field. By just auto populating the field but leaving it accessible during mod creation, it remains convenient to switch locations for the times when you do not want the project to be in the same spot.

![image](https://user-images.githubusercontent.com/111536029/218236625-e6eeae5b-acfd-439b-9847-be7738bdf913.png)

**_very_** low priority considering the scope of current overhauls, but would be nice eventually

**Comment by Simarilius-uk** [comment]
might be minor but its bloody annoying.

**Comment by rfuzzo** [comment]
hmm I think I would prefer if it just defaults to the last used folder here. lemme do that actually.

**Comment by Simarilius-uk** [comment]
yeah, the open dialog starts at that folder and thats 99% of the time what I want. the fact I have to click browse then ok every time is just a pita.

**Comment by rfuzzo** [comment]
yeah same actually :D I was annoyed about that too

**Comment by Simarilius-uk** [comment]
Thanks fuzzo
