### ISSUE TITLE
Mesh: Changing appearance cnames has no effect

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1163]
**Describe the bug**
When changing appearance cnames in a mesh, the fields will get updated, but the changes will revert upon closing and re-opening the file.

Good news: Changing stuff in the materials works!

![image](https://user-images.githubusercontent.com/965785/219498840-5f9383d8-62ad-4e86-92b0-82b06e7cf993.png)

[notepad.zip](https://github.com/WolvenKit/WolvenKit/files/10761342/notepad.zip)

**To Reproduce**
1. Open notepad.mesh
2. Change the name of the second appearance to something else
3. Change the chunkMaterial names to something else
4. save and close the file
5. re-open: the changes have reverted

Nightly 2023-02-16

**Comment by seberoth** [comment]
Should be fixed
