### ISSUE TITLE
Vector changes (e.g. BaseColorScale) reset on loss of focus

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1166]
When changing a vector value, it resets upon loss of focus. Only saving the file right away makes the value persist:

https://user-images.githubusercontent.com/965785/219954517-fc19f052-d273-4320-a525-c0397218e85b.mp4

Reproduced it in 8.8.2-nightly.2023-02-16 before filing the bug :)

**Comment by seberoth** [comment]
Probably will do that while/after the CVM rewrite...
