### ISSUE TITLE
"Lock GUI" button

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1171]
This is another [mana problem](https://github.com/WolvenKit/WolvenKit/issues/1146), so prioritize accordingly.

I find myself drag-and-dropping panels around by accident. This happens so often that I'm annoyed enough to write a ticket! 

Please add an option to lock down GUI panels, either disabling drag&drop completely, or discarding the changes instead of applying them.

![image](https://user-images.githubusercontent.com/965785/221363956-cd928f57-9863-45e3-800c-04c94d9e4587.png)

**Comment by rfuzzo** [comment]
not in scope
