### ISSUE TITLE
Filter row search behaviour

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1172]
Both the the filter row in "Export Tool" and the filter in "Select rigs" only select from the start of the string:

![image](https://user-images.githubusercontent.com/965785/221365675-38d8d302-943c-47e8-8353-261a604a95c1.png)
![image](https://user-images.githubusercontent.com/965785/221365680-d90058c6-e5f5-42e5-b38d-7ed690460325.png)

Please either default to fuzzy matching or add wildcard and/or regex support (or both?) :)

**Comment by seberoth** [comment]
Switch to `Contains` instead of `Begins with`
![grafik](https://user-images.githubusercontent.com/456881/221399895-5e4fad07-f509-44ab-97cd-31e4ab32ba6f.png)

**Comment by rfuzzo** [comment]
yep, but I will change default to "contains". thanks

**Comment by manavortex** [comment]
Didn't even see that, tysm <3
