### ISSUE TITLE
Error message toast: Close with right-click or shift-click

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1173]
![image](https://user-images.githubusercontent.com/965785/221366717-f93291d7-aa2c-4a10-be84-6e3373ee3dd1.png)

You have to exactly hit the close button for the toast to disappear. For impaired clickers ~~like me~~, that is somewhat annoying.

Please allow shift-click or right-button click on an error toast to close it :)

**Comment by seberoth** [comment]
Right-clicking is already a thing
![grafik](https://user-images.githubusercontent.com/456881/221399789-c0df68a7-340f-494b-b5cc-d243e48568cc.png)
