### ISSUE TITLE
Regression: can't import .re animation files with WKit 8.8

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1174]
With Wolvenkit 8.7, I can import .re files, following [this tutorial](https://www.youtube.com/watch?v=m5IL_TRwTew). With Wkit > 8.7, I can't do that anymore (latest stable and Nightly both won't allow it). 

[raw.zip](https://github.com/WolvenKit/WolvenKit/files/10832312/raw.zip)

**To Reproduce**
1. Add `base\animations\npc\generic_characters\male_average\locomotion\man_average_civilian_locomotion.anims` to project
2. Import the file `idle_turn_to_sprint_090.re` with the following anim settings:
  - animset: `base\animations\npc\generic_characters\male_average\locomotion\man_average_civilian_locomotion.anims`
  - animation to replace: the file name (`idle_turn_to_sprint_090`)

WKit 8.7 stable will succeed

Wkit 8.8 (Nightly 2023-02-25) will fail with the following error: 
```
[25/02/2023 22:19:08] WorkDir: C:\GOG Games\Cyberpunk 2077\tools\redmod\bin
[25/02/2023 22:19:08] Running commandlet: animation-import -depot="E:\CyberpunkFiles\anims\animation_1\source\archive" -input="E:\CyberpunkFiles\anims\animation_1\source\raw\base\animations\npc\generic_characters\male_average\locomotion\idle_turn_to_sprint_090.re" -animset=base\animations\npc\generic_characters\male_average\locomotion\man_average_civilian_locomotion.anims -animationRename=idle_turn_to_sprint_090
[25/02/2023 22:19:09] No root specified, using default root path.
[25/02/2023 22:19:09] Import error: The rig assigned to animation set is invalid. Maybe the path is wrong?
[25/02/2023 22:19:09] Failed to import animation!
[25/02/2023 22:19:09] Copyright (c) 2022 CD Projekt Red. All Rights Reserved.
[25/02/2023 22:19:09] Created in collaboration with CD Projekt Vancouver and Yigsoft LLC
[25/02/2023 22:19:09] 
[25/02/2023 22:19:09] App: Using custom game root path: 'E:\CyberpunkFiles\anims\animation_1\source\archive\'
[25/02/2023 22:19:09] Core: App instance initialized in 0.00 ms
[25/02/2023 22:19:09] 
[25/02/2023 22:19:09] 
[25/02/2023 22:19:09] 
[25/02/2023 22:19:09] Commandlet animation-import has failed.
[25/02/2023 22:19:09] Exit time    : 25/02/2023 22:19:09
Exit code    : 255
Elapsed time : 448
[25/02/2023 22:19:09] The following items failed:
E:\CyberpunkFiles\anims\animation_1\source\raw\base\animations\npc\generic_characters\male_average\locomotion\idle_turn_to_sprint_090.re
```

**Comment by seberoth** [comment]
`The rig assigned to animation set is invalid. Maybe the path is wrong?`
Seems mor like an file/redmod error then a WKit error

**Comment by manavortex** [comment]
I'd agree with you, if not for the fact that the same thing works in 8.7

**Comment by rfuzzo** [comment]
I'll assign this to me. maybe I missed some arg changes in redmod?

**Comment by seberoth** [comment]
> I'd agree with you, if not for the fact that the same thing works in 8.7

I'm not even sure how you made it to work with 8.7, since 8.7 is programmed for the previous redmod version

**Comment by manavortex** [comment]
> I'm not even sure how you made it to work with 8.7, since 8.7 is programmed for the previous redmod version

I'm not sure either, but Vesna confirmed it working, the anims _definitely_ get imported :D

**Comment by seberoth** [comment]
Probably using a backup of the previous redmod.exe then

**Comment by manavortex** [comment]
Nope - definitely not. And I've reproduced the successful import by simply running it with 8.7, I simply haven't confirmed whether or not the animation was working (yet)

**Comment by seberoth** [comment]
But the current redmod.exe hasn't import anymore and thats what 8.7 is calling
![grafik](https://user-images.githubusercontent.com/456881/221417437-269c3ffd-55ae-4971-87eb-5d316c2d1880.png)

**Comment by V3sn4** [comment]
This is what i was getting on my **8.8.1-nightly.2022-12-09** 
It says it succeed, however when tested in game the animation/pose turns into generic standing animation instead of the static one provided in redmod animation kit. While trying to get it to work long time ago by importing Fortnite dance animations according to Akos' tutorial I went as far as making the anim actually "explode" the character.

![image](https://user-images.githubusercontent.com/106106130/221421223-239d4a60-2dca-436e-954c-3302803d3c2d.png)

**Comment by seberoth** [comment]
No doubt that ther might be an issue with the latest redmod version.
Thought I'm still wondering how you managed to use the old syntax (8.7) with the new redmod (8.8+) version^^

**Comment by V3sn4** [comment]
Found results from my first try, it was on 27th December so I already had **8.8.1-nightly.2022-12-09** 
MY second try was recent, the same nightly but in the meantime I had PC upgrade and I had to reinstall all plugins if in the meantime was plugin update.
https://user-images.githubusercontent.com/106106130/221421803-7d45d062-a25d-4288-8f85-d937df8d8c23.mp4

**Comment by V3sn4** [comment]
This is the exact plugin I used for the outcome I had on **8.8.1-nightly.2022-12-09** 

[REDmodPlugin.zip](https://github.com/WolvenKit/WolvenKit/files/10834141/REDmodPlugin.zip)

**Comment by seberoth** [comment]
I was talking about the `redmod.exe` in `Cyberpunk 2077\tools\redmod\bin`, not the blender plugin :)

**Comment by V3sn4** [comment]
![image](https://user-images.githubusercontent.com/106106130/221423373-4f1dce86-8b3d-4049-bcb4-d3888d0d73c5.png)

**Comment by V3sn4** [comment]
It's version **1.0.0.1**
![image](https://user-images.githubusercontent.com/106106130/221423554-a1ed63c5-298b-4527-9e8b-a58aeb23433e.png)

**Comment by seberoth** [comment]
Yeah, all fine. Still don't know how this exe works together with 8.7...
The syntax is different in 1.0.0.0 and thats whats 8.7 was made for

**Comment by rfuzzo** [comment]
Maybe I just added an alias for “import”? 🤔

**Comment by seberoth** [comment]
No, my screenshot above was using 8.7. Then it needed to work for me too

**Comment by rfuzzo** [comment]
okay, I tested it, and the import works (succeeds and writes to the correct file), however it might still be that it writes it _incorrectly_...

**Comment by rfuzzo** [comment]
oh, and Wolvenkit cannot open the new file... That's a problem

**Comment by manavortex** [comment]
Can you check if the game recognizes the imported file and plays the .anim? I haven't been able to get it to work..

**Comment by rfuzzo** [comment]
If wkit can't raed it, chances are, the game cannot either...

**Comment by rfuzzo** [comment]
closing this as duplicated of #1193

**Comment by miron** [comment]
> This is what i was getting on my **8.8.1-nightly.2022-12-09** It says it succeed, however when tested in game the animation/pose turns into generic standing animation instead of the static one provided in redmod animation kit. While trying to get it to work long time ago by importing Fortnite dance animations according to Akos' tutorial I went as far as making the anim actually "explode" the character.
> 
> ![image](https://user-images.githubusercontent.com/106106130/221421223-239d4a60-2dca-436e-954c-3302803d3c2d.png)

Mine "exploded" too, was glad to come that far anyway.
