### ISSUE TITLE
Deleting multiple cnames remixes the rest

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1182]
Another index problem with the cnames (I'm so sorry)

Wkit version 2023-03-01, see attached video

https://user-images.githubusercontent.com/965785/222212529-a2d9eefc-e7d8-4302-a126-a65677a73d4f.mp4

**Comment by seberoth** [comment]
> (I'm so sorry)
I doubt you are :P

But its not a CName problem, it affects all array. Seems like it always deletes the first occurrences of a value
