### ISSUE TITLE
Docking floating import/export tool leads to duplication

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1185]
![image](https://user-images.githubusercontent.com/965785/222770943-70336b0b-6118-4052-b030-1fddf5ebace8.png)

Nightly 03-03

**To Reproduce**
1. Open or create a new project without a saved layout
2. Open the Import or Export Tool
3. Dock the floating window to the side of Wkit
4. Behold: You now have two windows

**Comment by seberoth** [comment]
Rly a bug?

Of all the windows we have, it only happens for import/export. Not even need to dock it first, just clicking the button multiple times opens multiple instances.

Could be used to compare settings and stuff...

**Comment by manavortex** [comment]
I open only one instance, then I pin it, and end up with two instances being pinned and visible. That's not a behaviour I'd expect :D

**Comment by seberoth** [comment]
No matter what I do, if I only create one, only one windows gets attached. So...

**Comment by manavortex** [comment]
Wow, okay - maybe I _did_ have a saved layout in the project, and the previous instance was hidden? Probably because of the bug.

In that case, this one can go!
