### ISSUE TITLE
UI: Remove "Convert To JSON" from json files under "raw"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1188]
![image](https://user-images.githubusercontent.com/965785/222819886-4fb46426-a6c7-4c70-85e9-a9a61d97bdb8.png)

It's not doing anything and I'd much rather not have it :D

**Comment by rfuzzo** [comment]
Ah yes thanks, i forgot about that!

**Comment by manavortex** [comment]
Gotta do something for my bug bounty!! (The bug-free easy-to-use Wolvenkit :D)
