### ISSUE TITLE
Verify mesh material indices of local materialEntries to prevent CTD

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1190]
Loading this mesh caused a CTD:

![image](https://user-images.githubusercontent.com/965785/222913685-f2598391-4cc9-48d3-b25a-5d9817059704.png)

The .ent preview loaded the first two appearances (with other meshes, a and b) and then failed silently, which is good, because at least it didn't explode. 

While this is absolutely an ID-10T kind of bug and I found it pretty quickly, WKit can detect it and should print warnings to the console. 

Version: WKit Nightly 03-03

**Comment by seberoth** [comment]
> and should prevent it

I'm not sure about that. Currently we don't do any file specific logic checks for user changes and I'm unsure if we should do it.

**Comment by manavortex** [comment]
Yeah, I know - but I think this would be an excellent point to start? :)

**Comment by rfuzzo** [comment]
Didn't I create an issue somewhere about verify file checks? We thought about it for a long time but never started...

**Comment by manavortex** [comment]
> Didn't I create an issue somewhere about verify file checks? We thought about it for a long time but never started...

I only know of an issue that's supposed to warn user about non-lowercase file paths when packing...

**Comment by rfuzzo** [comment]
#1092

**Comment by seberoth** [comment]
Should be done
