### ISSUE TITLE
The import tool can not be accessed when DDS files are present in the "Raw-folder"

### ISSUE THREAD

**Issue by Rudolph2109** [WolvenKit/WolvenKit#1194]
**Describe the bug**
Actually the title says it all!
I have added a .zip containing the following:
- The folders including their files (Nothing has been edited, literally just exported these, so all files  are 100% vanilla).
- A screenshot of my opened Wolvenkit (V. 8.8.1)
- A text file that is a complete copy of the log within Wolvenkit.

**To Reproduce**

**Expected behavior**
I expected to be able to import the exported files

**Version (please complete the following information):**
 - Version [e.g. 22] - 8.8.1, Latest Stable

**Screenshots**
Screenshot are in the attached .zip
[Wkit-Error.zip](https://github.com/WolvenKit/WolvenKit/files/10892113/Wkit-Error.zip)

**Comment by seberoth** [comment]
Fixed with #1176
