### ISSUE TITLE
Premature termination of questphase parsing (root.graph missing significant amount of nodes)

### ISSUE THREAD

**Issue by pharingWell** [WolvenKit/WolvenKit#1199]
**Describe the bug**
questQuestPhaseResource failing to read all nodes and all prefabs in questphase file

**To Reproduce**
1. Go to base/open_world/mini_world_stories/badlands/se1/mws_se1_01/mws_se1_01.questphase in 
2. Open the file
3. Note the significant discrepancy in the amount of nodes in the GraphEditor and those listed

**Expected behavior**
The node information of all 106 nodes being accurately collected in the root.graph

**Version (please complete the following information):**
 - Version 8.8.1 and 8.8.2-nightly-2023-03-05

**Screenshots**
![image](https://user-images.githubusercontent.com/30706897/223650527-0a5369d7-9a6a-441f-bb04-91ac9ad0ba26.png)
![image](https://user-images.githubusercontent.com/30706897/223650546-3a78525f-f55b-40df-8339-6f3aec0e9bfc.png)

**Comment by seberoth** [comment]
Nope, its all there ;)
![grafik](https://user-images.githubusercontent.com/456881/223654988-6c6a6a03-ed00-4ca4-8a0b-24fb6f6c58c3.png)
