### ISSUE TITLE
Scene files don't show up in graph editor

### ISSUE THREAD

**Issue by yna2jd** [WolvenKit/WolvenKit#1208]
**Describe the bug**
I don't know anything about the graph editor, but if you click on a scene file and try to look at the graph editor tab it's just totally blank

**To Reproduce**
Open up a scene file
click graph editor

**Expected behavior**
Editing graphs?

**Version (please complete the following information):**
 - Version 8.8.1

**Screenshots**
![Untit12led](https://user-images.githubusercontent.com/123516015/224462784-a33034bc-b349-4ef7-b534-09b5a9e2cced.png)

**Comment by yna2jd** [comment]
oops ignore the white in the screenshot

**Comment by seberoth** [comment]
Yeah, that feature was never finished for scene files and the dev who started working on it doesn't work on wkit anymore.

So we should probably hide this tab in future

**Comment by rfuzzo** [comment]
It's hidden now, but we can keep this open since it would be cool to have a scene graph viewer. related to: #575

**Comment by seberoth** [comment]
Done iwth b850ba2
