### ISSUE TITLE
Show locKey browser without a project

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#1210]
The LocKeys are shown only if a project was opened. If I launch WolvenKit and click on "Continue to editor ->", they aren't.

_Originally posted by @TeraLogin in https://github.com/WolvenKit/WolvenKit/issues/1207#issuecomment-1464882876_

**Comment by rfuzzo** [comment]
the locKeys don’t necessarily need a project right?

**Comment by seberoth** [comment]
No, but loading the archives without project could currently lead to more problems.
(Every PE releatad task needed to be checked?)

**Comment by rfuzzo** [comment]
Hmm 🤔 okay, yeah let’s leave this open and I’ll check the relay command conditions (most of them should be fine tbh)

**Comment by TeraLogin** [comment]
Thanks for your help guys. I'm just using the Tweak DB Browser and without a shown LocKey it's a trouble to identify what is what.

**Comment by seberoth** [comment]
This should work now.
Just need to load the archives via the asset browser before using it.
