### ISSUE TITLE
Wolvenkit version: consistent display position

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1213]
Wkit displays its version information in two different spots, based on whether or not you have a project open:

![image](https://user-images.githubusercontent.com/965785/224489571-f49bb5a7-2bee-4379-82b8-3bb3985e8958.png)

![image](https://user-images.githubusercontent.com/965785/224489616-83804266-05cf-4717-8650-4bd78422f223.png)

### It would be great if the information could be consistently displayed in the same spot. 

![image](https://user-images.githubusercontent.com/965785/224489786-e67090f7-36cc-4343-bccd-54d92900b511.png)

**Comment by rfuzzo** [comment]
To be quite honest, I don't see this as a problem. The Home overlay has a different design from the other app, and does not display the status bar. But we can keep this is in the backlog to think about overall consistency of design
