### ISSUE TITLE
Directory structure on compiled project

### ISSUE THREAD

**Issue by KoalaNalle** [WolvenKit/WolvenKit#122]
Currently the root folder contains all files but licence files. And it's housing some 100+ files.

I would suggest that the structure is updated to atleast /bin - folder and the root should house only standalone-executable-, readme- and config files.

**Comment by Traderain** [comment]
Cleaned it up a bit. Should be better now. Let me know If you have any other ideas how to make it better structured @KoalaNalle

**Comment by rfuzzo** [comment]
we could use this: https://www.nuget.org/packages/PrettyBin
![image](https://user-images.githubusercontent.com/37657287/76293759-ea6d8180-62b1-11ea-89c5-755d3c35e35e.png)

**Comment by Traderain** [comment]
Oh that's cool. I tried Fody but wasn't satisfied. This looks neat.

**Comment by rfuzzo** [comment]
ah I used fody on my wpf aps - for weaving, which worked nice. 
but yeah, PrettyBin seems very simple and does the trick I guess.

**Comment by Traderain** [comment]
What happened with this?

**Comment by rfuzzo** [comment]
maybe we can finnaly get smart about NET5 publish single file?
