### ISSUE TITLE
QOL Import/Export: Have filter do a selection refresh on focus lost

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1222]
![image](https://user-images.githubusercontent.com/965785/225454780-e9d8510a-03d7-4272-9ba3-e2c28c99d002.png)

Would be great if the button could click itself on focus lost - that way I wouldn't have to do it all the time :D

**Comment by seberoth** [comment]
It should already do that. Just press <Tab> or <Enter>

**Comment by manavortex** [comment]
True, it does - could it do onFocusLost as well? Sometimes I do click >.<

**Comment by seberoth** [comment]
Not sure what you do, but whenever it looses focus on my end, it refreshs the view. Even if I click the Refresh button

**Comment by rfuzzo** [comment]
Tbh for this I don’t think it refreshes on focus lost, but I also don’t think this is a good feature (you don’t need to refresh something when you’re going away from it)

**Comment by seberoth** [comment]
Maybe I missunderstood the issue here...

Is it about refreshing the underlaying file list, about refreshing the filter or both?

**Comment by manavortex** [comment]
It's about refreshing the list of displayed files. 

1. Apply a filter
2. Type a different filter term that should show files
3. click into the file list (not on an item, just in the list)
4. no refresh happens

**Comment by seberoth** [comment]
Oh, yeah thanks for that info.
I clicked everywhere and it it worked all the time. Clicking into the list is the only thing I didn't try and as it seems the only thing where it doesn't refresh^^

**Comment by manavortex** [comment]
Oh Jesus, that's about the only thing big enough for me to reliably click 😂 I guess my bug reports aren't as good as I thought they did.
