### ISSUE TITLE
Import/Export not considering filter selection for "Process All"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1226]
1. In the export tool, apply filter in a project with a bunch of files
2. click "Export All"

![image](https://user-images.githubusercontent.com/965785/225989680-a23546cd-82c6-4739-b031-de50e447baaa.png)

Expectation: Only files matching the filter will be exported
Reality: All my files get exported

It's debatable if this is a bug or a feature request ;)

# Edit: My main issue is the UI ambiguity
... where the filtered list is directly below the "import/export all" button, suggesting that there's a correlation. Could be resolved either by adding more buttons or by finding a way to clear the filter quickly (maybe by shift-clicking "Export All" or something) 

# Edit2 "select all" button disappears on sort
![image](https://user-images.githubusercontent.com/965785/226142504-6a6b257d-3df3-4788-9ee2-2892c51344e6.png)

**Comment by seberoth** [comment]
> It's debatable if this is a bug or a feature request ;)

No, its not since it does what it says.
I also would leave it like that. If I press "Export all" I want to export all files, not these which are currently shown because of a view filter.
Select them and use "Export selected" for that

**Comment by manavortex** [comment]
Strongly disagree, maybe we should put it up to a vote :)

**Comment by seberoth** [comment]
What you want is a "Export filtered" button in my opinion

**Comment by rfuzzo** [comment]
Does the checkbox in the header work properly when filtered?

**Comment by manavortex** [comment]
I have dozens of files in my project, and I'm only working on one asset in a time. Why would I even want to export the entire project? I can't evne think of a use case.

Fuzzo: Yeah, the checkbox works, but it's an extra click and half of the time I end up hitting the sort button instead -.-

**Comment by Simarilius-uk** [comment]
> I have dozens of files in my project, and I'm only working on one asset in a time. Why would I even want to export the entire project? I can't even think of a use case.

Working with sectors I run a script to add all the used files to the project, then export the lot. Its my default use case.

**Comment by manavortex** [comment]
> Working with sectors I run a script to add all the used files to the project, then export the lot. Its my default use case.

OK, very fair :) How often do you filter those when you don't want to export? 

Is click+modifier viable? That way, we could have both behaviours in one button
