### ISSUE TITLE
localMaterials.materials don't update names when adding/removing list items

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1231]
Updating the displayed material names after changes in the materialEntries list works like a charm. However, it's not yet working the other way around:

https://user-images.githubusercontent.com/965785/226109354-3bd50e47-f20d-4f00-9c97-f51bd3fac1cd.mp4

After adding or removing items from the list (or drag&drop, changing the order), material names won't update until I open and close the mesh. It would be great if it could do that automatically as well :)

**Comment by seberoth** [comment]
Fixed with 07c5790
