### ISSUE TITLE
MultiMesh Export is broken

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/WolvenKit#1232]
**Describe the bug**
Multimesh export fails for a combination of files/rigs that exported fine previously

**To Reproduce**
1. Add base\characters\main_npc\hanako\t0_001_wa_body__hanako.mesh and base\characters\main_npc\hanako\h0_001_wa_a__hanako\h0_001_wa_a__hanako.mesh to a project
2. go to the export tool, select the t0 body mesh and switch the options to multimesh.
3. Add both meshes to the meshes list
4. Add woman_base.rig, woman_base_deformations.rig and h0_001_wa_a__hanako_skeleton.rig to the rigs list
5. Click on Export selected
7. See log for error about RigTools.cs

**Expected behavior**
In the 19/1/23 nightly the above steps result in 1/1 files being exported successfully and a combined mesh/rig glb being generated.

**Versions :**
Tested & Broken in:
 - main
 - WolvenKit-8.8.2-nightly.2023-03-18
 - WolvenKit-8.8.2-nightly.2023-03-05
 - WolvenKit-8.8.2-nightly.2023-01-31
 - WolvenKit-8.8.2-nightly.2023-01-27

Worked in 
- WolvenKit-8.8.2-nightly.2023-01-19

**Comment by seberoth** [comment]
Duplicated of #1225
