### ISSUE TITLE
Setting to change double clicking behavior between add to project and view file

### ISSUE THREAD

**Issue by pharingWell** [WolvenKit/WolvenKit#1236]
**Is your feature request related to a problem? Please describe.**
When working with large mods, or projects that have many added files, double clicking a file can be a fatal mistake: it causes the program to stall and often times requires using Task Manager to close

**Describe the solution you'd like**
I'd love for the ability to change what double clicking does in settings

**Comment by rfuzzo** [comment]
you mean in the Asset Browser?

**Comment by pharingWell** [comment]
Yes, I'd love an option in settings that changes what double clicking does in the Asset Browser

**Comment by rfuzzo** [comment]
closing as not planned
