### ISSUE TITLE
Access denied to the path when building after update to 8.9.0

### ISSUE THREAD

**Issue by gewfsmc** [WolvenKit/WolvenKit#1238]
Hey,

I've just updated to latest release and started receiving this error:

`[3/20/2023 6:19:13 PM] Message: Access to the path '\\?\E:\path\to\folder' is denied.
Source: System.Private.CoreLib
StackTrace:    at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at WolvenKit.App.Controllers.RED4Controller.SafeDirectoryDelete(String path, Boolean recursive) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Controllers\RED4Controller.cs:line 585
`

when building a project.
Couldn't find anything related in wiki or on github and was hoping for some help.

Thanks!

**Comment by rfuzzo** [comment]
I think the solution to that kind of error is to manually delete the ModName/packed folders. Upon investigation this may be caused by a handle on the folder from some cloud backup service like google drive.
