### ISSUE TITLE
Project Tree UI: Recursive folding/unfolding on modifiyer+click

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1248]
## Feature request: 
When shift-clicking on a node in the project tree, expand or collapse all of its children (based on the folding state of its first child)
When shift-ctrl-clicking on a node in the project tree, expand or collapse all of its children (based on the folding state of its first child)

### Example:
![image](https://user-images.githubusercontent.com/965785/227570060-5de79dd7-bc2c-4bbe-aab3-016414f0ad54.png)
Shift-click on "misc" should **collapse** all children, but leave the grandchildren alone.
Shift-ctrl-click on "misc" should **collapse** all nested folders.

## Reasoning: 
While porting props, my project tree inevitably ends up looking like this:
![image](https://user-images.githubusercontent.com/965785/227569658-73585bb4-c706-476a-9d55-2b5c96842484.png)

![image](https://user-images.githubusercontent.com/965785/227570467-cd626739-f87e-4668-ac7f-76adcfe3decb.png)
I'm aware that these buttons exist and I'm frequently using them, but they don't quite cut it. My workflow would improve a lot if this could be implemented.

**Comment by rfuzzo** [comment]
not in scope sorry
