### ISSUE TITLE
mlsetup: visually mark layers with opacity == 0 

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1252]
![image](https://user-images.githubusercontent.com/965785/227777281-71d7025d-1df6-41cb-bb37-0055a033b3f0.png)

It would be great if layers with opacity 0 could be visually.. I'd sigh highlighted, but I actually want the opposite. They're inactive, so it'd be good if they could be indicated as such in the file viewer.

**Comment by seberoth** [comment]
I'm against it.
Changes which applies to certain workflows for certain users shouldn't become the standard for all users/workflows.

**Comment by manavortex** [comment]
I don't mean disable highlighting, I mean "make them visually distinct via grey font or something", since they're effectively not active

**Comment by seberoth** [comment]
I know what you mean. Still no.

**Comment by manavortex** [comment]
Okay? Because MLSB does that, and it's as much the standard workflow for multilayersetups as it can get, no? I'm curious as to which workflow wouldn't benefit from immediately seeing which of the layers are disabled?

**Comment by seberoth** [comment]
The CR2W editor is still a raw file editor.
And as such, I'm against doing visual changes based on some "higher" level logic.

**Comment by effs** [comment]
I think semantic visualization is a good thing to have — but rather than encode specific semantics at the UI level, maybe this would fall under a more general 'warning' category? That way the specific validation logic can be kept to type level, but there's a clear indicator when the user should take a look at something.

**Comment by manavortex** [comment]
I fixed this at some point
