### ISSUE TITLE
Mesh preview completely breaks for some meshes

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1258]
When I'm porting props, it frequently happens that the mesh preview is completely blank, as in, no appearances, no mesh:

![image](https://user-images.githubusercontent.com/965785/228935079-f4fae6d8-209f-432b-afc7-587331f81b2d.png)

The "File Information" preview works, but as soon as materials are involved, everything is broken. Even once I'm done porting and the meshes render correctly in-game, the material preview will stay blank.

I haven't exactly been able to reproduce it. I think it's only for items with multiple appearances and a mix of external and local materials? Anyhow, I attached an example (the mesh is inside the materials folder).

[materials.zip](https://github.com/WolvenKit/WolvenKit/files/11115022/materials.zip)

**Comment by seberoth** [comment]
The preview doesn't like the fact, that 2 materials have the same name
![grafik](https://user-images.githubusercontent.com/456881/228947743-a5a6d431-b36f-40ac-9ac1-91f3bca0fca9.png)

Is that a valid scenario?

**Comment by manavortex** [comment]
One of them will do nothing, but the material is at least very defined ':D Copy-paste mistakes there. I wouldn't expect that to break the preview?

There are no exceptions or anything, it's just empty.

**Comment by manavortex** [comment]
> Yeah, exceptions are surperessed for the preview. Don't know why
Probably because there were a lot? :'D IDK

I'd say the first definition, same loading behaviour as the rest?
