### ISSUE TITLE
Import Scale to Streaming Sector Nodes Along with pos and rot

### ISSUE THREAD

**Issue by DoctorPresto** [WolvenKit/WolvenKit#1260]
Currently when importing nodes to a streaming sector using the "import from JSON (no coords update)" we are unable to import scale information even though it is part of the node data.. This would be extremely valuable and help with user additions to the world tremendously. I've included in the zip both the currently working import format and the desired format including the scale.
[import jsons.zip](https://github.com/WolvenKit/WolvenKit/files/11130762/import.jsons.zip)

Worth noting as well that when we import a full streaming sector as .json, we can currently import the scale along with the rest of the node data no issue at all

**Comment by seberoth** [comment]
Did the Object Spawner recently add scale?
Any other props which are missing?

**Comment by DoctorPresto** [comment]
Object spawner doesn't yet support scale, but I wrote a python script to
convert some of the large AMM presets to object spawner format in order to
add them to the game properly but without scale it means manually adjusting
2000+ nodes.

Won't be a problem to either add scale to object spawner (or at least just
have it output scale as x1, y1, z1) to ensure it doesn't cause any
compatibility issues.

As far as I can see there's nothing else missing which should be included.

**Comment by seberoth** [comment]
And why doesn't you import the AMM json?

**Comment by DoctorPresto** [comment]
That would be because I didn't realize I could :D
I guess we can just close this request as complete. Thanks Seb!
