### ISSUE TITLE
Mesh Export/Import messes up Dino Vest right half Spikes Normals

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1272]
**Describe the bug**
It seems that exporting dino's vest messes up the right half of the spike no matter if you've put it in blender to edit or not, just straight export/import messes it up. Only the right half tho which is odd. It's also not double sided submesh. 

**To Reproduce**
1. Add base\characters\main_npc\dino\t2_001_ma_vest__dino.mesh to project
2. Export the mesh to glb
3. Import the glb back into mesh
4. Go in game with the mesh (I did mesh replacement) and see error

**Expected behavior**
It should look like vanilla mesh. 

**Version (please complete the following information):**
 - Tested on nightly 2023-04-12 as well as stable 8.9.0

**Screenshots**
Top is vanilla mesh, bottom is WolvenKit exported/imported mesh
![photomode_12042023_222937](https://user-images.githubusercontent.com/20621809/231761254-2c41b096-5320-43ea-b7e8-12afc59c13f4.png)

**Comment by seberoth** [comment]
Probably fixed with #2076
