### ISSUE TITLE
Unbundle Game doesn't Unbundle Game but opens Depot folder

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1280]
![image](https://user-images.githubusercontent.com/965785/232835899-d00c9a60-bad2-442a-89e0-601b73e72c37.png)

18.04 Nightly

**Comment by seberoth** [comment]
Works like expected.
The folder is always opened after finishing unbundling.

If you do not load a project before clicking the button or load the archives manually, there is nothing to unbundle.

**Comment by manavortex** [comment]
I would have expected it to unbundle the entire game - just like "export materials", but with more data. Because that one worked, even though I wasn't in a project. 

Is it expected that the two buttons have different logic there?

**Comment by seberoth** [comment]
No...

Wasn't aware that the other one works.

**Comment by manavortex** [comment]
haha, the bug is the opposite of the bug that I thought it was!
(But maybe disable the buttons and display a hint that the user needs to have a project open for this?)
