### ISSUE TITLE
Disable "Launch" button during import tasks

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1281]
While Wolvenkit is processing files (e.g. import), trying to launch the project will lead to an exception, since it obviously can't get an exclusive lock on the file to pack it. 

It would be good to deactivate the Install and Launch button while other tasks are running to prevent that sort of exception.

Unrelated: The "Install and Launch" button is optically much less prominent than its neighbours and seems deactivated, even if it isn't
![image](https://user-images.githubusercontent.com/965785/232860371-04c474a6-b66b-49b8-8a17-41f33b7afcc2.png)

**Comment by seberoth** [comment]
You don't get more...
Already wasted 4 hours on that...

**Comment by manavortex** [comment]
I'm so sorry.

**Comment by manavortex** [comment]
Maybe leave it open and document what you did that didn't work, in case somebody else feels like taking a stab at this?
