### ISSUE TITLE
Quality of live and small performance improvements to WolvenKit.Modkit.Scripting

### ISSUE THREAD

**Issue by paulober** [WolvenKit/WolvenKit#1287]
**Describe the bug**
Some minor improvements to the codebase could be made in `ScriptService.cs`:
1. Use the `Stopwatch.StartNew()` method to create and start a new Stopwatch instance.

Some minor improvements to the codebase for `WKitScripting.cs`:
1. Use the C# `readonly` modifier for fields that are only set in the constructor and should not be modified afterward, such as `_archiveManager` and `_redParserService`.
2. ~~In the `GetArchiveFiles()` method, the return type can be changed to `IEnumerable<FileEntry>` to provide better type information.~~
3. Use expression body for simple getter like methods for a consistent code style

**Comment by seberoth** [comment]
> In the GetArchiveFiles() method, the return type can be changed to IEnumerable<FileEntry> to provide better type information.

Nope, caused issues with ClearScript.

**Comment by paulober** [comment]
@seberoth Sorry, just saw this in your comment. I'll skip this change.

**Comment by paulober** [comment]
@seberoth I just wanted to ask you if it's ok for me to add more quality of live improvements to this repository. I am a big C# enthusiast and a big fan of the project and CP77 mods. So I would like to contribute something, and since I'm not that good at modding I thought fixing and implementing small QoL and naming scheme PRs for this project might help some to focus more on features and bugs and at the same time I'm also learning the codebase to maybe fix bugs or implement a new feature someday.

**Comment by seberoth** [comment]
@paulober 
Sure, we are happy for anyone who wants to help :)
If you want to know something or discuss stuff, feel free to ask us on our Discord server

**Comment by paulober** [comment]
@seberoth All right, glad to hear it. Just thought it might be a bit annoying if I keep requesting relatively many PRs with small improvements. However, I could try maybe a few commits in a PR together, would that be allowed? 

For questions `wolvenkit-dev` channel is the right one, am i wrong?

**Comment by seberoth** [comment]
@paulober 1. Yeah, thats allowed^^ No need to make a new PR for every problem you find
2. `wolvenkit-dev` is the right one for dev stuff

**Comment by paulober** [comment]
@seberoth Found the channel but I have no permission to talk there...
