### ISSUE TITLE
resources: nested file structure of yaml leads to extra-nesting

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1296]
**Describe the bug**

In the current (23.05.) nightly, nested folders in resources aren't correctly packed to the game folder anymore, but instead have an incorrect level of nesting.

**To Reproduce**
1. Have a file in `resources/r6/tweaks/myfile.yaml`
2. Pack the project (I used the "Pack" button in the taskbar)
3. Expectation: The file should be in `r6/tweaks/myfile.yaml`
4. Actual: The file is in `r6/tweaks/r6/tweaks/myfile.yaml`

**Comment by rfuzzo** [comment]
that's intended as .yaml files when created go into the folder without nesting and get put into the correct location on pack.

we could add a warning on pack if a yaml file is found in a nested folder. hmm
