### ISSUE TITLE
Multimesh exporter issues

### ISSUE THREAD

**Issue by eaguull** [WolvenKit/WolvenKit#1298]
**Describe the bug**
In Wkit 8.9.0 and 8.9.1 Multimesh export is broken, it returns an error even with right export settings. Export succeeded in 8.8.0 with exact same settings.

**To Reproduce**
https://wiki.redmodding.org/cyberpunk-2077-modding/modding-know-how/3d-modelling/dangle-bones/moving-a-dangle-chain
'multimesh export' part. When the described process (with the same settings) is attempted in 8.9.0 or 8.9.1, wolvenkit returns an error.

**Expected behavior**
like... no error and working export idk?

**Version (please complete the following information):**
 - 8.9.0 and 8.9.1 (works in 8.8.0)

**Screenshots**

**Comment by seberoth** [comment]
It would be helpfull if you also could post the error

**Comment by Simarilius-uk** [comment]
are you trying it with or without the use new exporter box checked?

**Comment by eaguull** [comment]
![image](https://github.com/WolvenKit/WolvenKit/assets/124358865/f4c6dc4d-7bf4-4d02-b637-c9ff7f5bf32f)
Error when using classic exporter

**Comment by eaguull** [comment]
![image](https://github.com/WolvenKit/WolvenKit/assets/124358865/a457c4d7-eb41-45ab-8884-e2091bcaffea)
This error appears when the 'use new importer' box is checked. The settings, additional meshes and rigs are still exactly the same as used for a working export in 8.8.0.

**Comment by seberoth** [comment]
> ![image](https://user-images.githubusercontent.com/124358865/241746441-f4c6dc4d-7bf4-4d02-b637-c9ff7f5bf32f.png) Error when using classic exporter

This should be fixed in the next nightly.

Not sure about the bone issue and why it happens now / has worked before
