### ISSUE TITLE
Errors when editing player item app file without deleting default appearance

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1307]
**Describe the bug**
When editing player item app file such as base\gameplay\items\equipment\underwear\appearances\player_underwear_item_appearances.app, if default appearance is not deleted, when you save it will give an "TypeError: Cannot read properties of null" error, but will save the file. 
If you duplicate the default appearance, it will give a "Object reference not set to an instance of an object." error and not allow you to save unless you delete the duplicated default appearance. 

**To Reproduce**
1. Add player_underwear_item_appearances.app to project and open it
2. Save the file, get the TypeError error
3. Open appearances and duplicate the default appearance(the first one)
4. Try to save the file, get error and unable to save. 

**Expected behavior**
It should work like any other appearances and shouldn't give error. 

**Version (please complete the following information):**
 - Tested on latest nightly 2023-06-16

**Screenshots**
First error
![image](https://github.com/WolvenKit/WolvenKit/assets/20621809/a178b815-cade-4863-a711-a72279ad486f)
Second error
![image](https://github.com/WolvenKit/WolvenKit/assets/20621809/de7dd681-1ebb-4021-99c7-b4bba06cc1bb)
[player_item_app_errors.txt](https://github.com/WolvenKit/WolvenKit/files/11771869/player_item_app_errors.txt)

**Comment by seberoth** [comment]
Should be fixed with 4188c9d
