### ISSUE TITLE
File import/export settings: persistent across restarts per project

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1335]
It would be extremely convenient if changes in the import/export settings would be persistent across restarts of Wolvenkit. Could they be stored in the project settings, perhaps on a depot path base?

![image](https://github.com/WolvenKit/WolvenKit/assets/965785/c0a8b01f-ba29-4d0b-a3e4-b4ab5a2c33b3)

**Comment by rfuzzo** [comment]
too minor
