### ISSUE TITLE
Scripting: FileExists returning "false"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1338]
I ran into this when trying to enable file validation for .mi files. The corresponding changes are on the branch `file-validation-changes`

**Describe the bug**
FileExists returns false, although the depot path is present in the project. I did "copy relative path" and pasted it into the field, just to rule out any 10Ts on my end.
[archive.zip](https://github.com/WolvenKit/WolvenKit/files/12138374/archive.zip)

**To Reproduce**
1. Check out `file-validation-changes`
2. Download the attached example project
3. Open `velvet_brown_light.mi`
4. Save it
5. See the warning from FileValidation's `checkDepotPath`

Both `velvet_brown.mi` and `velvet_brown_light.mi` are daisy-chained to `velvet_base.mi`, which should show warnings because at the very least the normal texture is missing. If you set up `velvet_brown_light.mi` to use `velvet_brown.mi` as a base material, you'll get a longer daisy chain.

This only happens for the baseMaterial property in .mi files and the strings look okay. I'm completely stymied, so I'm probably overlooking something obvious again.

**Comment by seberoth** [comment]
Not a bug...
