### ISSUE TITLE
QOL (Mesh): Display name for externalMaterials (same as with localMaterials)

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1339]
As it says in the title: it would be great if external materials could display their names in the list, like it works with local materials: 
![image](https://github.com/WolvenKit/WolvenKit/assets/965785/c242ed5e-f94b-424a-aec2-cd07341bb972)

It would be a great help with visually spotting fuck-ups during index assignment (validation doesn't properly check for this yet, and due to our initial implementation, there are issues with mixed materials. I'm trying to come up with a performant implementation for that).

I'm absolutely willing to implement it myself, I just can't figure out how. Feel free to throw me a pointer :)

**Comment by seberoth** [comment]
Duplicate of #1233
