### ISSUE TITLE
Manual Precise Camera Control in CyberPunk2077

### ISSUE THREAD

**Issue by Rahul29392** [WolvenKit/WolvenKit#1341]
**Is your feature request related to a problem? Please describe.**
It's just a thing that came to my mind. First thing, I am not so much of a player but more of a programmer. I was wondering if we can control camera movement with spline (gui) and automate character position, driving/drinking/or enjoying the view within a game and movement like defined walking/running and record it as video and create a movie from it. My goal is to create a video and direct the camera movement and actions of the character and make a movie out of it with stunning visuals and graphics and 4k mods.

**Describe the solution you'd like**
Is that feasible with this kit ?

**Comment by dragonzkiller** [comment]
This is not possible with wkit. There are similar systems with IGCS and AMM.
