### ISSUE TITLE
.xbm -> png export: "Flip Image" does nothing

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1342]
# Description

Checking the "Flip Image" box when exporting an xbm to png will not result in a flipped image. [Bug verified by Auska](https://discord.com/channels/717692382849663036/808086068023918603/1137482743832395868), so it's not just me this time :P

# Version
8.9.1-nightly.2023-07-28

**Comment by seberoth** [comment]
Please us the latest nightly. Already fixed with d9f420c
