### ISSUE TITLE
Add enableMask to the materials.json

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/WolvenKit#1355]
metal_base determines if it has alpha or not based on the enableMask flag which is an mt variable rather than a parameter. Its not currently written to the material.json so I cant access it in a normal glb export to see if a material should use transparancy or not. 

Would be great if it could be added to the material.json so that the plugin could access it, I have the node setup ready to take a boolean value, all works just cant get at the value.
From my testing the value thats set highest in the mi/mt chain gets used by the material.

**Comment by rfuzzo** [comment]
is this still relevant?

**Comment by seberoth** [comment]
Done with 9d37065
