### ISSUE TITLE
[compression mode issue] Imported texture shows up as black in-game

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1366]
**An imported texture shows up as black and matte in-game**
If I import my texture with the default settings (TEXG_Generic_Color), it shows up as black and matte in-game. The texture is named `colourchecker_d01`, so Wolvenkit should pick the right settings.

I have to switch compression from `TCM_QualityColor` to `TCM_None` to make it show up in-game (hat tip to Presto)

1. Prerequisite: CET and AMM
2. Install the attached project [wolvenkit_example_broken_texture.zip](https://github.com/WolvenKit/WolvenKit/files/12642271/wolvenkit_example_broken_texture.zip)
3. Start the game, open AMM's decor tab and spawn the prop `aaaaaaaaaaaaaaaaa spawnme` (it's in `Misc`)
4. Behold the broken texture:
  ![image](https://github.com/WolvenKit/WolvenKit/assets/965785/007d2e88-e06a-4e7f-94de-6c454a7a55e5)
5. Via Import Tool, import colourchecker_d01.png with compression mode `TCM_None`
6. repeat Step 3
7. The texture works now
  ![image](https://github.com/WolvenKit/WolvenKit/assets/965785/c425eaf5-3768-47dd-b425-e53bd4e54133)

I have no idea what's behind this, but I would've lost my mind without Presto's tip. If we can't find and fix the reason behind this, maybe we should change the default import compression mode for `TEXG_Generic_Color` to `TCM_None` for the time being.

**Comment by seberoth** [comment]
Was already fixed. Was related to uneven image dimensions, which doesn't work with compression
