### ISSUE TITLE
Memory Leak during file export

### ISSUE THREAD

**Issue by thunderysteak** [WolvenKit/WolvenKit#1367]
**Describe the bug**
When exporting larger amount of files, WolvenKit will just keep on filling the memory until the host OS locks up from being OOM.

In my case, I was trying to bypass an unrelated issue where the exporter didn't export the materials during model export, so I decided to export all materials, which caused WolvenKit to fill up the entirety of RAM and committing over 70GB to swap/pagefile before the system locked up.

It's like it never runs garbage collection on files it worked on and are no longer needed.

**To Reproduce**
1. Import Base > Characters > Appearances into project
2. Open the export tool
3. Export All
4. Watch the memory fill up.

**Expected behavior**
For Wolvenkit not to memory leak and do memory cleanup for files it's not using

**Version (please complete the following information):**
 - WolvenKit 8.9.1-nightly.2023-09-17

**Screenshots**
![firefox_2023-09-17_18-13-36](https://github.com/WolvenKit/WolvenKit/assets/16468437/f6958ab6-d7ec-4c8f-8207-7f8c19156fa0)

**Comment by FronkenZeepa** [comment]
![image](https://github.com/WolvenKit/WolvenKit/assets/145403079/e92ce9d5-050d-44d0-95b4-c837e8362f6d)
I have also noticed this happening, on the September 18th Nightly. I was testing something for Doctor Presto, so I used the export vehicle ent script on Judy's .ent file, and my ram usage shot up to 100% shortly afterwards, then leveled out to just shy of 12gb, which WolvenKit was sitting on until I closed and reopened.

**Comment by seberoth** [comment]
Should be fixed
