### ISSUE TITLE
Update for 2.0

### ISSUE THREAD

**Issue by seberoth** [WolvenKit/WolvenKit#1369]
TODO:

- [ ] Wait for Red4Ext
- [x] Dump classes (partly done)
- [x] Update hashes
- [ ] Update RedDB
- [ ] Test everything
- [ ] Run the unit tests
- [ ] Release

**Comment by pradd2004** [comment]
I was looking for ua-ua localization files today, in 2.0 patch, but they are not displayed in Asset Browser as a separate folder. However it is possible to open them manually by using  paths from editor of upper level files
![image](https://github.com/WolvenKit/WolvenKit/assets/1121923/072eddff-c462-46e7-bc63-b68d67e2c050)
