### ISSUE TITLE
Mod browser: search field for archives

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1372]
The mod browser could use a filter field for toplevel archives.

Especially with the non-intuitive ordering, it's currently a pain to find any specific archive file. A filter field would help a lot.

(In addition, sorting by alphabet would probably also be more user-friendly. Is the current sort order identical to the load order? or inverted load order?)

**Comment by rfuzzo** [comment]
you can search for `archive:modname` in the AB to filter for that, but yeah an actual filter would be good
