### ISSUE TITLE
Asset Browser Missing mappin Files for Phantom Liberty

### ISSUE THREAD

**Issue by cozzbp** [WolvenKit/WolvenKit#1377]
**Describe the bug**
Asset Browser using the latest version doesn't show .mappin or .poimappins files for the DLC. 

**To Reproduce**
1. Open wolvenkit
2. open asset browser
3. search for .poimappins

**Expected behavior**
.poimappins file should be present for ep1

**Version (please complete the following information):**
 - 8.11.0-nightly.2023-09.27

**Comment by seberoth** [comment]
Thanks for the report.
The file is actually there, just the search function is broken...
Just go manually to the path (base\worlds\03_night_city\_compiled\default\03_night_city.poimappins) for now

**Comment by seberoth** [comment]
Fixed in nightly
