### ISSUE TITLE
cp77tools throws error when attempting to convert default_dialogs.questphase

### ISSUE THREAD

**Issue by khuongTiet** [WolvenKit/WolvenKit#1381]
**Describe the bug**
When using the cp77tools cli to convert `default_dialogs.questphase` file, the cli throws an error

**To Reproduce**
Use `cp77tools` cli to convert the `default_dialogs.questphase` file into a .json file

```
cp77tools convert s default_dialogs.questphase
```

Stacktrace:
```
[ 0: Information ] - Found 1 files to process.
[ 0: Error       ] - Unable to cast object of type 'WolvenKit.RED4.Types.DynamicBaseClass' to type 'WolvenKit.RED4.Types.IScriptable'.
[ 0: Error       ] - Message: ConvertToText
Source: WolvenKit.Modkit
StackTrace:    at WolvenKit.Modkit.RED4.ModTools.ConvertToText(ETextConvertFormat format, String infile, Boolean skipHeader) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\RedConverter.cs:line 30
   at WolvenKit.Modkit.RED4.ModTools.ConvertToAndWrite(ETextConvertFormat format, String infile, DirectoryInfo outputDirInfo) in D:\a\WolvenKit\WolvenKit\WolvenKit.Modkit\RED4\RedConverter.cs:line 60
[ 0: Information ] - Elapsed time: 4810ms.
```

**Expected behavior**
Expect the tool to convert the file to a .json file with no errors thrown

**Version (please complete the following information):**
 - Used the CLI installed via [WolvenKit.Console-1.10.0.zip](https://github.com/WolvenKit/WolvenKit/releases/download/8.10.0/WolvenKit.Console-1.10.0.zip)

**Screenshots**

**Comment by rfuzzo** [comment]
No longer occurs in 1.11
