### ISSUE TITLE
Wolvenkit throws exception when trying to conect to github

### ISSUE THREAD

**Issue by Elliesium** [WolvenKit/WolvenKit#1382]
**Describe the bug**
Installing anything by WK GUI throws exception saying access was forbidden to github.com at port 443 (HTTPS)

**To Reproduce**
1. Launch WK (Nightly 8.11 or 8.10)
(Optional):
2. Go to plugins
3. Click install on any plugin

**Expected behavior**
WK checks for update or in case of pressing install - installs a plugin

**Version (please complete the following information):**
 - Version 8.10
 - Version 8.11 [Nigthly]

**Screenshots**
Automatic Check for Update on Launch of WK:
![image](https://github.com/WolvenKit/WolvenKit/assets/146141713/396bcc3c-aa7f-414b-b465-16b80fd2500a)
After clicking install (wk-resources but anything does it)
![image](https://github.com/WolvenKit/WolvenKit/assets/146141713/4a67ed0f-89f8-4347-a2f7-47fe4f2264fa)

**Comment by seberoth** [comment]
Sorry for the late response.
Something is blocking the access to https://github.com on your end.
Had the same problem on the Discord just now and here it was a VPN / Split Tunneling problem.

**Comment by rfuzzo** [comment]
yes, I checked and it works on the latest nightly
