### ISSUE TITLE
Wkit becomes unresponsive when deleting arrayitems in a .mesh file

### ISSUE THREAD

**Issue by spliffz** [WolvenKit/WolvenKit#1386]
**Describe the bug**
When deleting arrayitems for materials in the following arrays it sometimes becomes unresponsive, takes CPU and breaks certain UI elements which results in to having to kill the application.

**To Reproduce**
1. import glb with 1 mesh in it
2. move and rename
3. open .mesh file in wkit

4. Delete in this order:
all but entry 0 in 'materialEntries' with 'Delete Selection in array/buffer'
save file.
all but entry 0 in 'localMaterialsBuffer > materials' with 'Delete Selection in array/buffer'
save file
all but entry 0 in 'appearances' with 'Delete Selection in array/buffer'
save file
all but entry 0 in 'appearances[0].chunkmaterials' with 'Delete Selection in array/buffer'

And then it stops. Items are not being deleted. WKit becomes unresponsive and certain UI elements go blank.
Have to kill the application and restart it to continue

**Expected behavior**
The arrayItems to be deleted.

**Version (please complete the following information):**
- Wolvenkit 8.11.0-nightly.2023-10-03

**Screenshots**
Rightclick context menu doesn't respond.
![WolvenKit_2023-10-03_19-28-27](https://github.com/WolvenKit/WolvenKit/assets/5054095/efef3dc7-9ad4-404a-bd7e-b6609adb9a9a)
CPU Load:
![Taskmgr_2023-10-03_19-29-52](https://github.com/WolvenKit/WolvenKit/assets/5054095/df2e564d-b4ae-400a-9188-8dd09be865a0)

**Comment by seberoth** [comment]
Yeah, had that to recently. Will check it when I find time to work on WolvenKit again...

**Comment by manavortex** [comment]
We fixed this with the CVM changes
