### ISSUE TITLE
Very slow when trying to preview streaming sector files

### ISSUE THREAD

**Issue by KrAt0s210** [WolvenKit/WolvenKit#1389]
**Describe the bug**
Wkit hangs and stops responding after trying to preview the sector files. 
**To Reproduce**
1. Go to any interior or exterior .streamingsector file
2. open it and click on sector preview

**Expected behavior**
Wkit stops responding and ram usage spikes up to 99%

**Version (please complete the following information):**
 - Version 8.11.0-nightly-2023-10-03

**Screenshots**
![Screenshot 2023-10-04 175136](https://github.com/WolvenKit/WolvenKit/assets/94441663/1663208c-cb01-468a-bc51-c86a45ce5f02)
![Screenshot 2023-10-04 175003](https://github.com/WolvenKit/WolvenKit/assets/94441663/a8b3d59a-9b78-4335-946f-3b8c187ff4e1)

**Comment by seberoth** [comment]
Should be fixed with 8200473
