### ISSUE TITLE
Mod Browser: search ignores archive

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1392]
[CLOTHING_KALA_CROP_LED_JACKET.zip](https://github.com/WolvenKit/WolvenKit/files/12839971/CLOTHING_KALA_CROP_LED_JACKET.zip)

At first I thought this was due to the CAPS LOCK IN THE ARCHIVE FILE NAME, but the search works fine regardless of that. For some reason, this archive is ignored silently (but I can browse it manually)

**Comment by seberoth** [comment]
More info pls.

Can find the file just fine. Maybe some other archive overwrites the file?
![grafik](https://github.com/WolvenKit/WolvenKit/assets/456881/b6090992-63d1-43a9-aacc-17c35b8d08e3)

**Comment by manavortex** [comment]
Right, I forgot to include the relevant part of the ticket, which was that I was searching by archive file name `archive:CLOTHING_` (or the full name). 
If you can't reproduce, feel free to close it immediately

**Comment by yohoZHENG** [comment]
Can not convert .ttf to .fnt is that a bug?

**Comment by seberoth** [comment]
> Can not convert .ttf to .fnt is that a bug?

1. Please create a new report for a new issue
2. Yes, will be fixed in the next nightly
