### ISSUE TITLE
Error when exporting Herrera Riptide to Blender

### ISSUE THREAD

**Issue by jkerman2000** [WolvenKit/WolvenKit#1394]
To reproduce: load the Herrera Riptide .ent file in Wolvenkit Nightly from 10/8/2023, then run the export vehicle ent script.
Bug: most meshes and materials cannot be loaded from the depot, despite said depot being fully regenerated upon download of the 2.0 patch and Phantom Liberty.
Observations: The entity and appearances can be fully loaded in the entity preview window. Also, the export appearance with rig button works perfectly (without any textures).

**Comment by DoctorPresto** [comment]
What version of the blender plugin?

**Comment by jkerman2000** [comment]
Latest version, but it doesn't seem to be an issue with the blender plugin.

**Comment by Simarilius-uk** [comment]
Try with the latest nightly, there was a bug in the entity export wscript that got fixed the other day

**Comment by jkerman2000** [comment]
Still broken. I'll try regenerating the entire depot again.

**Comment by DoctorPresto** [comment]
No need to generate the whole depot, just change the name of your current depot folder and re export the meshes. You only need the material depot for mlsb

**Comment by seberoth** [comment]
Same as always. All files it can't find are embedded files...
Nothing you can do about and will take some time until we can do anything about it
