### ISSUE TITLE
Some audio exports have a looping issue

### ISSUE THREAD

**Issue by SouljaVR** [WolvenKit/WolvenKit#1396]
Hi,

For some reason, some exported audio from Wolvenkit/Wwise has an issue where the audio will loop continuously in the exported audio for a certain duration. For example exporting 'v_mq033_m_2ff7b1e9b46fc000' becomes looped in the audio itself. I dont know if it affects specific files or any at random per export.

For example if I export a 1 second voiceline of V saying "Name's V", the exported audio will be 20 seconds long with "Name's V, Name's V, Name's V, Name's V, Name's V, Name's V, " constantly for the entire thing. This makes voice conversion projects incredibly tedious. It seems to affect a small amount of audio, but enough to be game breaking. Maybe every 10 voice lines per 1000 exported. Others have mentioned the same behaviour who are working on voice conversion projects.

**Comment by seberoth** [comment]
Not a wkit bug.
Only happens for en-us vo's. All other languages are fine.
Tried to convert using the latest version of vgmstream and the same happens.

So either its a bug in vgmstream or something is off with the wem.
Will dig again into it later

**Comment by NightDocs** [comment]
I'll confirm that this is indeed an issue and it boils down to the choice to use vgmstream. I'd recommend switching to ww2ogg and not using the export tool. Would recommend adding a warning to the export tool when exporting audio files if they can't make a switch to something other than vgmstream any time soon.  I also have only tried wav and mp3 files and haven't checked to see if ogg files have the same looping issue when exporting.
