### ISSUE TITLE
Disable file validation while mod browser is open

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1404]
While the mod browser is open, no project files can be found because WKit is looking in the other context. Instead of running the onSave hook, it'd be good to print a warning to console instead that the feature is disabled while the mod browser is open.

**Comment by seberoth** [comment]
Sure, can do that. But tbh, don't know how much sense it makes to lookup in mods anyway (is an oversight of me).
Could also just force lookup in base files.

Whatever you prefer

**Comment by manavortex** [comment]
Oh, wow, I thought that was super-impossible :) Maybe force lookup in base files?
