### ISSUE TITLE
Crash when browsing extracted files in project tree

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1405]
**Describe the bug**

**To Reproduce**
1. Extract the attached .archive file and install it
2. In the mod browser, add all the files from the archive to your project
3. Click on 10971943052883425263.mesh in the base dir (or fx_braindance.mesh)
4. Watch it crash and burn

**Version**
Most recent Nightly as of 27.10.

**Comment by seberoth** [comment]
> Extract the attached .archive file

Not possible without attachment

**Comment by manavortex** [comment]
[basegame_vs_apartment_red_black.zip](https://github.com/WolvenKit/WolvenKit/files/13194830/basegame_vs_apartment_red_black.zip)
I swear, github hates me sometimes

**Comment by manavortex** [comment]
Still crashing on most recent Nightly the moment I click on 10971943052883425263 in the mod browser D:
