### ISSUE TITLE
Textures Darker in Game

### ISSUE THREAD

**Issue by XilaMonstrr** [WolvenKit/WolvenKit#1413]
**Describe the bug**
Many types of textures show up darker in game. TGA files show up darker without any alteration when simply exported and re-imported via Wkit. PNG and DDS files show up darker when resaved in any other application and then re-imported.

**To Reproduce**
For TGA: Export textures, import textures.
For PNG or DDS: Export textures, resave in another application (photoshop, chaiNNer, etc), import textures

**Expected behavior**
Textures to be able to save correctly in other applications, and to be able to export and import without it affecting the tone in-game.
Also, the original game textures appear to be BC1 format, and when wkit exports DDS it does so as 16-bit RGBA instead of their original file format.

**Version (please complete the following information):**
I have tried 8.11.0 stable, and nightlies from 10-27 and 11-1.

**Screenshots**
![VANILLA](https://github.com/WolvenKit/WolvenKit/assets/105951863/bbebb3ed-14dc-41c7-9121-0c954a1aa2ca)
![DARKER](https://github.com/WolvenKit/WolvenKit/assets/105951863/d177afb1-d613-4457-bbc7-3d467b5d60d8)

**Comment by XilaMonstrr** [comment]
More info on discord:
https://discord.com/channels/717692382849663036/1168301607323185234
https://discord.com/channels/717692382849663036/1166760450176864346

**Comment by seberoth** [comment]
> Also, the original game textures appear to be BC1 format, and when wkit exports DDS it does so as 16-bit RGBA instead of their original file format.

Thats "normal". The texture you are testing is a 16-bit RGBA file compressed with BC1. To work with the file we need to export the uncompressed version (this info isn't saved in the dds, PS wouldn't know which on to use).
As long as you use the correct settings on reimport, it should compress it again.

Whats the filepath of the texture you used for testing?

**Comment by XilaMonstrr** [comment]
> Thats "normal". The texture you are testing is a 16-bit RGBA file compressed with BC1. To work with the file we need to export the uncompressed version (this info isn't saved in the dds, PS wouldn't know which on to use). As long as you use the correct settings on reimport, it should compress it again.
Ok thanks.

> Whats the filepath of the texture you used for testing?
Mostly I'm testing raw\base\surfaces\materials\asphalt\asphalt_generic\asphalt_generic_01_300_d
But having the same issue with any other textures I've tried.

Also, I forgot to note that I have been restoring the xbm's to original before export and import, and loading vanilla settings for import.

**Comment by XilaMonstrr** [comment]
If any additional testing or information is needed let me know. I'd love to be able to start making mods for this game again. Thanks for all your hard work!

**Comment by XilaMonstrr** [comment]
11-22 nightly resolves the issue with textures being darker, but causes performance to tank. FPS drops from 120 to 20

**Comment by rfuzzo** [comment]
Hmm, I need to check if import is uncompressed now

**Comment by XilaMonstrr** [comment]
The file size is the same as before

**Comment by seberoth** [comment]
@XilaMonstrr Would it be possible that you upload your project?

**Comment by XilaMonstrr** [comment]
It's 3.2GB, so I can upload it to nexus on send a link via DM on discord

**Comment by rfuzzo** [comment]
![image](https://github.com/WolvenKit/WolvenKit/assets/37657287/bfd122ce-75d3-4bb1-8e43-e28abed85055)
okay, so I checked and the size of the imported xb, does (as usual) depend on the import settings. For comparison:
1. vanilla ... 1.845mb
2. default import settings (just clicking import) ... 3.6mb
3. using the game-setting (click "load settings") ... 1.855mb

**Comment by XilaMonstrr** [comment]
> ![image](https://user-images.githubusercontent.com/37657287/285501963-bfd122ce-75d3-4bb1-8e43-e28abed85055.png) okay, so I checked and the size of the imported xb, does (as usual) depend on the import settings. For comparison:
> 
> 1. vanilla ... 1.845mb
> 2. default import settings (just clicking import) ... 3.6mb
> 3. using the game-setting (click "load settings") ... 1.855mb
> 
> It seems like you used non-optimal import settings.

No, I have been loading settings from vanilla, also the file size is the same

**Comment by XilaMonstrr** [comment]
> @XilaMonstrr Would it be possible that you upload your project?

Send me your nexus username and I will share access.

**Comment by XilaMonstrr** [comment]
> hmm I see these differences in imported/vanilla xbm settings ![image](https://user-images.githubusercontent.com/37657287/285504214-4fc891e4-4173-4d07-bfe9-f62604eaefda.png)

Yep, those happen automatically and stay that way even when I load settings from vanilla. It has always been that way. But also even with old nightlies where the textures were darker those settings were the same.

I'll upload a couple individual files.

**Comment by XilaMonstrr** [comment]
Original single files are here now, I'll get the xbms up soon as well:
https://drive.google.com/drive/folders/1P-3ibPobi9D9YLEkRKm43bL7SN1FC1py?usp=sharing

**Comment by XilaMonstrr** [comment]
I have both versions of the complete mod that I'm trying to make uploaded to nexus.
Darker version made with 10-27 nightly, and heavy performance hitting version made with 11-22 nightly
The mod is unpublished so it's hidden
https://www.nexusmods.com/cyberpunk2077/mods/10331
@rfuzzo I granted you access
@seberoth if you send me your nexus username I can also grant you access

**Comment by rfuzzo** [comment]
thanks, I looked at them and they have identical settings. 🤔 
Also, I haven't actually touched any xbm import-related functionality since 10-27 afaik. I'm really not sure what could be the problem of the lag

**Comment by XilaMonstrr** [comment]
Very strange...
What specifically changed with the 11-22 nightly?

**Comment by rfuzzo** [comment]
just the export (no longer dark raw textures)

**Comment by XilaMonstrr** [comment]
Really weird then. Trying to think of how to test this to eliminate possibilities...

I could try importing the new textures with the 10-27 nightly to see if that is any different?
Maybe also mess around with vanilla export and import to see if affects performance?

I also sent the nexus link to a friend to test in his game to see if it tanks performance on someone else's system, he was testing the darker textures before.

**Comment by rfuzzo** [comment]
https://github.com/WolvenKit/WolvenKit/compare/bfef2dd...3445467
that's all the changes since Oct 26th.

>I could try importing the new textures with the 10-27 nightly to see if that is any different?
That's a good idea!

**Comment by XilaMonstrr** [comment]
Ok thanks so much, I have to head out for the day but will do more testing tonight.

**Comment by XilaMonstrr** [comment]
Alright, I have an unfortunate and strange report.
1. My friend tested and got the same results of tanked performance with the import via 11-22 nightly
2. I tested files exported via 11-22 nightly and imported w/ 10-27 nightly and got the same results
3. Strangely, with the files from #2, some but not all are darker than vanilla.

![VANILLA](https://github.com/WolvenKit/WolvenKit/assets/105951863/612af8f8-0edb-402a-b8f5-462d2cabf54a)
![Mod 10-27exportandimport](https://github.com/WolvenKit/WolvenKit/assets/105951863/e0f969f7-f5c8-402e-89c0-7f14de358b91)
![Mod 11-22export 10-27import](https://github.com/WolvenKit/WolvenKit/assets/105951863/a010f1f7-25b8-4bde-9229-3082e65081d7)

**Comment by XilaMonstrr** [comment]
Well, strangely I am unable to replicate the original results of superior performance. 
I tried repeating exporting PNG files, editing them, and then updating them, all from the 10-27 nightly and the performance tanks.
So the question may be more about why it didn't affect performance so much previously and does now, I have no idea.

Thanks for your help in fixing the darker textures. I'll drop this for now and let you know if I have any further insights.

**Comment by rfuzzo** [comment]
Hej @XilaMonstrr I made a new wkit test build, would you like to test it out?
https://drive.google.com/file/d/1Sb4jTixXgLRMBVfPC7FZw6VDq1KNWr12/view?usp=drive_link

**Comment by XilaMonstrr** [comment]
New nightly isn't better on performance. I've realized that there's something about DLSS resolution scaling with these altered textures that make it necessary. Something about the way they're handled by the game engine makes it more vital.

I'll go ahead and close this issue, thanks so much for working on it and figuring out what we could!

**Comment by rfuzzo** [comment]
> New nightly isn't better on performance. I've realized that there's something about DLSS resolution scaling with these altered textures that make it necessary. Something about the way they're handled by the game engine makes it more vital.
> 
> I'll go ahead and close this issue, thanks so much for working on it and figuring out what we could!

But the old WolvenKit before the changes still has good performance on 2.1?
