### ISSUE TITLE
Save embedded mlsetup/mlmask easily

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1458]
**Is your feature request related to a problem? Please describe.**
The mlsetup I want to edit only exist embedded in the mesh it's used in. I know I can probably copy attribute by attribute to recreate the mlsetup but that is way too tedious, and I tried exporting to json and overriding the mlsetup part in another json but that didn't work either (potentially manual error on my part but I wouldn't really know). 
For mlmask I feel like having to save individual layers down and rebuild with a masklist is also very tedious. 

**Describe the solution you'd like**
I'd like the ability to right click on the tab of an embedded file and have the option to save it, either pop up a new window to let us select where to save to, or automatically save it in the same folder as the file it's embedded in. 
![圖片](https://github.com/WolvenKit/WolvenKit/assets/20621809/5e7db416-38ba-434d-8dd5-a53f01c57911)

**Comment by DoctorPresto** [comment]
In tools - script manager, if you run the "export mesh" script, it'll make local copies of the embedded materials that you can use.
