### ISSUE TITLE
Edited inkwidget causes game crash.

### ISSUE THREAD

**Issue by heavymoonarch** [WolvenKit/WolvenKit#1470]
Modified via wkit version 8.11.2-nightly, inkwidget causes the game to crash. When editing inkwidget from a game version 1.63 through 8.9.0, the game starts normally.

**Comment by seberoth** [comment]
Need more info. Like what file, what did you change, ...

Just opened a random inkwidget, changed some values and the game launched fine.

**Comment by heavymoonarch** [comment]
I change 911_turbo_ui.inkwidget, for example I just change the opacity parameter from 0 to 1 and save the file, the game does not start anymore
![image](https://github.com/WolvenKit/WolvenKit/assets/130565366/3e736e93-8af6-46f3-b74b-e38c3460a9f1)
![image](https://github.com/WolvenKit/WolvenKit/assets/130565366/42e85ed8-e9bf-45ea-85e4-71e3fbb02d99)
![image](https://github.com/WolvenKit/WolvenKit/assets/130565366/652be4ac-3885-4e34-95c8-d4ba19a84e32)
![image](https://github.com/WolvenKit/WolvenKit/assets/130565366/a577ff8d-fa1b-4556-987d-8d36d338512a)
[mod_911_turbo_ui.zip](https://github.com/WolvenKit/WolvenKit/files/13589977/mod_911_turbo_ui.zip)
[orig_911_turbo_ui.zip](https://github.com/WolvenKit/WolvenKit/files/13589984/orig_911_turbo_ui.zip)

**Comment by seberoth** [comment]
Tried both my own modified and your modified one. Both work fine for me.
Even drove with the Porsche 911 Turbo through the city to make sure.

Latest nightly: 9.11.2 (2023-12-06)
Game version: 2.1
