### ISSUE TITLE
Unable to import replacement .wav files as of patch 2.1

### ISSUE THREAD

**Issue by khaganmv** [WolvenKit/WolvenKit#1472]
As of patch 2.1, importing .wav files named after specific .wem files to replace them does not work.

Steps to reproduce:
1. (If you haven't already) Set the Game Executable Path to the version 2.1 .exe, click Save & Close and restart Wkit.
2. Place [533464258.wav](https://drive.google.com/file/d/1sUI5LP7gCNs1Lq2g-oJpeWisxng65iom/view?usp=sharing) in raw/ (533464258 is the .wem file that corresponds to the English audio of the intro cinematic). You can also just create an empty file called 533464258.wav to reproduce the bug.
2. Import Tool > Select 533464258.wav > Import Selected
3. See the empty archive/base/sound/soundbanks/ folder
4. See the lack of error logs

This previously generated a corresponding .opus file under raw/ and corresponding .opusinfo and .opuspak files under archive/base/sound/soundbanks/.

- Wkit version 8.11.1 
- Cyberpunk 2077 version 2.1

**Comment by seberoth** [comment]
Will add better logging in the future, but it seems that `533464258` doesn't exists anymore since 2.1

**Comment by khaganmv** [comment]
I checked eventsmetadata.sjon and the wwise id of the event also remains the same (2364279097). I used wwiser to dump cp_music.bnk to double-check if all wems also remained the same:

CAkEvent (ulID: 2364279097) > Action (ulActionID: 113384784) > ActionInitialValues (idExt: 723208066)

Looking up 723208066 gives 11 AkMediaInformation objects and 533464258 is the sourceID of one of them.

Not sure if this is useful, but I thought I'd share my findings in case it is of any help.

**Comment by seberoth** [comment]
Thats 2 different things.

One part of the audio data is stored as `.wem` files (together with info in `eventsmetadata.json`)
The other are `.opuspak` files with info in `.opusinfo`.

Also we will probably remove the `.opuspak` / `.opusinfo`. SInce you need to edit the opusinfo for that and only one mod at a time could then use that method.

**Comment by khaganmv** [comment]
Thank you for the explanation. It seems the file was entirely removed from the opus part of things then. `sfx_container_1701.opuspak` used to contain a single .wem file, which was the audio in question, but now it contains several different sfx.

By the way, where did you find the 533464258 file?
