### ISSUE TITLE
The Log window heavily impacts performance and stability.

### ISSUE THREAD

**Issue by BlankFX1** [WolvenKit/WolvenKit#1475]
**Describe the bug**
The Log window heavily impacts performance and stability as it gets filled with lines over time and can even make WolvenKit unresponding and go "white window mode".

**To Reproduce**
1. Asset Browser
2. Filter for something that produces a list with a vast amount of files. e.g. `en-us V_ .wem`.
3. Select all -> Right click -> Add selected items to project.

While in the first seconds, the import will stay fast (e.g. 80 files per second), the extraction will become extremely slow after a short amount of time (e.g. 2 files per second).

**Workaround**
Clearing the Log by clicking that cool little icon in the lower right of the Log Window will clear it and reset the import speed back to normal. This has to repeated until the Import has finished.

**Expected behavior**
The speed of import/extraction is not bound to the amount of data in the log window.
I assume this could be fixed by moving the log window process to its own Thread.

**Version (please complete the following information):**
 - All I recently tested with WolvenKit-8.11.2-nightly.2023-12-06 being the most recent one.

**Comment by rfuzzo** [comment]
Thank you, done.
