### ISSUE TITLE
Installing Redscript from plugin view installs the wrong version

### ISSUE THREAD

**Issue by rmarquis** [WolvenKit/WolvenKit#1476]
**Describe the bug**
On a clean Cyberpunk2077, REDmod and Wovenkit installation, installing Redscript from the Plugins section will lead
 to an error at launch. This is seemingly happening because the Install/Update button is installing the 0.6.0-M8 (newer, but unstable) version of redscript, _despite reporting the installed version as being the stable version (0.5.16)_.

As a workaround, manually grabing the 0.5.16 zip file on GitHub and dezipping it in the game forlder solves the issue.

**To Reproduce**
1. Install game from scratch, with REDmod support
2. Install last WolvenKit nightly
3. In Plugins, install Redscript and any dependent plugin or mod (f.e. TweakXL plugin)
4. At launch, see Redscript launching a compilation error

**Expected behavior**
The game can launch with automatically installed plugins. The redscript version installed is the latest stable version, as reported by the version shown in UI.

**Version (please complete the following information):**
 - 2077 + PL version 2.1 (GOG)
 - WolvenKit: latest nightly

**Screenshots**
![Screenshot_2023-12-10_214254](https://github.com/WolvenKit/WolvenKit/assets/162442/dbdd3c4a-395f-4b40-9e5d-64891a228018)

**Comment by rmarquis** [comment]
The issue seems to be located in `WolvenKit.App/Services/PluginService.cs` in the `InstallPluginAsync`. Check the releases array returned by the `Octokit` API call [here](https://github.com/WolvenKit/WolvenKit/blob/3fbc34c476f0a1aba4b03d8a97d46f61f7b249c8/WolvenKit.App/Services/PluginService.cs#L265).

**Comment by rfuzzo** [comment]
Yeah it grabs the prereleases as well. I need to dig into the octokit documentation or refactor the whole method.
