### ISSUE TITLE
Scripting Support

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#148]
**Is your feature request related to a problem? Please describe.**
Add scripting support to Wkit. We can combine this perhaps with the Console, or get rid of the console once we have scripts.

**Describe the solution you'd like**
We have an IronPython solution in the git history, and this is something relatively easy to do. 
As for UI, we can take inspiration from Ghidras scripting Tools:

![ghidra_scriptTools](https://user-images.githubusercontent.com/37657287/77222188-59b86080-6b51-11ea-96fa-71bdf955737c.jpg)

**Comment by Traderain** [comment]
We can maybe even use this: https://github.com/cyotek/ScriptingHostDemo

**Comment by Traderain** [comment]
So i just found this: https://github.com/waf/replay-csharp
![image](https://user-images.githubusercontent.com/6411732/94265350-a33a9b80-ff38-11ea-97e1-30e8e61c5d5c.png)
Maybe we could:
 - [ ] Fork the repo and integrate it into wkit
 - [ ] Reference all the wkit dlls when launched
 - [ ] Figure out a way to get runtime variables?
This would be pretty neat imo
