### ISSUE TITLE
"Recent Projects": improve usability

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1485]
Due to the fact that project naming corresponds to .archive file naming, my refit projects are named similarly to the "master" project. This leads to something like this: 
![image](https://github.com/WolvenKit/WolvenKit/assets/965785/f9622c08-6193-4254-bd22-fa2f08b5df9f)
… where I can't see which refit is which without mouseover-hovering.

**Describe the solution you'd like**
- https://github.com/WolvenKit/WolvenKit/issues/1090
- a text filter that'll hide items which don't match
- a list view that'll show the full project names and filepaths (optimally, WKit would remember my setting)
Lazy solution:
- truncating at the beginning rather at the end…?

**Comment by seberoth** [comment]
Is this good now?
