### ISSUE TITLE
Resources plugin can't resolve some paths under ep1

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1497]
Nightly 03. Jan 2024

Find Files Using This shows nothing for e.g. `ep1\characters\garment\player_equipment\head\h1_001_mask__swim_mask\h1_001_pwa_mask__swim_mask_ep.mesh`, although it's used by `ep1\characters\garment\player_equipment\head\h1_001_pwa_mask__swim_mask.ent`

**Comment by seberoth** [comment]
Works for me

![grafik](https://github.com/WolvenKit/WolvenKit/assets/456881/7f06e7ff-a879-4b80-9dbc-6f3184dbc396)

**Comment by manavortex** [comment]
Damn! Do I have to invalidate some cache or anything?
Or (and I know it's a stretch), could this be related to https://github.com/WolvenKit/WolvenKit/issues/1498 somehow?
