### ISSUE TITLE
"Copy Selection From Array/Buffer": "Paste into…" stays disabled until I "Copy From"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1498]
Nightly 03 Jan 2024

Unfortunately, I'm not quite sure how to reproduce this, but I've repeatedly run into it, and it happened to Fronky as well. I'm attaching a video of the problem.

A restart of Wolvenkit fixes the issue until I run into it the next time.

https://github.com/WolvenKit/WolvenKit/assets/965785/12501bfe-c297-4e79-8f36-609f4dd3b48f

**Comment by FronkenZeepa** [comment]
Just like mana said, I've had the same issue on and off. I never tried restarting wkit though because I wasn't doing a whole lot of copying, but it's an interesting issue nonetheless. And I think it's been ongoing since the 2.0 update? But don't quote me on that.

**Comment by manavortex** [comment]
Fixed by now
