### ISSUE TITLE
[Bug] WolvenKit not terminated correctly after closing the application

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#1508]
**Describe the bug**
The WolvenKit application hangs in the background after exiting, not utilizing any system resource other than staying in the system memory, taking up a good chunk of it. The WolvenKit log also doesn't tell anything useful.

It has been occuring for me since some nightly versions of 8.9 and continued through 8.10 release and nightlies.

**To Reproduce**
Currently steps to reliably reproduce the bug are unknown, but it seems to occur after loading a project, and then exiting the application.

**Expected behavior**
The application to be terminated accordingly.

**Version (please complete the following information):**
 - Version 8.9/8.10 + Nightly

**Screenshots**
[applog20240110.txt](https://github.com/WolvenKit/WolvenKit/files/13895380/applog20240110.txt)

![image](https://github.com/WolvenKit/WolvenKit/assets/17293117/01596ec4-ac24-463d-b367-3f35d7e4fecd)

**Comment by DoctorPresto** [comment]
Have also experienced this with 8.12 and latest nightly. Seems to happen inconsistently but I'll take some screens, try to get more context next time it happens

**Comment by DoctorPresto** [comment]
I haven't noticed this for several nighties now, not sure what changed but can probably close this issue

**Comment by seberoth** [comment]
> not sure what changed

Me neither, but sure^^ If it happens again, feel free to reopen it
