### ISSUE TITLE
Exporter hangs forever when trying to export mesh

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1511]
**Describe the bug**
When exporting vase_1.mesh (or template_textured from the same folder), the exporter hangs. For vase_1, it does so at 10% progress, for the other near the end. The file opens fine in WKit and spawns in game, the export just never seems to finish and I'm not sure what's happening.

[source.zip](https://github.com/WolvenKit/WolvenKit/files/13922893/source.zip)

**To Reproduce**
1. Use the source folder in the attached zip
2. export `manavortex\amm_props\maroccan_dreams\vases\vase_1\meshes\vase_1.mesh`

**Version (please complete the following information):**
nightly.2024-01-10, previous version is also affected.

**Comment by effs** [comment]
Looks like `manavortex\\amm_props\\maroccan_dreams\\materials\\emissive_purple.mi` has a basematerial loop

**Comment by manavortex** [comment]
ahhhh, shit, user mistake - why does file validation not catch this? Need to fix.

Can we prevent this from happening?

**Comment by effs** [comment]
I think fixed by https://github.com/WolvenKit/Wolvenkit-Resources/commit/0c9a0a37632613e40c396e8f4169341b93942bad ?
