### ISSUE TITLE
Accessor[18] JOINTS_0[31]: Is out of bounds

### ISSUE THREAD

**Issue by DevMaxiss** [WolvenKit/WolvenKit#1517]
**Describe the bug**
Tried to export a mesh, but I received an OOB error.  I've tried to also disable "Export Materials/Garment Support", but that didn't work.

The mod does have a prerequisite if that helps: https://www.nexusmods.com/cyberpunk2077/mods/3890?tab=files?

**To Reproduce**
1. Add the `.mesh` to archives in wolvenkit project
2. tools > export > select `t0_000_pwa_extra_06`
4. export selected 
5. error pops into console :(

**Expected behavior**
Should be able to extract the mesh into a `.glb`

**Version (please complete the following information):**
 - 8.11.0
 - 8.12.0
 - 8.12.1-nightly (2024-01-15)

[t0_000_pwa_extra_06.zip](https://github.com/WolvenKit/WolvenKit/files/13947333/t0_000_pwa_extra_06.zip)

**Comment by DoctorPresto** [comment]
Just to clarify, are you trying to export one of the empty meshes from nims mod or a mesh from a mod that uses nims as a prereq?

**Comment by DevMaxiss** [comment]
I am only trying to export the attached file (t0_000_pwa_extra_06.zip).

**Comment by seberoth** [comment]
Use the `Experimental` export. Seems to work fine.
![grafik](https://github.com/WolvenKit/WolvenKit/assets/456881/cd11504e-e58e-412c-a3a5-4d1767e5d296)
