### ISSUE TITLE
Texture Import reverting to previous or no texture

### ISSUE THREAD

**Issue by sammilucia** [WolvenKit/WolvenKit#1523]
**Describe the bug**
Using Tools > Import to import a texture (in this case a dds LUT), the texture is either broken or reverted to the old texture on Save.

**To Reproduce**
1. Bring e.g. `cp2077_gen_lut_ep1_sdr_v002` into your project
2. Double click the newly imported `cp2077_gen_lut_ep1_sdr_v002` in _Project Explorer_ to open / activate it
3. Select **Tools** > **Import**
4. Select the new texture you want to import
5. (Notice that the new texture is now visible under _File Information_ > _Image_)
6. Select **File** > **Save**
7. (Notice that the _File Informatoin_ > _Image_ has either reverted to the old texture, or is now showing no image)
8. Pack the mod
9. (Notice that the mod is probably broken, and of unpredictable size)

**Expected behavior**
The imported texture remains imported on Save, and pack into a mod correctly.

**Version (please complete the following information):**
- 8.12.0-stable
- 8.12.1-nightly.2024-01-18

**Workarounds**
1. Double-click the texture in the _Project Explorer_
2. Select _Texture Preview_
3. Right-click and select **Replace Texture**
4. Select **File** > **Save**
5. (Notice the texture is correctly saved, the bug is not reproduced in this workflow)

**Screenshots**
Please **click** to see video steps to repro
[![Watch the video](https://github.com/WolvenKit/WolvenKit/assets/3295286/5fa1ae2d-3236-4d20-bd97-4fae5620817b)](https://github.com/WolvenKit/WolvenKit/assets/3295286/68b6fa8f-ed3b-470e-bba0-f8771c315c56)

**Comment by seberoth** [comment]
Thats somehow expected.
When you open a file and overwrite it then (either via import or replacing the file in the folder) the already opened one has still the old data. So if you save it then, the old data will get written again.

**Comment by sammilucia** [comment]
did you click the image to watch the video? i don't think any user will expect this behavior, the UI shows different data in two areas 😊

**Comment by seberoth** [comment]
No, didn't see it. No play button, no video :P

Still the answer is the same. The opened file is in memory (and so is the preview) and the property window is based on the "physical" file.

But I understand you concerns. Only 2 options I see here:
1. Disable importing files when they are currently opened
2. Force close open files if they are getting imported

**Comment by seberoth** [comment]
Also not sure why it doesn't show a preview after import. But thats another problem^^
Also could update to nightly. LUT previews are hald8 images now and wkit support import/export lut cube files

**Comment by manavortex** [comment]
IMO reloading the opened file (closing and re-opening) would probably be best, wouldn't it?

**Comment by sammilucia** [comment]
https://github.com/WolvenKit/WolvenKit/assets/3295286/68b6fa8f-ed3b-470e-bba0-f8771c315c56
video ^ 😊

I'm on nightly and using hald.

yes I see what you're saying, and it makes sense. it's confusing to the user, however.

ideal workflow would be
1. import texture
2. modal -> "Open asset has changed, reload? (changes will be lost)" (a-la notepad++, gedit)

though reality is if you've imported, changes will already be lost, so ideally the workflow should be:
1. importer has a clear note that "Any changes to open assets will be overwritten"
2. modal -> "Open asset has changed, reload?"

the above would catch edge case after imports, where the user accidentally overwrites their import and it's not clear what happened.

**Comment by sammilucia** [comment]
(also hald and cube are _wonderful_)
