### ISSUE TITLE
Project Explorer: Improve context menu (Suggestion/discuss)

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1530]
# Suggestion
Please discuss! Maybe we can reach a better consensus!

<img width="824" alt="image" src="https://github.com/WolvenKit/WolvenKit/assets/965785/1fe36022-adee-47aa-870c-a2411af45dc9">

**1. Open in MLSetupBuilder**
Entry (and separator) should be hidden if the file isn't under raw

**2. Export**
- Export entries should be grouped
- **3. with export tool** entry: cause export of file as if the user had selected it from the export tool, with the currently-configured settings. (Is this even possible?)
- **3. if possible**: Would be good to have the same with "import" for files under `raw`

**4. Copy relative path**
Title should be updated based on modifier pressed. I've already implemented the functionality, but was too lazy to edit the GUI.

**5. Open in Asset Browser**
Deactivate entry if the file _has_ no representation in the asset browser (shortcut: if the relative path doesn't start with `base/`). 
What about the mod browser?

**6. Replace with original** 
Deactivate entry if the file _has_ no original game file (shortcut: if the relative path doesn't start with `base/`). 
What about the mod browser?
Are dzk's changes for the mod browser relevant here? "Replace with file from archive", for example if we have several instances of the file from several archives?

**Comment by seberoth** [comment]
1. Yeah, was like that previously. Some update borked that. WIll look at it
2/3. There is no "to XML".
  a. For Export I need to look when I'm home
  b. If Export is possible, probably should also do a `with import tool` for raw files
5/6. Will look into it. Shortcut wouldn't work for `engine` / `ep1` files though

**Comment by manavortex** [comment]
fixed by now :)
