### ISSUE TITLE
Mods built on WK v8.12.0+ causing mod conflicts and texture issues

### ISSUE THREAD

**Issue by CyanideX** [WolvenKit/WolvenKit#1531]
**Description**
Users have reported various issues when installing mods built on versions of WolvenKit 8.12.0 and above that result in player eyes, commonly alongside modded eyes, returning to vanilla or becoming completely black.

I have had reports of a few of my mods causing issues with player eyes that do not even touch eye mesh or player assets. Specifically, my mods modify the mesh parameters of vegetation and trash which seem to have an effect on player eyes.

One user mentions:
> Experiencing the same, using Unique Eyes Core and (Almost) Real Eyes. Some appear plain white, some orange, some black etc but all solid.

One user suggested building on an older version of WolvenKit and mentioned that they were able to resolve the issue by using version 8.11.1.
![image](https://github.com/WolvenKit/WolvenKit/assets/3106700/ae7dfcf7-471e-4b34-b4c6-aa20845545a1)

**To Reproduce:**
1. Install [Trash Begone](https://www.nexusmods.com/cyberpunk2077/mods/12269) or [Wind Begone](https://www.nexusmods.com/cyberpunk2077/mods/12252).
2. Install [(Almost) Real Eyes](https://www.nexusmods.com/cyberpunk2077/mods/4546)
3. Check player eyes in the customization screen.
4. Eyes will not appear as intended.

**Expected behavior:**
Custom eye textures and vanilla eyes should appear as intended while installing another mod that doesn't touch those same assets.

**Version:**
 - Cyberpunk 2077 v2.1 - 12872066
 - Built on WK 8.12.1 2024-01-24

**Screenshots:**
Posted by a user showing the reverting of modded eyes back to vanilla when installing Trash Begone:
![image](https://github.com/WolvenKit/WolvenKit/assets/3106700/51b37799-3867-435a-8660-62f4a7bf06b9)

**Comment by seberoth** [comment]
Followed the steps you provided and whatever your mod is installed or not, eyes are fine for me.
Also the screenshot provided isn't really helpfull, since the user selected different eyes in both pics

**Comment by seberoth** [comment]
Maybe related to #1509

**Comment by CyanideX** [comment]
I'm still receiving comments on my mods that they're causing black eye issues. 

![image](https://github.com/WolvenKit/WolvenKit/assets/3106700/32fa80bc-3026-4ee4-8961-d604283ed0e8)

My latest [Blur Begone](https://www.nexusmods.com/cyberpunk2077/mods/8105) update, built on WK 8.12.3-nightly.2024-02-04+00.

I've suggested they contact the author of the custom eye mods to see if building on different versions resolves the issue. I'm not sure how it would fall on me to use an older version when my assets aren't even related to eyes. 😅

**Comment by seberoth** [comment]
Even if it still were a WolvenKit issue, as long as none of us can reproduce it, its hard to say anything about it.
So not sure what to tell you
