### ISSUE TITLE
Copy Tweak Name in Tweak Browser

### ISSUE THREAD

**Issue by BhaktijPatil** [WolvenKit/WolvenKit#1532]
![image](https://github.com/WolvenKit/WolvenKit/assets/39721836/aff3a1d8-cb3b-404f-83fc-87279aa8fa48)

Currently the "copy value to clipboard" button in tweak browser does nothing, and the "copy to clipboard" option in tweakXL submenu copies the whole tweak. A lot of times, I just wanna copy statusEffect names, statModifiers, etc. Currently I copy the whole tweak and erase everything but the name.

Make a new button that let's users copy just tweak names.

**Comment by BuffMcMuff** [comment]
+1
