### ISSUE TITLE
Keep document tab position after automatic reloading

### ISSUE THREAD

**Issue by seberoth** [WolvenKit/WolvenKit#1537]
**Is your feature request related to a problem? Please describe.**
Keep document tab position after automatic reloading

Not possible right now, but before "someone" asks for it...

**Comment by manavortex** [comment]
+1, I would pay actual money for this, especially if the "oh, you duplicated an array entry? Let's just scroll back to the top of the file, shall we?" bug would be addressed as well. (I tried to link the issue that I created, but couldn't find it…)

**Comment by seberoth** [comment]
That has nothing to do with this one. Please keep it seperated

**Comment by manavortex** [comment]
Oh, okay! Thought it'd be the same Syncfusion... thing. Will do o7
