### ISSUE TITLE
Streamingsector nodeData copy/paste and export/import not working

### ISSUE THREAD

**Issue by Akiway** [WolvenKit/WolvenKit#1543]
**Describe the bug**
Got an issue with streaminsector nodeData export/import and copy/paste not working.
I want to copy/export one or more nodeData from a sector and paste/import into another sector.
The copy/paste function does work for nodes.

**To Reproduce**
Steps to reproduce the behavior with copy/paste:
1. Open a streaming sector, `Copy from Array/Buffer` a nodeData
2. Open another sector -> no paste option available

Steps to reproduce the behavior with export/import:
1. Open a streaming sector, `Export to JSON` a nodeData
2. Open another sector, `Import from JSON (no coords)` does nothing and throw a warning `"Could not recognize the format of your JSON"`

**Expected behavior**
For copy/paste -> A paste option should be available when a nodeData got copied.
For export/import -> The import should handle the same JSON format as the format provided by the export

**Version (please complete the following information):**
 - Version Wolvenkit 8.12.2-nightly.2024-01-28

**Comment by DoctorPresto** [comment]
Node data refers to specific entries in the node array. Without the actual node the node data is meaningless. In order for this to work in wkit, it would need to copy both, paste them both into their respective arrays and update the reference within nodedata to make sure it points to the right entry in the array. 

That said, even with the node and node data, this would almost definitely not lead to the desired result in game. From a mod development perspective, you should definitely not be copy pasting nodes between sectors. Please see the wiki for world editing workflows or feel free to @ me on discord if you'd like some help with whatever you're trying to achieve.

The import from json function is meant to import jsons produced by object spawner (and to a lesser extent amm) this is why you're getting the message you're getting. Not sure if it would make sense to support nodes exported from another sector for the reasons mentioned above.
