### ISSUE TITLE
Strange bug with the texture on the right hand after import

### ISSUE THREAD

**Issue by Sett788** [WolvenKit/WolvenKit#1546]
Has anyone encountered a bug where when you put on clothes, strange seams appear on the character's shoulders?
![Right hand seam-](https://github.com/WolvenKit/WolvenKit/assets/158290449/9d3cca1b-a532-4e86-95eb-3f85dcd6a2c1)

I could easily solve this problem by editing these files using Wolvenkit and Blender:
right hand - _base\characters\common\player_base_bodies\player_female_average\arms_hq\a0_000_pwa_base_hq__r.mesh_
left hand - _base\characters\common\player_base_bodies\player_female_average\arms_hq\a0_000_pwa_base_hq__l.mesh_

And I managed to fix my left hand:
![Shoulder fix-](https://github.com/WolvenKit/WolvenKit/assets/158290449/bdd2e2c0-809c-45c9-a9dc-e33e2d91329b)

But when I import the right hand file through Wolvenkit and turn on the game, the seam disappears, as it should, but a strange bug appears with the texture on the right hand:
![Wolvenkit bug](https://github.com/WolvenKit/WolvenKit/assets/158290449/186fdb37-857a-4a85-861a-ae3abc134380)

I've been struggling with this for many days now, tried different settings, but still couldn't fix it. It's probably Wolvenkit bug. I read that I'm not the only one having problems with righ hand file.

[Here](https://github.com/WolvenKit/WolvenKit/issues/1245)

This happens regardless of the program version.

**Comment by effs** [comment]
The seam is [GarmentSupport](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-creators/3d-modelling/garment-support-how-does-it-work). You might have to recreate it for the body and arms or use a body mod where it's fixed (or entirely deleted.)

**Comment by Sett788** [comment]
> The seam is [GarmentSupport](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-creators/3d-modelling/garment-support-how-does-it-work). You might have to recreate it for the body and arms or use a body mod where it's fixed (or entirely deleted.)

I know why the seam occurs and I fixed it by simply removing the transformations that Garment Support does (simply changing shapekeys in blender). The problem occurs after importing the file back into .archive format. Even if I do not carry out any manipulations in blender, but simply export the file and immediately import it, this problem with the texture on the hand appears.

**Comment by effs** [comment]
> I know why the seam occurs and I fixed it by simply removing the transformations that Garment Support does (simply changing shapekeys in blender).

This is not a fix. It's not intended to work like that, so it can lead to further problems or just not solve the original problem.

It is possible that there's still some issue with the calculation on import but because it _generally_ works (even on the exact same model as you say), you need to check that the model is correct when exporting it from Blender — i.e. that the submesh boundaries are correct, UVs are correct and contiguous, normals are correct, and that they're all also correct with GarmentSupport (or alternatively you can try to remove GarmentSupport from the entire player model, not just arms, so that the feature is broken everywhere the same way.)

**Comment by Sett788** [comment]
> > I know why the seam occurs and I fixed it by simply removing the transformations that Garment Support does (simply changing shapekeys in blender).
> 
> This is not a fix. It's not intended to work like that, so it can lead to further problems or just not solve the original problem.
> 
> It is possible that there's still some issue with the calculation on import but because it _generally_ works (even on the exact same model as you say), you need to check that the model is correct when exporting it from Blender — i.e. that the submesh boundaries are correct, UVs are correct and contiguous, normals are correct, and that they're all also correct with GarmentSupport (or alternatively you can try to remove GarmentSupport from the entire player model, not just arms, so that the feature is broken everywhere the same way.)

The thing is, I didn't remove Garment Support drom hands... It's still there.

As for UV and normals, I checked all this and compared it with left hand. Everything is fine and looks identical to each other.

**Comment by revenantFun** [comment]
can confirm just like above that even without doing anything to a glb beyond exporting it and importing it straight back in, no blender, that just the right leg is somehow getting flipped on these pants. 
![before](https://github.com/WolvenKit/WolvenKit/assets/149233165/42fae621-76fc-44d3-b31e-1442b1aedc62)
![affter](https://github.com/WolvenKit/WolvenKit/assets/149233165/e9aff7c3-1255-4341-9e4a-cd2faf0ed901)
