### ISSUE TITLE
widget preview crashes wkit

### ISSUE THREAD

**Issue by barisbatur0** [WolvenKit/WolvenKit#1555]
when I preview some widgets (especially complex ones) wkit freezes for a while and then closes

**Comment by dragonzkiller** [comment]
> when I preview some widgets (especially complex ones) wkit freezes for a while and then closes

do you have an example widget that crashes?

**Comment by barisbatur0** [comment]
fixed no more crashes, but sometimes wkit freezes or shows nothing when previewing
