### ISSUE TITLE
Broken WidgetPreview

### ISSUE THREAD

**Issue by Berdagon** [WolvenKit/WolvenKit#1568]
**Describe the bug**
trying to use the widgetpreview of large inkwidgets will show nothing and throw an out of memory exception:
[2/14/2024 12:28:51 PM] [Error    ] Unhandled exception in WolvenKit v8.12.3.0
[2/14/2024 12:28:51 PM] [Error    ] Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Out of memory.)
Source: 
StackTrace: 

based on my understanding inkwidget files are a main root container and several other library items and these library items are all loaded via script and are not all added to the main root widget and trying to load all of them together may be the cause of out of memory my suggestion would be to separate every library item and make a dropdown selection(like appearance selection in meshpreview) to select different library items and loading them separately

**To Reproduce**
1. open a large inkwidget file(i used ripperdoc.inkwidget)
2. select widgetpreview
3. wait

**Expected behavior**
showing the widgetpreview

**Version (please complete the following information):**
 - Version 8.12.3.0

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/60521745/7be31b70-d07c-47ef-8df3-467049edd8f8)
![image](https://github.com/WolvenKit/WolvenKit/assets/60521745/4d543e4c-068e-4350-917d-2b39ab4523aa)

**Comment by seberoth** [comment]
Has nothing to do with the size of the inkWidget/libraries.
"Just" some calculation errors while drawing the widget.
Will see if I can fix it asap.
