### ISSUE TITLE
Export streamingsector to json not working correctly

### ISSUE THREAD

**Issue by anon56003269** [WolvenKit/WolvenKit#1577]
**Describe the bug**
When converting a streamingsector from WolvenKit to json, the HandleIds are not correctly generated for nodes. This results in nodeData->NodeIndex no longer matching up with the correct nodes->HandleId in the json file. Viewing the streamingsector directly in WolvenKit is fine, only exporting to json causes this issue.

**To Reproduce**
1. Go to Wolvenkit
2. Add exterior_-4_6_0_0.streamingsector to your project
3. Right click it in archive -> Convert to JSON
4. Open resulting json in text editor
5. Observe that the HandleIds get incremented for nested spot HandleId, effectively skipping HandleId 1 at the base level, which causes nodeData->NodeIndex not to match up correctly with nodes->HandleId from that point forward to the rest of the exported json. For example, nodeData->NodeIndex = 145 in WolvenKit, but in the exported json it is 173, which no longer matches the nodeData[311]->NodeIndex = 145 in both WolvenKit and json.
```
      "nodes": [
        {
          "HandleId": "0",
[...]
            "spot": {
              "HandleId": "1",
[...]
        {
          "HandleId": "2",    <---- This should be "1"
```

**Expected behavior**
It should increment the HandleId by one for the base level, and nodeData->NodeIndex == nodes->HandleId.

**Version (please complete the following information):**
 - 8.12.2 stable

**Screenshots**

**Comment by anon56003269** [comment]
If this is just an issue with my understanding of HandleId, then please close.

**Comment by seberoth** [comment]
HandleId/HandleRefId represents class references in cr2w files. Has nothing to do with how streamingsectors works
