### ISSUE TITLE
ExportTool: when .ent export fails, suggest using the script

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1600]
**Describe the bug**
The export tool doesn't work reliably for .ent files. The error popup should suggest using the export wscript instead:
<img width="491" alt="image" src="https://github.com/WolvenKit/WolvenKit/assets/965785/928ccf5f-010c-49cc-91c9-61c729a8dae9">

**Comment by rfuzzo** [comment]
the ent exporter in the export tool was very much always against my design-ideas, I can't think of good reasons that it should stay, but that obviously doesn't mean there aren't any good reasons for it - it's just they may not be known to us (or anyone even!).

**Comment by seberoth** [comment]
Hmm, I disabled that already with e67b123. How did you manage to get it in the exporter?
![grafik](https://github.com/WolvenKit/WolvenKit/assets/456881/42844423-0f80-4a1c-9221-c669a07bd9d3)

**Comment by manavortex** [comment]
User error, I think. [Wasn't me](https://discord.com/channels/717692382849663036/1033120509216444550/1217808083879985234)

**Comment by Simarilius-uk** [comment]
I'm not sure how they were doing it, I tried via the button in preview to test.

**Comment by manavortex** [comment]
fixed by .ent files no longer showing up in the exporter
