### ISSUE TITLE
Allowing resources in the project to be installed even when the game is running

### ISSUE THREAD

**Issue by Berdagon** [WolvenKit/WolvenKit#1638]
currently you can have resources in the project that get placed in the game directory when installed and there is also RHT that allows reloading archives while the game is running but when i try to install the project so the changes that i made to the tweaks or script files in the resources folder are transferred to the project folder it doesnt happen because install mod aborts after trying to install the archive which is being used by the game and RHT also only places the archive in the archive folder and leave the rest as is

**Describe the solution you'd like**
either installing just skip over the archive when it fails and put the resources in the game directory anyway
or add the tweak and script reload futures of the rht to the wkit

**Comment by DoctorPresto** [comment]
Red hot tools has a vscode plugin which allows you to hot reload scripts and tweaks directly from the text editor, seems to make more sense to use that than to add in the extra steps in wkit.

**Comment by Berdagon** [comment]
doesnt that only work when the file is in the gmae directory? or does it also move the file over?

**Comment by manavortex** [comment]
I changed HotReload to also include non-archive files. If you need anything else, feel free to open another issue with what exactly you need :)
