### ISSUE TITLE
Can't delete selection in ".json" file (axl clothes project) - WolvenKit Nightly 8.13.0-nightly.2024-04-18

### ISSUE THREAD

**Issue by NolaDreamer** [WolvenKit/WolvenKit#1649]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version (please complete the following information):**

**Screenshots**

**Comment by NolaDreamer** [comment]
Also cant delete more than 1 component when click "Delete selection"

**Comment by manavortex** [comment]
Should be fixed by now? Please confirm

**Comment by NolaDreamer** [comment]
> Should be fixed by now? Please confirm

The problem is fixed, I confirm
