### ISSUE TITLE
Materials are not exported correctly for meshes using ArchiveXL Dynamic Materials

### ISSUE THREAD

**Issue by philipl** [WolvenKit/WolvenKit#1697]
**Describe the bug**
The new Dynamic Materials feature in ArchiveXL means that material entries cannot be exported as-is. Today, if you try and export such a mesh, it will export as-is, resulting in one material called `@dynamic` with the `debug_to_replace.mi` placeholder for the templateised path.

**To Reproduce**
1. Export any mesh using dynamic materials
2. Look a the resulting `Material.json`
3. See that it doesn't contain all the expanded materials

**Expected behavior**
The dynamic materials should be expanded as part of the export, so that all are fully populated in the `Material.json`

**Version (please complete the following information):**
 - Version 1.14.0

**Comment by manavortex** [comment]
Should be fixed in today's Nightly (in a few hours)
