### ISSUE TITLE
Feature: Remember nodes state in the Project Explorer across restarts

### ISSUE THREAD

**Issue by hgyi56** [WolvenKit/WolvenKit#1721]
It is sometimes annoying to open a project into WolvenKit and see that all the nodes (folders) of the Project Explorer are expanded. As I create a mod I may add a lot of folders and files and I want some folders to be expanded or collapsed depending on the situation.

Anytime I reopen WolvenKit I must set my folders state again. It would be nice if there was a feature to remember folders state in the Project Explorer.

**Comment by seberoth** [comment]
Fixed with #1744
