### ISSUE TITLE
Improve the LocKey browser

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1724]
The LocKey browser needs some love: 

- Translation entries without a secondary key won't be displayed (in `onscreens.json` are plenty of those)
- searching by key is hidden in the context menu

The LocKey browser should allow (and show a clear UI) for
- searching by translation text
- searching by secondary key
- searching by primary key

Optionally, we could allow wildcard and/or range search 

See also https://github.com/WolvenKit/WolvenKit/issues/1148

**Comment by manavortex** [comment]
Good to know, thanks! I didn't find that yesterday :)

**Comment by rfuzzo** [comment]
But yeah maybe it should be more intuitive, with an option next to the big search field instead of the filters

**Comment by manavortex** [comment]
yeah, maybe a checkbox/dropdown :)
