### ISSUE TITLE
missing embedded files

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/WolvenKit#1742]
**Describe the bug**
the inplace resources list of exterior_-62_-102_1_0.streamingsector show 4 cfoliage files that are all listed as embedded, but the tabs at the top only have 3? json export has 4.
wscript doesnt seem to want to export any of the cfoliage, bit stumped about whats going on

**To Reproduce**
add exterior_-62_-102_1_0.streamingsector to a project, look at hte inplace resources, json it, look at hte embedded files bit of the json.

**Expected behavior**
All 4 cfoliage should be in the top bar

**Version (please complete the following information):**
latest nightly

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/29640139/bbd0cb00-7344-4540-958b-a79eb848a5fa)

![image](https://github.com/WolvenKit/WolvenKit/assets/29640139/c6502d13-dd2d-418d-b71c-2558fb07d9f1)

**Comment by seberoth** [comment]
Tested with latest nightly & stable.
Both show 4 embedded foliages for me. Also wscript looks fine for me.

**Comment by Simarilius-uk** [comment]
its showing me the 4 when I opened it in a new project today, no idea what was up with it last night.
Still cant get the wscript to export the cfoliage files from the sector though

**Comment by seberoth** [comment]
WScript works fine for me.
Just edited the sector export script to include `.cfoliage` for json export and it gets extracted
