### ISSUE TITLE
Files disappear from the Project Explorer when being saved

### ISSUE THREAD

**Issue by hgyi56** [WolvenKit/WolvenKit#1767]
If I modify any file and save it, then it disappears from the Project Explorer and I must refresh it to make it show again.

Also if I create a file or duplicate one in the windows file explorer, then the ordering of files in the Project Explorer won't be updated so I need to refresh it manually.

**Comment by seberoth** [comment]
> If I modify any file and save it, then it disappears from the Project Explorer and I must refresh it to make it show again.

Will be fixed soon.

> Also if I create a file or duplicate one in the windows file explorer, then the ordering of files in the Project Explorer won't be updated so I need to refresh it manually.

Not sure what you mean with this. Duplicated files in the explorer and WKit shows them ordered

**Comment by hgyi56** [comment]
> Not sure what you mean with this. Duplicated files in the explorer and WKit shows them ordered

When I duplicate a file in the Windows file explorer and change its name for example duplicate `steel_bare.mltemplate` to `copper_bare.mltemplate` from the Windows file explorer.

Then I go back into WKit and that files are not correctly ordered in the Project Explorer until I refresh it.

**Comment by manavortex** [comment]
Pretty sure this is fixed - I remember touching this, and also tried reproducing and it didn't happen :)
