### ISSUE TITLE
Rig Selection in Export/Import Tool for Mesh w/Rig / Multi-Mesh bug

### ISSUE THREAD

**Issue by kmirea** [WolvenKit/WolvenKit#1775]
**Describe the bug**
Rig Selector Button (ellipsis) on Import & Export Tool for Mesh w/Rig / Multi-Mesh options failing to bring up the rig list, causes exception in log output instead.

**To Reproduce**
1. Add Mesh and associated rig to project
2. Tools -> Export Tool, or Import Tool
3. Choose Default Importer/Exporter
4. Select Mesh from project
5. Select Export Type "Mesh with Rig" or "Multi-Mesh"
6. Click-on Select Rig(s) or Select Rig 
7. See error in log (exception error message: searchScope)

**Expected behavior**
List of rigs shows up in popup panel

**Version (please complete the following information):**
 - 8.14 nightly 2024-06-08 and previous,  8.13 works as expected

**Screenshots**
see attached

![Screenshot 2024-06-08 220650](https://github.com/WolvenKit/WolvenKit/assets/11072763/905fb90e-7a03-4395-b94e-6c9733f15c7c)

**Comment by seberoth** [comment]
Fixed with 30062e7
