### ISSUE TITLE
CLI version exports garbled subtitles

### ISSUE THREAD

**Issue by steamch** [WolvenKit/WolvenKit#1779]
**Describe the bug**
when i use CLI Command to unbundle archives file,the subtitles has been change into garbled

**To Reproduce**
1.use the cli export lang_zh-cn_text.archive file
2. Go to 'lang_zh-cn_text\base\localization\zh-cn\subtitles\open_world\scenes'
3. Click on 'aaron_mccarlson_default.json'

**Expected behavior**

> .\WolvenKit.Cli.exe unbundle -p "L:\GOG-GAMES\2077extra\Depot\lang_zh-cn_text.archive" -o "L:\GOG-GAMES\2077extra\Depot\lang_zh-cn_text"
[ 0: Information ] - L:\GOG-GAMES\2077extra\Depot\lang_zh-cn_text.archive: Found 3076/3076 entries to extract.
100%
[ 0: Success     ] - L:\GOG-GAMES\2077extra\Depot\lang_zh-cn_text.archive: Unbundled 3076/3076 entries.

**Version (please complete the following information):**
 - windows 11, [WolvenKit.Console-8.14.0](https://github.com/WolvenKit/WolvenKit/releases/download/8.14.0/WolvenKit.Console-8.14.0.zip)

**Screenshots**
<img width="1240" alt="20240606225439" src="https://github.com/WolvenKit/WolvenKit/assets/22424279/099cca02-4964-4c19-96c3-debd61b242fa">
it is use CLI version.but when i use the webui version,i click the convert to JSON.the subtitle can be recognized
![20240610002252](https://github.com/WolvenKit/WolvenKit/assets/22424279/ee94fe27-ec03-492e-939f-5eb637d849d4)

**Comment by dragonzkiller** [comment]
Closing as it's a non-issue
