### ISSUE TITLE
Embedded mlmask when export materials will have weird name(hash?)

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1794]
**Describe the bug**
When exporting a mesh with an embedded mlmask with the setting "Export Materials", it will output "t2_001_wa_shirt_straps__songbird.mesh_embedded" folder, but under that will be another folder with a bunch of numbers(likely path hash?) and the layers inside will have the same numbers as well. 

**To Reproduce**
1. Add "ep1\characters\main_npc\songbird\t2_001_wa_shirt_straps__songbird.mesh" to project
2. Export with "Export Materials" setting
3. See the names of the exported mlmask folders/files

**Expected behavior**
It should be the correct name of the mlmask for convenience.

**Version (please complete the following information):**
 - Tested on nightly 06-12

**Screenshots**
![image](https://github.com/WolvenKit/WolvenKit/assets/20621809/30b7fdb1-6c31-445b-a8a5-ddc59fe18978)

**Comment by seberoth** [comment]
This is not a bug. This is intended
