### ISSUE TITLE
Darken text of layers in mlsetup is not intuitive

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#1804]
**Is your feature request related to a problem? Please describe.**
The darken text of layers that are not Opacity 0 in mlsetup is not intuitive. It leads me to believe that the layer is inactive when it is, just not full Opacity. 
![圖片](https://github.com/WolvenKit/WolvenKit/assets/20621809/e8900ea8-4255-4e88-bfe7-859a25c16f6f)

**Describe the solution you'd like**
I think only the layers that have Opacity 0 should be darkened, to indicate that they are inactive and not used.

**Comment by AAbdii** [comment]
YES agreed, I got v confused too. Currently it greys at <1, it should ideally only grey at 0

**Comment by manavortex** [comment]
Turns out, when you compare something as an integer, it will be 0 as soon as it's < 0.5, who'd have thought.
