### ISSUE TITLE
Wkit not responding after Widget Preview

### ISSUE THREAD

**Issue by DoraVirtuoso** [WolvenKit/WolvenKit#1836]
**Bug description**
After doing a Widget Preview and coming back, when I click on anything in the widget, WolvenKit freezes and does not respond, sometimes it responds after a while, but even if it does, when I click on anything it becomes again unresponsive, sometimes it does not recover at all and remains frozen, this only happens after doing a Widget Preview
and Also, in some widget files (especially complex ones), WolvenKit may freeze when the Widget Preview is pressed, but it does not fall into the unresponsive phase and does not recover no matter how long it waits.

**To Reproduce**
1. Open any inkwidget file (especially those for complex menus settings.inkwidget etc.)
2. Click on Widget Preview
3. Back to inkWidgetLibraryResource
4. Click anything (propertyManager, children etc.)
5. and You see WolvenKit  not responding

**Expected behavior**
 - WolvenKit not responding or freezing

**Version**
 - WolvenKit 8.14.1-nightly.2024-07-07

**Comment by manavortex** [comment]
> Also, in some widget files (especially complex ones), WolvenKit may freeze when the Widget Preview is pressed, but it does not fall into the unresponsive phase and does not recover no matter how long it waits.

I'd need a widget where that always happens. Maybe Wolvenkit fails to load this, but without an example file, I can only guess. I loaded the two largest inkwidgets and couldn't reproduce your bug.
Give it another try with today's Nightly? It should ship in 1 or 2 hours

**Comment by manavortex** [comment]
Setting this to "fixed" for now
