### ISSUE TITLE
Unable to create items in Buffer for instanceData

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#1840]
**Describe the bug**
Unable to create array in buffer for 'instanceData' of 'nodes' in 'streamingsector'

**To Reproduce**
1. Create a '.streamingsector'
2. Click on 'nodes'
3. Navigate to 'instanceData'
4. Create item in 'buffer'

**Expected behavior**

**Version (please complete the following information):**
 - 8.14.1-nightly.2024-07-11

**Screenshots & Videos**

https://github.com/user-attachments/assets/d636df1a-d693-40fa-b57c-e1c65fd7ed90

**Comment by manavortex** [comment]
Buffers are write protected by default in easy editor mode. Switch it around here: 
![image](https://github.com/user-attachments/assets/7a3fb459-d6fd-4b71-b232-ad5aa3133a04)

**Comment by ArasakaApart** [comment]
This unfortunately, makes no difference.

https://github.com/user-attachments/assets/2b5816e2-fa2a-459b-99cb-38836cc08571

**Comment by manavortex** [comment]
Can you share the sector file? Easier than finding one :)

**Comment by ArasakaApart** [comment]
[apart_sq029_toygun.zip](https://github.com/user-attachments/files/16201712/apart_sq029_toygun.zip)
