### ISSUE TITLE
"Texture Preview" Compresses image into a 1 pixel horizontal image

### ISSUE THREAD

**Issue by itsgoco** [WolvenKit/WolvenKit#1853]
**Describe the bug**
When I open any file, going into the "Texture Preview" tab doesn't show a preview of the texture/image, rather, it shows just a long horizontal compressed 1 pixel line of the texture. Using an older version of WolvenKit's Nightly Release doesn't result in this bug.

**To Reproduce**
1. Go to any file that would have a Texture Preview tab
2. Click on the Texture Preview Tab

**Expected behavior**
No texture shown, only a compressed down image.

**Version (please complete the following information):**
 - WolvenKit 8.14.1 Nightly 7-17-2024. Nightly 7-14-2024 also doesn't work. Last version that shows the whole texture is 7-13-2024.

**Screenshots**

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/f20af6b3-d1d2-4a32-9ccb-186972ccbf26">
Top WKit is from a previous version that worked. Bottom WKit is from Nightly 7-17

<img width="1920" alt="image1" src="https://github.com/user-attachments/assets/c7ab6580-4fd9-488d-87fe-1c76df2d4b23">
<img src="https://github.com/user-attachments/assets/73ccc0f8-0fcd-4e77-b147-75a8dfda0759">

**Comment by manavortex** [comment]
Fixed that in yesterday's Nightly
