### ISSUE TITLE
nodeData indexes no longer display correctly

### ISSUE THREAD

**Issue by sosuinepsixuyu** [WolvenKit/WolvenKit#1869]
nodeData indexes in .streamingsector files are not displayed correctly with Nightly wkit:
![image](https://github.com/user-attachments/assets/9d54f0d6-ee8f-47df-b803-c2db5c1e0370)

To Reproduce:
- Open any streamingsector with latest Nightly build
- Unfold nodeData

The issue isn't there in release build (8.14.0):
![image](https://github.com/user-attachments/assets/252a8c49-da5c-467b-9c14-be7b6c163209)

**Comment by manavortex** [comment]
fixed in https://github.com/WolvenKit/WolvenKit/pull/1891
