### ISSUE TITLE
raRefs must have flags Soft

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1875]
![image](https://github.com/user-attachments/assets/713452ae-5565-455e-996d-99f8406e9050)
https://discord.com/channels/717692382849663036/1171003964200853594/1269214772147261550

It's only broken for raRefs inside components and has never worked.

psi has implemented a workaround in ArchiveXL, which makes this non-urgent, but it would be nice if Wolvenkit could enforce the correct flags for raRefs.

**Comment by manavortex** [comment]
Also, I was too optimistic and can't implement that (without touching the generated files). @rfuzzo, any ideas?

**Comment by seberoth** [comment]
Wouldn't it be enough to change the default value of flag?

Just change line 16 and 22 to `.Soft` 
https://github.com/WolvenKit/WolvenKit/blob/main/WolvenKit.RED4/Types/Primitives/CResourceAsyncReference.cs

**Comment by manavortex** [comment]
I thought that was verboten because the file was generated. If it's not, then I _can_ fix it :D

**Comment by seberoth** [comment]
No.

As Psiberx and me said before:
![grafik](https://github.com/user-attachments/assets/fa81c632-f739-4d09-95dc-1a715f2015d0)

**Comment by manavortex** [comment]
oh, I didn't see that. Awesome :)
