### ISSUE TITLE
Wolvenkit will only run in the background after startup

### ISSUE THREAD

**Issue by therazormail** [WolvenKit/WolvenKit#1903]
**Describe the bug**
It does the wolvenkit loading screen but once it is done, it just closes and only runs in the background after which I can see on task manager. I tried some really old versions of wolvenkit nightly, and I found that the 8.9.1 nightly 2023-09-16 works and will open, that's the most recent I found that works so far. any recent versions I try do not work and will not open correctly

**To Reproduce**
1. Go to the wolvenkit application
2. Click on it twice to open
3. let the startup screen open and load the application
4. It closes after it's done loading and Runnes in the background when I check task manager

**Expected behavior**
I expect the the wolvenkit menu to open after the startup loading screen is done like in some really old versions

**Version (please complete the following information):**
 - any lastest versions do this

**Screenshots**

**Comment by manavortex** [comment]
Does it work if you update Visual C Redistributable and .NET framework?

**Comment by therazormail** [comment]
> Does it work if you update Visual C Redistributable and .NET framework?

no, it does the same thing

**Comment by manavortex** [comment]
Hmm - I'm pretty sure this is because of some dependency missing? Alternatively, you can try to delete %APPDATA%/RedModding/Wolvenkit, maybe it has broken files :)

**Comment by therazormail** [comment]
> Hmm - I'm pretty sure this is because of some dependency missing? Alternatively, you can try to delete %APPDATA%/RedModding/Wolvenkit, maybe it has broken files :)

This worked! this is annoying because I did think to do this. I deleted the folder even, but restored it because I thought I would lose my projects, smh

**Comment by manavortex** [comment]
Awesome :) Glad that we found a solution.
