### ISSUE TITLE
Can't rename DynamicWidgetController in inkwidget

### ISSUE THREAD

**Issue by alphanin9** [WolvenKit/WolvenKit#1905]
When I attempt to rename a dynamic widget controller to a new class name, WolvenKit whines about the feature not being implemented.

**How to reproduce**
1. Create new inkwidget, shouldn't matter much what it has, maybe add some items to root widget
2. Add a dynamic widget controller gameController to the root widget, like this one here:  ![image](https://github.com/user-attachments/assets/de32c6ea-8520-4462-a1ed-5e5ba8c77a8f)
3. Right click on gameController, click "Rename class"

**Expected behavior**
I can change the widget controller's class name

**Version (please complete the following information):**
Commit 334699904921eb450064281faee34d9ba6306aa6 (latest), main branch

**Comment by alphanin9** [comment]
There are more problems with DynamicWidgetController.

I can't actually add new props, it whines about the feature being unimplemented too

**Comment by alphanin9** [comment]
Still not fixed, I can't rename a dynamic widget controller class or add new props. Same error whining about it not being implemented.

**Comment by djkovrik** [comment]
Btw if you need a temp workaround things seems to work as expected when you copy an existing inkwidget, clear everything inside libraryItems except Root and create a new handle there for game controller

**Comment by manavortex** [comment]
Check it with today's Nightly when it drops - I've implemented the fix that Unknown pointed out yesterday. If that doesn't fix it, I hope I can save enough braincells across the workday to take a look tonight :D

**Comment by alphanin9** [comment]
Almost forgot about this - it seems to be fixed.
