### ISSUE TITLE
Meredith stout base outfit not loading with materials in blender

### ISSUE THREAD

**Issue by Uncleteh** [WolvenKit/WolvenKit#1906]
**Describe the bug**
Whenever I try to import militech agent base outfit in blender using the latest wk nightly version and latest blender add-on with blender 4,1, 4.2 it never load with materials or nodes applied on the mesh

**To Reproduce**
1. Open the latest nightly wolvenkit version
2. Navigate to npc folder and selecting militech agent folder
3. Double click on t0_001_wa_body__militech_agent.mesh and than export it 
4. Open blender 4.1/4.2 with the latest add on installed
5. Importing t0_001_wa_body__militech_agent.glb 
6.The mesh loads without any materials applied to it just white mesh

**Expected behavior**
The mesh named t0_001_wa_body__militech_agent.glb to load with materials and nodes

**Version (please complete the following information):**
 - Latest nightly version of wk (WolvenKit-8.14.1-nightly.2024-08-21) and latest blender add on 

**Screenshots**
![6464646](https://github.com/user-attachments/assets/df2618fd-790f-4dbd-a5c3-4f0df7f19476)

**Comment by manavortex** [comment]
Closing this, since it's really more of a Blender Plugin issue :)
