### ISSUE TITLE
Warn user about capital letters in file path on project pack

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#1920]
When packing/installing the project, WKit should run a basic file validation (maybe as part of a launch profile?). 

It should print an error to console if the archive folder contains uppercase file names.

**Comment by alphanin9** [comment]
I get the feeling this should be a toggle - as it is now, it can get kind of annoying.

**Comment by manavortex** [comment]
Wolvenkit will secretly re-name everything to lower case internally, so no - this needs to be as annoying as possible :D 
Check [Moving and Renaming in Existing Projects](https://wiki.redmodding.org/cyberpunk-2077-modding/modding-guides/items-equipment/moving-and-renaming-in-existing-projects) on the most pain-free way to fix that, though :)
