### ISSUE TITLE
Select and run a WScript from Log dock

### ISSUE THREAD

**Issue by poirierlouis** [WolvenKit/WolvenKit#1932]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to run a WScript while coding it and looking at logs. I need to close the Script Manager, look at logs, fix my code, open the Script Manager again, `Update scripts` and run my script.

**Describe the solution you'd like**
Add a dropdown field in the Log dock to quickly pick a WScript to run.
It would be followed by a run button to refresh scripts and execute the selected WScript.

Ticket created after a small discussion on [Discord](https://discord.com/channels/717692382849663036/717720094196760760/1287790060447465483).

Suggestion with a mockup:
![2024-09-23_wolvenkit_mockup_wscript_shortcut](https://github.com/user-attachments/assets/113188f8-9910-499b-aa08-94c6e66cf230)

**Comment by seberoth** [comment]
Not saying that it isn't a good idea but...

> I'm always frustrated when I want to run a WScript while coding

![grafik](https://github.com/user-attachments/assets/7d481be0-8f1d-4024-8c7b-69fe7a3da9f7)

**Comment by seberoth** [comment]
Fair. External editing of wscript files were not considered at the time of writing.
Could also add a `Reload` button to the menu.
`Ctrl + R` should already work though

**Comment by poirierlouis** [comment]
Good to know. If Run button next to the dropdown can trigger a Reload before execution, that would be appreciated and straightforward imo.

**Comment by poirierlouis** [comment]
> Fair. External editing of wscript files were not considered at the time of writing. Could also add a `Reload` button to the menu. `Ctrl + R` should already work though

fyi, `CTRL + R` doesn't show the log like when using "Update scripts" button from Script Manager.

**Comment by seberoth** [comment]
Not sure what yoe mean?

`Ctrl + R` reloads the active tab/document. So if you are in the internal editor and press it, the file reloads.

**Comment by poirierlouis** [comment]
My bad, don't mind me.

**Comment by poirierlouis** [comment]
fyi, I'll start working on a PR for this.

**Comment by manavortex** [comment]
Awesome, feel free to self-assign

**Comment by poirierlouis** [comment]
@seberoth , regarding the customization of UI through WScript. I'm not convinced, even if right now it might be easier for me instead of diving in WKit codebase...
Mockup I made is imo the fastest way to code / try / code / try: one click to open dropdown, one click to pick a script, one click to refresh and execute a script. Which respect the "3 clicks rule". All nearby the log output... What do you think?

If it can be implemented with UI api only, that would be even better though.

**Comment by seberoth** [comment]
Sure, using the existing api wouldn't add a button near the log but I don't see how it would be "slower" to use. (Except the first time setup, but it would easily allow the script author to decide if it should be executeable via a menu entry or not).

It would be basicly a "1 click rule" if reloading would be added to the api.

code / click button / code / click button...

**Comment by poirierlouis** [comment]
So if I understand well:
- wscript use `ui` api to declare a menu item.
- wscript define button and callback to trigger reload + validate + run.

`reload` and `validate` can be implemented from script, but `run` cannot currently?

Yeah, it would mean this kind of "hot reload" feature could be defined only when working on the wscript, right?

**Comment by seberoth** [comment]
`Reload` and `Validate` are just example buttons shipped with WolvenKit.
The called function doesn't need to be in the same ui script.

Only thing missing currently is reloading of wscript files from script. Since wscript are chached that would be needed before execution.

Where you can place a button is hardcoded. So if you want a menu/button in the log window, we would need to add a `ScriptableMenu` there.

![grafik](https://github.com/user-attachments/assets/b788d894-2157-49e2-a928-6dc21255b01b)

**Comment by manavortex** [comment]
I think this would genuinely be the fastest way to implement that. Also, we could move the Script Manager into that menu? 

I'd be willing to wait for this as the last feature for the release. Thanks to Seb fixing the project browser bug, everything else should be more or less stable

**Comment by poirierlouis** [comment]
I must say that I lost track of what is expected or not...

> Also, we could move the Script Manager into that menu?

Into `Scripts` menu, which is generated by `ui` api in `ui_example.wscript`? Or the idea is to "natively" implement these "reload" / "validate" into a "Scripts" menu? And move the manager in it too?

**Comment by manavortex** [comment]
@poirierlouis, since you're the one implementing this, you get to decide how it's done (the benefits of open source development) :) We're just making suggestions to save work.

My idea was, anything script related could be chucked into the "scripts" menu, and then you could just run everything/open script manager from there. Not sure if that's what you had in mind, you do you!

Also, I think we're stable. I'll wait a few days before starting to think about a new release to collect new bug reports, but if none are forthcoming, should we wait for you?

**Comment by poirierlouis** [comment]
Alright, well I'm open to suggestions as you better know the codebase anyway.

I think it is a good idea to provide Scripts feature in one menu only. I guess I can "play" around and suggest something with a draft PR and start from there to tweak it with your feedback...

No don't wait on me, I'll need time to dive back in C#, get to learn ReactiveUI and patterns already in place. If it is alright to release these changes later.

**Comment by manavortex** [comment]
FAFO time :D
