### ISSUE TITLE
Feature Request: Add Optional Description to Scripts

### ISSUE THREAD

**Issue by notaspirit** [WolvenKit/WolvenKit#1936]
**Is your feature request related to a problem? Please describe.**

Not all scripts are a one step process where you just run the script and it's done, or there are caveats to how and when it should be used. But there is currently no good solution to providing additional information about the script to the user in a way that is intuitive and clear.

If you create a wiki entry for your script only the people who come across your script from the wiki will know about it
If you add the description into the code itself even less people will see it
If you send a discription or disclaimer via the console output it will clog up the console or might go unnoticed due to other output.

**Describe the solution you'd like**

Just like there is an author and version field there could be a description field that is displayed in the same location.

**Comment by seberoth** [comment]
Will add both `@description` (general description what a script does) and `@usage` ( usage instructions) then.
Not sure how the interaction with #1932 will be (as in where to show instruction when a script is called via an shortcut)

**Comment by poirierlouis** [comment]
> Will add both `@description` (general description what a script does) and `@usage` ( usage instructions) then.
Alright :)

> Not sure how the interaction with #1932 will be (as in where to show instruction when a script is called via an shortcut)
Could it be a "tooltip" when mouse hovers a dropdown item? Said tooltip would include all tags: version, author, description, usage.
