### ISSUE TITLE
Strange code fragments

### ISSUE THREAD

**Issue by rip-mm** [WolvenKit/WolvenKit#1947]
Hello! I checked WolvenKit with the PVS-Studio static analyzer. I was wondering If you could take a look at several suspicious fragments:

**Issue 1**
```
public AppImpl()
{
  ....
  // load oodle
  var settingsManager = Locator.Current.GetService<ISettingsManager>();
  if (   settingsManager.IsHealthy() 
      && !Oodle.Load(settingsManager?.GetRED4OodleDll()))
  {
    throw new FileNotFoundException($"{Core.Constants.Oodle} not found.");
  }
}
```
Developers used the `settingsManager` variable twice in the condition of the `if` statement. They initially used it without `null` checking, and then with the check via `?.`. 
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit/App.xaml.cs#L48).

**Issue 2**
```
public EFileReadErrorCodes ReadBuffer(RedBuffer buffer)
{
  ....
  data.Uk1 = _reader.ReadUInt32();
  data.Uk2 = _reader.ReadUInt32();
  data.Uk3 = _reader.ReadUInt32();
  var numBrck = _reader.ReadUInt32();
  var numSurf = _reader.ReadUInt32();
  var numProb = _reader.ReadUInt32();
  var numFact = _reader.ReadUInt32();
  var numTetr = _reader.ReadUInt32();
  data.Uk4 = _reader.ReadUInt32();
  data.Uk5 = _reader.ReadUInt32();
  data.Uk5 = _reader.ReadUInt32();      // <=

  data.Bounds.Min.X = _reader.ReadSingle();
  ....
}
```
The `data.Uk5` property is assigned a value twice. Developers might have copied a line, change the digit, but then forgotten about it in the last line. It's hardly a redundant line, since there's the `data.Uk6` property.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.RED4/Archive/IO/CGIDataReader.cs#L35).

**Issue 3**
```
public void Load()
{
  ....
  for (....; sectorIndex < pgc.BufferTableSectors.Count; ....)  // <=
  {
    if (   pgc.SectorEntries == null 
        || pgc.SectorEntries.Count <= sectorIndex 
        || pgc.SectorEntries[sectorIndex] == null)
    {
      throw new ArgumentNullException();
    }

    var sectorHash = pgc.SectorEntries[sectorIndex]!.SectorHash;
    if (!_entries.ContainsKey(sectorHash))
    {
      _entries[sectorHash] = new();
    }

    if (   pgc.BufferTableSectors == null                    // <=
        || pgc.BufferTableSectors.Count <= sectorIndex 
        || pgc.BufferTableSectors[sectorIndex] == null)
    {
      throw new ArgumentNullException();
    }
  }
}
```
The analyzer has detected that developers used the `pgc.BufferTableSectors` property before checking it for `null`.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.App/Services/GeometryCacheService.cs#L43).

**Issue 4**
```
private void LoadInfo()
{
  if (_projectManager.ActiveProject is null)
  {
    return;
  }

  var path = Path.Combine(Environment.CurrentDirectory,
                          "Resources",
                          "soundEvents.json");
  path = Path.Combine(_projectManager.ActiveProject.ResourcesDirectory,
                      "info.json");
    if (File.Exists(path))
    {
      ....
    }
}
```
It's probably not an error but a suspicious code fragment. The `path` variable is assigned a value twice. 
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.App/ViewModels/Dialogs/SoundModdingViewModel.cs#L82).

**Issue 5**
```
private bool InsertArrayItem(IRedArray ira, int index, IRedType item)
{
  var iraType = ira.GetType();
  if (iraType.IsGenericType)
  {
    var arrayType = iraType.GetGenericTypeDefinition();
    if (   arrayType == typeof(CArray<>) 
        || arrayType == typeof(CStatic<>) 
        && ira.Count < ira.MaxSize)
    {
      ....
    }
  }
}
```
There's another suspicious code fragment. It's tough to say for sure if it's a bug or not, but it's worth taking a peek at this code. The analyzer warns about a possible issue related to the operator precedence. As we all know, the `&&` operator takes precedence over `||`. It means that the `ira.Count < ira.MaxSize` expression is evaluated only with `arrayType == typeof(CStatic<>)`, not with the entire OR expression. If developers wanted it, it'd be a good idea to put the AND expression in parentheses for readability.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs#L3273).

**Issue 6**
```
private void AddCurrent(worldNodeData current)
{
  ....
  if (Parent?.Data is DataBuffer db && db.Buffer.Data is IRedType irt)
  {
    if (irt is IRedArray ira && ira.InnerType.IsAssignableTo(current.GetType()))
    {
      var indexx = Parent.GetIndexOf(this) + 1;
      if (indexx == -1 || indexx > ira.Count)      // <=
      {
        indexx = ira.Count;
      }
      ira.Insert(indexx, current);
    }
  }
}
```
The analyzer has detected that the `indexx == -1` expression is always false. The `indexx `variable gets its value from the `Parent.GetIndexOf(this) + 1` expression. Look at the `GetIndexOf` method.
```
public int GetIndexOf(ChunkViewModel child)
{
  if (child.NodeIdxInParent > -1)
  {
    return child.NodeIdxInParent;
  }
  
  for (var i = 0; i < Properties.Count; i++)
  {
    if (ReferenceEquals(Properties[i], child))
    {
      child.NodeIdxInParent = i;
      return i;
    }
  }
  return -1;
}
```
As we can see, the minimum return value from the method is -1. In the expression, developers added 1 to the return method value. So, the analyzer is right.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs#L4435).

**Issue 7**
```
public static Dictionary<string, string> GetPropertiesFor(....)
{
  ....
  foreach (var appearance in appearancesArr)
  {
    details[....] = appearance.AppearanceName.ToString()!;
    details[....] = appearance.IsPlayer == true ? "True" : "False";
    details[....] = ParseGameEntityReference(appearance?.PuppetRef);

    counter++;
  }
  ....
}
```
Here's a simple error: three lines use the `appearance` variable. In the last line, developers used appearance with the `?.` operator. So, the variable may be `null`.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs#L548).

**Issue 8**
```
public int UncookTask(FileSystemInfo[] paths, UncookTaskOptions options)
{
  ....
  if (options.outpath == null)       // <=
  {
    _loggerService.Error("Please fill in an output path.");
    return ERROR_BAD_ARGUMENTS;
  }

  if (   options.meshExportType != null
      && string.IsNullOrEmpty(options.meshExportMaterialRepo) 
      && options.outpath is null)     // <=
  {
    _loggerService.Error("When using --mesh-export-type, the --outpath" +
    " or the --mesh-export-material-repo must be specified.");
    return ERROR_INVALID_COMMAND_LINE;
  }
}
```
The analyzer warns that the large expression is always false. All the subexpressions are connected via `&&`, and the last one has already been in the previous `if` statement, followed by the method exit.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.Modkit/RED4/Tasks/UncookTask.cs#L47).

**Issue 9**
```
private static string TryGetGameInstallDir()
{
  if (   programName?.ToString() is string n 
      && installLocation?.ToString() is string l)
  {
    if (n.Contains(gameName) || n.Contains(gameName))  // <= 
    {
      exePath = Directory.GetFiles(l, exeName, SearchOption.AllDirectories)
                         .First();
    }
  }
}
```
The analyzer has detected the subexpressions that are identical to the ones on either side of the `||` operator.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.Core/Compression/Oodle.cs#L488).
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.Core/Compression/Oodle.cs#L507).

**Issue 10**
```
public void Extract(Stream output, bool decompressBuffers)
{
  if (Archive is not { } ar)
  {
    throw new InvalidParsingException(
      $"{Archive.ArchiveAbsolutePath} is not a cyberpunk77 archive.");
  }

  ar.CopyFileToStream(output, NameHash64, decompressBuffers);
}
```
Essentially, `Archive is not { }` is the same as `Archive is not object` or `Archive is null`. If the check is true, developers get a `NullReferenceExceprion` when an error exception is thrown. 
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.RED4/Archive/Base/FileEntry.cs#L87).

**Issue 11**
```
public ButtonCursorStateView()
{
  HoverStateName = "Hover";
  PressStateName = "Hover";
  DefaultStateName = "Default";

  PostConstruct();
}
```
It seems that the analyzer has detected the failed copy-paste, and developers should assign "Press" to `PressStateName`.
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.RED4/Types/Classes/ButtonCursorStateView.cs#L34).

**Issue 12**
```
public static int GetCompressedBufferSizeNeeded(int count)
{
  var n = (((count + 0x3ffff + ((uint)((count + 0x3ffff) >> 0x3f) & 0x3ffff))
    >> 0x12) * 0x112) + count;
  //var n  = OodleNative.GetCompressedBufferSizeNeeded((long)count);
  return (int)n;
}
```
And here's the last suspicious fragment. Developer wanted to shift to `0x3f`, which is equal to 63. However, it exceeds the size of the expression type to which the shift operation is applied. This expression is of the `Int32` type, which contains 32 bits. Since shifts are circular in C#, the shift of 63 is equal to that of 31. 
[Link to the code](https://github.com/WolvenKit/WolvenKit/blob/fa1e494c578451721eaa477df0bc8577dfd80116/WolvenKit.Core/Compression/Oodle.cs#L397).

**Comment by manavortex** [comment]
Define "suspicious"? You can read the entire code and see what it does

**Comment by Zhincore** [comment]
Seems to me like you found some so-called "code smells", I would suggest you make a PR(s) instead of explaining each issue from PVS.

**Comment by Simarilius-uk** [comment]
Seems to be their thing, analyse random code bases, make a post like this, look like their connected to the analyser as half their git commits point to blogs on the website rather than actual bugposts.

**Comment by manavortex** [comment]
Linkfarm/botfarm? Should we delete this?

**Comment by Simarilius-uk** [comment]
think its a genuine analysis, just weirdly worded text round it (Their in Kazakstan, so its probably just a nuance of translation)

**Comment by manavortex** [comment]
Oh

**Comment by seberoth** [comment]
Yeah, 2 is wrong.
11 is probably a c&p too, but since its autogenerated its CDPRs fault. Not gonna change that.
12 isn't used anymore if I remember right.

The rest, idc :P

**Comment by manavortex** [comment]
Do you wanna fix, or should I?

**Comment by seberoth** [comment]
¯\_(ツ)_/¯

**Comment by Simarilius-uk** [comment]
> Do you wanna fix, or should I?

Get cassian to do it if hes so keen to close it

**Comment by manavortex** [comment]
He writes in, like, Erlang
