### ISSUE TITLE
New error when opening a "mesh preview"

### ISSUE THREAD

**Issue by busyvampire** [WolvenKit/WolvenKit#1959]
**Describe the bug**
I've edited a mesh, added textures and even tested it in game. When i got back to Wolven Kit and opened my mesh i got this error (picture 1). And when i open "mesh preview" i get another (picture 2 and 3). Even though i can import and export the mesh, i can't see it on the preview and this error confuses me. Any other mesh (game mesh or mine) are working fine in the same project.

**To Reproduce**
1. Double click on mesh.
2. See first error (picture 1)
3. Open mesh preview and click on the mesh preview error.
4. See error (picture 2 and 3)

**Expected behavior**
To be able to generate materials and see my mesh.

**Version:**
 - Version 8.14.1.nightly.2024-10-12

**Screenshots**
![Знімок екрана 2024-10-13 113322](https://github.com/user-attachments/assets/e5349f86-3929-4166-93d1-091b3e8243e1)
![Знімок екрана 2024-10-13 035648](https://github.com/user-attachments/assets/b4fd349b-d0e6-441d-95c5-9d8106b9f90d)
![Знімок екрана 2024-10-13 113519](https://github.com/user-attachments/assets/5b94aa98-7ca7-4f3e-bdff-4b815e30eb94)
Also my mesh that causes this error.
[mesh.zip](https://github.com/user-attachments/files/17354935/mesh.zip)
Xbm's that are required by this mesh:
[xbm black colors.zip](https://github.com/user-attachments/files/17355100/xbm.black.colors.zip)
[xbm white stripes.zip](https://github.com/user-attachments/files/17355101/xbm.white.stripes.zip)
[normal.zip](https://github.com/user-attachments/files/17355103/normal.zip)

**Comment by seberoth** [comment]
Pic1: Can't reproduce. Opens without error for me
Pic2&3: Would say one of your xbms is faulty. Can't really tell what is wrong without the whole project

**Comment by manavortex** [comment]
Same here - and what Seb said :) Can you zip up the whole folder, please (including the xbm files)? Then I can generate a better error message

**Comment by busyvampire** [comment]
I uploaded all the .xbm files that needed. When i was packing them i noticed that my "normal" texture just dissapeared... Probably it was the broken one, but i added the new one manually.

**Comment by seberoth** [comment]
> Probably it was the broken one, but i added the new one manually.

I mean, you could test it on your end then. If its still throwing errors or not.
Also still no problems for me with your files.
If it still happens, upload your whole project

**Comment by busyvampire** [comment]
I tested, i still have the same error (pictures 2 and 3)

**Comment by manavortex** [comment]
I have the project, I'll take a look now. Got sidetracked with something else, of course.

**Comment by manavortex** [comment]
I have it, and I fixed it in https://github.com/WolvenKit/WolvenKit/commit/98ddbd447e3e06fc39615b1ef58c4639b2efbecb
