### ISSUE TITLE
Mesh does not export using default settings after multimesh export failure

### ISSUE THREAD

**Issue by derekduoba** [WolvenKit/WolvenKit#1961]
**Describe the bug**
If a multimesh export fails with a "need at least 1 extra mesh..." error, it becomes impossible to export the selected mesh on subsequent attempts, even if using "default" export settings. Note that when the export fails to produce an exported file using default settings, the log indicates that the export succeeded.

The workaround is to close and reopen wkit, after which it becomes possible to export using default settings again.

**To Reproduce**
1. Ensure that you have an open project that contains exportable mesh files.
2. Open the wkit Export tool (Tools -> Export tool).
3. Select a single mesh for exporting.
4. Under "Export Type" select "MultiMesh."
5. Click "Export Selected." Note that the export fails with a "need at least 1 extra mesh..." error.
6. With the same mesh selected, change "Export Type" to "Default."
7. Click "Export Selected." Note that the log indicates that the export succeeded. Note that no mesh file was exported.

**Expected behavior**
The Export tool should successfully export a supported mesh using "Default" settings after an export fails due to incorrect settings.

**Version (please complete the following information):**
 - Wkit Version 8.15.0

**Comment by kmirea** [comment]
I don't believe u are able to export only one mesh with multimesh exporter.. personally i only use this in sitation where there are 2+ meshes or more than one rig (ie in case of characters - deform + base + anim)

Do u have more than one rig / cant use the regular single mesh w/rig or materials exporter ? a hacky workaround maybe - could try adding some random prop (ideally without any rigging/bones) to ur project and select that as the 2nd mesh, deleting it inside of blender after the fact
