### ISSUE TITLE
Ability to extract multiple .XBM  files with the same name

### ISSUE THREAD

**Issue by pyro5857** [WolvenKit/WolvenKit#1966]
https://github.com/user-attachments/assets/a53c5ebe-5fbe-44f5-a908-d2423f41504d

I have 100 mods each affecting the same head texture. WolvenKit displays all 100 folders correctly and I can see each file inside their separate folder

However when using the search function to onl show .xbm files, it only shows 1. Presumably because all of them have exactly the same name and folder structure

Attempting to export all 100 .archive files using the WolvenKitConsole exe - results in only 1 head texture file. As if it overrode 99 of them, leaving only the last one

Can you please add the ability to automatically rename files when duplicates are found? Random hexadecimal names, or appending .0001 at the end, anything like that

Or perhaps you can recommend an alternate way of dealing with this issue?

Thank you very much!

**Comment by manavortex** [comment]
For WKit, these are the same mod - you would have to deal with that yourself. I assume you're running things in a loop? I'd re-name the file directly after importing.

**Comment by pyro5857** [comment]
Hey @manavortex, thank you for replying!

I don't know what running things in a loop means, but I appreciate the advice. I actually tried exporting mod by mod, and then renaming the output folder one by one so that the files aren't overriden. But I can't do that for hundreds of mods x_x

Do you think there's way to bypass this issue entirely by using the cmd version of WKit? Perhaps there's a way to create a subfolder for each new .archive? So that my output folder has hundreds of subfolders by the end, each containing the files from each individual mod. Instead of just one tree where everything gets overriden by the next mod containing a file with the same name

This is the .bat file I'm currently using: 

@ECHO OFF
"path\WolvenKit.CLI.exe" uncook -p "path\mods" -o "path\output" -w *.xbm --uext png
PAUSE
EXIT

Is there anything I can change here to allow me to keep all the extracted files? Either by renaming duplicates, or putting them in their own separate subfolders?

I spent days trying to figure this out, but I'm no programmer ._. 

Thanks so much, mana!

**Comment by manavortex** [comment]
It should be something like (not tested, but I'm sure you can fix it if it doesn't work):

```
FOR %%F IN ("path\mods\*.archive") DO (
    SET "baseName=%%~nF"
    "path\WolvenKit.CLI.exe" uncook -p "%%F" -o "path\output" -w *.xbm --uext png
     REN "path\to\file.png" "!baseName!_%%~nG_file.png"
)    
```

**Comment by pyro5857** [comment]
Thanks @manavortex 

I changed all the paths (except for "path\to\file.png" because I had no idea what to write there or how to make it target potentially hundreds of pngs. And sadly that didn't work. I asked for advice from some other people, but they also didn't know anything about writing .bat files

Then I tried ChatGPT, and it made a lot of alterations. I tried different versions of what it gave me, but the .bat file always stops after extracting the first .archive. I think the renaming must be breaking the loop or something

Thank you for trying anyway. I don't know if you personally get anything out of this, but if you help me figure it out, I will pledge $50 on the WKit Patreon @_@ I just can't seem to find a way to extract multiple .archives at the same time containing the same file name

**Comment by manavortex** [comment]
Hey, 

"path\to\png" is the file that gets ecxtracted. For example, if the file in your .archive is `base\myfile.xbm`, extracting it would create `C:\path\output\base\myfile.png`
In the second step, you would rename `C:\path\output\base\myfile.png` to e.g. `C:\path\output\base\archive1_myfile.png`

**Comment by pyro5857** [comment]
Ah I understand now, thank you

Sadly it didn't work or I didn't do it right. The console just closes after extracting and renaming the first file. I'm giving up, but I will try again in a couple of years. Maybe duplicate handling will be implemented in the official GUI version because I'm not good at all this coding stuff x_x

Thank you very much for your help and your patience, I really appreciate it

**Comment by manavortex** [comment]
I'll write you a better batch script, it shouldn't fail because of this.

**Comment by pyro5857** [comment]
Really? :ooo thank you so much!

This is as far as I got:

https://github.com/user-attachments/assets/da131585-a137-4639-97f5-78659ffe47c4

As you can see, it goes through multiple .archive files that contain the same file name in them. And every new one simply overrides the old one :< I can't find a way to either rename the output to something unique, or maybe create a separate folder for each .archive file. Whichever is easier for you 🙏 I wouldn't mind if the files didn't retain their original names, that's totally fine with me

Thanks again mana!

**Comment by manavortex** [comment]
Can you give me your script? Easier than starting from scratch :)

**Comment by pyro5857** [comment]
Sure, this is what I use + your tip:

`FOR %%F IN ("D:\CP77 Extract\MODS\*.archive") DO (
    SET "baseName=%%~nF"
    "D:\CP77 Extract\WolvenKit.Console-8.15.0\WolvenKit.CLI.exe" uncook -p "%%F" -o "D:\CP77 Extract\zoutput" -w *.xbm --uext png
     REN "D:\CP77 Extract\zoutput\001_flower tattoo KSUV (black)(female)\base\4k\common\overlays\fullbody_overlay_d01.png" "!baseName!_%%~nG_file.png"
)    `

**Comment by manavortex** [comment]
This here works:

```
@echo off
setlocal

set "cli_path=C:\01_apps\Wolvenkit_CLI_8_15\Wolvenkit.CLI.exe"
set "modpath=F:\CyberpunkFiles\temp"

FOR %%F IN ("%modpath%\*.archive") DO (
    SET "baseName=%%~nF"
    "%cli_path%" uncook -p "%%F" -o "%modpath%\output"  REM -w *.xbm --uext png
    
    REM Move PNG files and preserve relative paths
    FOR /R "%modpath%\output" %%G IN (*.png) DO (
        SET "relPath=%%~pG"
        SETLOCAL enabledelayedexpansion
        SET "newDir=%modpath%\out\!baseName!\!relPath!"
        mkdir "!newDir!" >nul 2>&1
        move "%%G" "!newDir!"
        ENDLOCAL
    )
)

PAUSE
EXIT
```

**Comment by pyro5857** [comment]
Holy crap IT ACTUALLY WORKS, WOOOOOOOOOO. Everything gets extracted, moved to a different folder and onto the next file

Thank you so much manavortex! I'm off to tip a solid $50 on Patreon, well earned 👏 

Couldn't have done this without you. And to think I had all the files selected and ready to be deleted when you replied :D

**Comment by manavortex** [comment]
Would've been a shame! I also put this snippet on the Wolvenkit wiki, into the .CLI section, so that it can help the next person :)

**Comment by manavortex** [comment]
https://wiki.redmodding.org/wolvenkit/wolvenkit-cli/usage#processing-files-in-bulk
