### ISSUE TITLE
Add Ability to kill scripts

### ISSUE THREAD

**Issue by notaspirit** [WolvenKit/WolvenKit#1971]
**Is your feature request related to a problem? Please describe.**

When developing and debugging wscripts - especially if they normally take longer to complete - you will naturally encounter mistakes. 
If such a mistake in the script doesn't make the script outright crash the only way to end the script prematurely is to close out of wkit, which adds a lot of time waiting for it to restart even if it's for a minor thing.

**Describe the solution you'd like**

Next to the run button above the log there could be a kill script button that just terminates the current script whenever pressed.

**Comment by poirierlouis** [comment]
You mean the same "Stop" button present when editing a script with WKit editor?

**Comment by notaspirit** [comment]
Never noticed that as I never really used the inbuild script editor. Would still be nice to have it accessable outside of that.

**Comment by poirierlouis** [comment]
Yes, I realized that after seeing the Stop button in embedded editor. I'll add it.
