### ISSUE TITLE
Minor exception when trying to open ChangeComponentChunkMaskDialog

### ISSUE THREAD

**Issue by poirierlouis** [WolvenKit/WolvenKit#1980]
**Describe the bug**
Minor exception showing in logs, see description.

**To Reproduce**
- GIVEN
  - any .app open in tab
- WHEN
  - click on Appearances
  - select "Change chunk view by component"
- THEN
  - exception is thrown in [RedChunkMaskEditor.xaml.cs](https://github.com/WolvenKit/WolvenKit/blob/2890a91e15f54300d686049e079c74a83c5bba40/WolvenKit/Views/Templates/RedChunkMaskEditor.xaml.cs#L110)

**Expected behavior**
- silently ignore the action (if action is not expected/allowed)
OR
- show a warning dialog to explain why action cannot be done in current state

**Version (please complete the following information):**
 - Version 8.15.1

**Comment by seberoth** [comment]
Yeah, it throws an exception, because `RedNumber` is null. And should be fixed.

But the error gets suppressed for me. Not showing up in the log

**Comment by poirierlouis** [comment]
> But the error gets suppressed for me. Not showing up in the log

Maybe because you are running it in Release mode?

**Comment by seberoth** [comment]
Tried both latest nightly release as well as current dev build from main.

**Comment by poirierlouis** [comment]
Hum right, maybe I got mixed up with other minor issues I reported recently. Anyway, exception should be avoided by checking when `RedNumber` is null then.
