### ISSUE TITLE
Minor exception when expanding/collapsing children in Project Explorer view

### ISSUE THREAD

**Issue by poirierlouis** [WolvenKit/WolvenKit#1982]
**Describe the bug**
In Project Explorer, trying to expand / collapse children when no item in the tree is selected will throw an exception (in logs).

**To Reproduce**
- GIVEN
  - any project open with some folders / files
  - no folder/file is selected in tree view
- WHEN
  - click on `Expand Children` or `Collapse Children` button
- THEN
  - exception is thrown in [ProjectExplorerView.xaml.cs](https://github.com/WolvenKit/WolvenKit/blob/2890a91e15f54300d686049e079c74a83c5bba40/WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs#L281)

**Expected behavior**
- silently ignore the action

**Version (please complete the following information):**
 - Version 8.15.1

**Comment by seberoth** [comment]
Works fine for me o.O

Collapse/Expand does what it should do, no exception thrown.
