### ISSUE TITLE
Linux Compat

### ISSUE THREAD

**Issue by Rykita** [WolvenKit/WolvenKit#1989]
**Is your feature request related to a problem? Please describe.**
The app runs quite poorly on Linux, tested under Proton Experimental, soda 9.1, wine stable, GE-Proton, none yield results that make the software usable. This doesn't just mean the performance is bad, it's impossible to open any view and use any of the tools, only the basic homepage/dashboard GUI works.

**Describe the solution you'd like**
A proper native Linux port, this isn't wishful thinking, if I can contribute I will, but with 16.6k files, I'd like to first create an issue to ensure I get the most information about what needs to be done or what stands in the way or what help is needed to make this plausible/achievable. I assume the current state of things is related to reliance on WPF.

**Comment by Rykita** [comment]
A good way to know where I should start is to hear from the devs themselves and what the community thinks, if there is a comprehensive list of the "main" stinkers that cause Linux builds to be impossible, I'd love to hear all of them

**Comment by Rykita** [comment]
I was notified WolvenKit 8.13 (and most likely previous ones) work just fine under Proton and confirmed it, the question is what causes >8.14+ to break?

**Comment by seberoth** [comment]
Found the issue causing newer versions to fail.
Will not solve all problems, but at least this.
