### ISSUE TITLE
Empty dropdown in scneventsSocket

### ISSUE THREAD

**Issue by Sun1ive** [WolvenKit/WolvenKit#1996]
**Describe the bug**

**To Reproduce**
1. Create a scene file.
2. Create a section node.
3. In the events array create a `scneventsSocket`
4. See the empty dropdown

**Expected behavior**
The dropdown should not be empty?

**Version (please complete the following information):**
Latest nightly

**Screenshots**
![image](https://github.com/user-attachments/assets/e3968bbd-4ba3-4f24-87d6-5402fb2bfbad)

**Comment by seberoth** [comment]
Since the used enum has now values, it is correct that the dropdown is empty.
Why it has no values? No idea.
