### ISSUE TITLE
Unable to open phases in PL quests

### ISSUE THREAD

**Issue by Sun1ive** [WolvenKit/WolvenKit#1998]
**Describe the bug**
Unable to open some phases and its related `.questphases` from native PL quests

**To Reproduce**
1. In assets manager find  `ep1\quest\main_quests\q304\phases\q304_05_stadium_infiltration.questphase`
2. Open graph
3. Click on Phase 2 / Phase 4

**Expected behavior**
Should be opened phase/questphase

**Version (please complete the following information):**
 - Version latest nightly

**Screenshots**
![image](https://github.com/user-attachments/assets/37a72f5a-a7f8-4096-adf7-f205da4f3779)
![image](https://github.com/user-attachments/assets/6c2b9295-f738-4951-9c16-35e344f224a5)

**Comment by poirierlouis** [comment]
Thanks for reporting.

@dustinlacewell did you come across this issue, maybe fixed it while working on #1977 ?

**Comment by seberoth** [comment]
The problem is, that the defined files doesn't exists.
Should have a better error message soon.
