### ISSUE TITLE
Cannot show widgets without snap grid

### ISSUE THREAD

**Issue by poirierlouis** [WolvenKit/WolvenKit#1999]
**Describe the bug**
When viewing an `.inkwidget`, button `Toggle Grid` will not show/hide the grid to snap, it will show/hide the entire canvas showing widgets.

**To Reproduce**
1. Open any `.inkwidget`
2. Click on 'Widget Preview'
3. Look at canvas preview
4. Click on 'Toggle Grid'

**Expected behavior**
Only the snap grid visibility should be turned on/off when clicking on the button `Toggle Grid`. Preview of widgets should always be visible.

**Version (please complete the following information):**
 - Version 8.15.1

**Additional notes:**
@manavortex , I think the culprit is from #1968 in [RDTWidgetView#L78](https://github.com/WolvenKit/WolvenKit/blob/4125ce6b71ed96e79491f5cba2bc17e0861f9c1f/WolvenKit/Views/Documents/RDTWidgetView.xaml#L78).

**Comment by MadradMagerman** [comment]
+1 confirm with this bug

P.S. Thank you for reminding me to report this bug, even though I was the requester...
+ Sorry @manavortex that I forgot to say this
