### ISSUE TITLE
REDmod Deployment

### ISSUE THREAD

**Issue by ArasakaApart** [WolvenKit/WolvenKit#2026]
**Describe the bug**
Experiencing some issues for my REDmod restricted mod. 

- Deploying the mod no longer generates an "info.json" file.
- Tweak and Scripts files are not being installed to `Cyberpunk 2077\mods\<mod>` folder.
- An empty project folder is created under **Resources** with the path `r6\scripts`, which is redundant.

**Expected behavior**

- An info json containing the mod name (as set in project file) is generated and deployed in the mod folder
- Tweak and script files are deployed in that same folder
- No empty folder with the path `r6\scripts` is generated upon deployment

**Version (please complete the following information):**
 - Version 8.15.1-nightly.2024-11-18

**Comment by seberoth** [comment]
Are you sure it worked before?
Can't find any function which actually moves the files to the game dir xD
Could be that I'm blind though

**Comment by manavortex** [comment]
I know that they were zipped up correctly at least, because I tested and fixed that :D

**Comment by seberoth** [comment]
@manavortex You did disable installation for RedMods here. Any reasoy why?
https://github.com/WolvenKit/WolvenKit/commit/545db98d4ead5433b0451e052ad3cbf37f7ec0ea#diff-ab086f9c8fb500da6e528e1e23ba451372da04f3f452d2a4bf3bc77beb4e62f5R429

**Comment by manavortex** [comment]
Install as redmod has its own button that is by default hidden

**Comment by seberoth** [comment]
You mean the launch profile? Yes, thats what I'm talking about.
Your change above prevents the copying of redmod files to the game dir if "Instal as: RedMod" (DeployWithRedmod) is selected.

**Comment by ArasakaApart** [comment]
Yeah I did come across the option for Deploy as REDmod needed to be re-enabled in the Settings, which I did, but seems the issue lies deeper then :D

**Comment by manavortex** [comment]
Oh... then I probably fucked that up. Will double-check
