### ISSUE TITLE
Regression (Mesh export): .glb can't be imported into Blender

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#2035]
This is a regression! An export of the mesh with 8.15 (stable) can be imported into Blender just fine!

**Describe the bug**
When exporting a .mesh to .glb with the current Nightly (Nov 22), 
- the resulting file has the extension `mesh.glb` instead of `glb` 
- the resulting file can't be imported into Blender (I removed `.mesh` from the filename first)

**Blender exception**
```
Traceback (most recent call last):
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\i_scene_cp77_gltf\importers\__init__.py", line 232, in execute
    CP77GLBimport(self, props.with_materials, props.remap_depot, self.exclude_unused_mats, self.image_format, self.filepath, self.hide_armatures, self.import_garmentsupport, self.files, self.directory, self.appearances)
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\i_scene_cp77_gltf\importers\import_with_materials.py", line 189, in CP77GLBimport
    import_mats(current_file_base_path, DepotPath, exclude_unused_mats, existingMeshes, gltf_importer, image_format, mats, validmats)
  File "C:\Users\manav\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\i_scene_cp77_gltf\importers\import_with_materials.py", line 242, in import_mats
    if extras is None or ("materialNames" not in extras.keys() or extras["materialNames"] is None):
                                                 ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'
```

**Files**
[stable_8_15_export.zip](https://github.com/user-attachments/files/17868626/stable_8_15_export.zip)
[nightly_nov_22_export.zip](https://github.com/user-attachments/files/17868627/nightly_nov_22_export.zip)
[source.zip](https://github.com/user-attachments/files/17869059/source.zip)

**Comment by seberoth** [comment]
Since it is a export issue, it would be cool if you could add the mesh file, not the glb file

**Comment by seberoth** [comment]
Also for the `.mesh.glb`: Wasn't that wanted anyway? Keeping the internal extension available in the glb?
Thats why I didn't check for that

**Comment by manavortex** [comment]
It's wanted _except_ for mesh, since that's the default case. It's how it was originally implemented. The extension is only necessary to let us pick the import format.
I suppose we could also keep .mesh.glb, but then the material file needs to be renamed accordingly. Would have to check if the Blender addon can deal with that (it should).

I added source.zip to the original post :)

**Comment by Simarilius-uk** [comment]
wrt the blender addon working, it wont, theres places in entity and sector import where we're looking for a mesh to match a .mesh in the jsons that we strip .mesh and replace with .glb, easy enough to fix as we just dont strip the .mesh before adding glb, but it definitely will break as is.

**Comment by seberoth** [comment]
Will remove the mesh then again

**Comment by Simarilius-uk** [comment]
Thanks Seb, appreciate it.
