### ISSUE TITLE
Finishing release-0.6.2 cr2w tests

### ISSUE THREAD

**Issue by Maxzor** [WolvenKit/WolvenKit#205]
About the red reflection branch: things to do:
1) the classes are fully parsed, there’s nothing to be done on terms of rtti
2) what does need to be done is testing:
 - [x] A) test if all vanilla files are read (this can more or less easily be done with wkits unit test)
 - [x] B) test if all files are written (this can be done by modifying the unit test)
 - [ ] C) test if all files when edited in wkit are correctly written (here there isn’t a good automated unit test available sadly)

@elcorazonmc if you want to help with red reflection options A and B are stuff I could need help with
I ran most tests for A already, it seems all good (w2ent maybe needs more testing)
no B-type tests have been run afaik

**Comment by Maxzor** [comment]
2a (almost) done with #206

**Comment by Maxzor** [comment]
In my opinion #239 is a prerequisite to 2C

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by rfuzzo** [comment]
outdated, will need to be rehashed on Wolvenkit 8 tw3 support
