### ISSUE TITLE
Only able to copy an arry item once, will not copy another array item without restarting WKit

### ISSUE THREAD

**Issue by Lorkym** [WolvenKit/WolvenKit#2068]
**Describe the bug**
If you try and copy and paste individual array/Buffer item it will only let you copy the first item after Wkit starts up. Then the next item you attempt to copy and paste, it will paste the first item again.
It does not matter how many attempts you have a copying something different it will only paste the first item. Shutdown Wkit and it will copy the first item you select and paste but nothing else you try and paste.
**To Reproduce**
1. Open an .app file and copy an item in an appearance and paste it to another appearance, now go and copy a different item and paste it somewhere and the first item copied will be pasted. Only way to reset is to shut down Wkit and start it up again.

**Expected behavior**
you should be able to copy and paste different items.
**Version (please complete the following information):**

8.15.1-nightly.2024-12-07

**Screenshots**

**Comment by manavortex** [comment]
Pretty sure I fixed that already. Check today's Nightly when it drops :)
