### ISSUE TITLE
Scan Project for Broken File References not working

### ISSUE THREAD

**Issue by Lorkym** [WolvenKit/WolvenKit#2087]
**Describe the bug**
When you run the option from the project menu to scan for broken file references it no long displays any data in the pop up window. It does report how many files it has detected with broken references but not data in the window.

**To Reproduce**
select scan project for broken file records in the project file and empty pop window.

**Version (please complete the following information):**
8.15.1 nightly 2024-12-18

![Screenshot 2024-12-19 214134](https://github.com/user-attachments/assets/68583be7-9e6d-4292-918f-faa9199e9086)

**Comment by manavortex** [comment]
fixed in next Nightly :)
