### ISSUE TITLE
Support for user-created cr2w files

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#211]
cr2w tables left:
- [ ] buffers: referencing buffers in depot. no idea (medium priority)
- [ ] embedded files: user generated in-place embedded files. no idea (low priority)

_Originally posted by @rfuzzo in https://github.com/Traderain/Wolven-kit/issues/61#issuecomment-623355085_

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
