### ISSUE TITLE
epic: add new voicelines to the game

### ISSUE THREAD

**Issue by ghost** [WolvenKit/WolvenKit#23]
As a voice asset modder I want to add new voice lines to the game so I can use them in my scenes/mod.

- pair dialoglines and audio voicelines to add
- create lipsync animation
- pack as w3speech file to add in a dlc

**Comment by rmemr** [comment]
some background: 

voicelines and game strings from (w3speech files) are paired by the string id. to add voicelines for a specific dialog (scene) the scene must already exist and have all lines added as strings. the w3speech files provides the audio with those strings ids. lipsync animations are paired with the audio files in the w3speech files. audio files need to be encoded as a special ogg variant (with wwise).

the cli tools for creating lipsync anims and packing the files already exist (http://www.nexusmods.com/witcher3/mods/2124/)  but the audio encoding must still be done in wwise

**Comment by Traderain** [comment]
I think the best would be if we used sphinx: https://github.com/cmusphinx/sphinxbase and convert all the voicelines by a single character eg.: Geralt and use them to train an acoustic model. So a pretty similar speech to the original one can be generated. This should be a first run thing so it gets cached. After this is done when we add completely new actors or something I guess we could use the build in ones or make the user to be able to open a spinx dictionary or something.
Lipsync animations are still questionable. I still have no idea how rmemr does this in his tool. I guess we can use his tool as a last case scenario.
