### ISSUE TITLE
CR2W editing and viz target

### ISSUE THREAD

**Issue by Maxzor** [WolvenKit/WolvenKit#239]
# Reworking cr2w editing & vizualization
Just to clarify : a cr2w file has a chunklist and a propertylist.
![image](https://user-images.githubusercontent.com/16599683/93666537-4eea7400-fa7f-11ea-86b1-b513e924e44a.png)

The **main goal** is :
- ~~to remove as much as possible editing from the chunklist, and to move it to the property list :
forcing people to **think objects and not serialization**~~ Turns out I was wrong, both panes are quite equivalent so readded editing operations (except copy-insert) on chunk list.
- to have by default solid cr2w modification rules to guide the users, and have the engine accept those edits.

## Property operations :

_Cannot_ add unknown variables to native classes.

_Cannot_ add unknown variables to scripted classes from wkit, but new scripted classes can be compiled by wkit with the added properties discovered and made usable.

_Can only_ add/remove properties in arrays :

| - 	| Modifying properties in arrays 	| Commit/PR 	| Note 	|
|:-:	|:-:	|-	|-	|
|  :white_check_mark:	| reindexing 	|  	|  	| 
|   	| moving up/down 	|  	|  	| 
| :white_check_mark:  	| referrers updates on creation / deletion 	|  	|  No multi-referred chunk has a parenting distance with each of its referrers bigger than one, either on real or virtual chunkindex	|
|  	| drag and drop 	|  	| ![propdrag](https://user-images.githubusercontent.com/16599683/93667126-b4406400-fa83-11ea-8135-00f57388332b.png) 	|
|  	| clear variable function 	|  	|  removed for now	|
| :white_check_mark: 	| inter-cr2w file operations  	|  #242	|  works on a per-cvariable basis and for chunks, subject to the same problems as property-copying   	|

### FCD
- [ ] auto-generation

## Property viz :
| - 	| Prop viz 	| Commit/PR 	| Note 	|
|:-:	|:-:	|-	|-	|
| :white_check_mark: 	| Show all properties / show only serialized props  	|  	|  	|
| :white_check_mark: 	| Prop color picker  	|  	|  	|
|  	| Native and scripted classes/props in different colors  	|  	|  	|

## Chunk operations :

| - 	| Chunk ops 	| Commit/PR 	| Note 	|
|-	|-	|-	|-	|
|  :white_check_mark:	| Cannot modify chunks by default 	|  	|  Apart from copying and pasting in the context menu, which is only an abstraction of the underlying CVariable data property copying.	|
|  :white_check_mark:	| A ~~hidden setting triggers "entering crazy-advanced-user-mode"~~, where no chunk edit is forbidden 	|  	|  creating a new chunk from nothing and parenting it manually,  and deleting chunks manually. This requires updating all pointers!! |
| :white_check_mark:	| Maintain a children list per chunk 	|  	|  	|
| :white_check_mark: 	| Auto-chunk create and delete (based on property edits) 	|  #242	|  implemented for arrays of Pointers/Handles and on an individual basis inside the dropdown menu	|
|  :white_check_mark:	| Chunk reindexing API - maintain a consistent chunk hierarchy & index 	|  #251 , #256	| 	|

## Chunk vizualization :
| - 	| Chunk viz 	| Commit/PR 	| Note 	|
|-	|-	|-	|-	|
| :white_check_mark: 	| display chunks sequential, with a virtual parent chunk  	| #210 	|  lacks a unit test to assert all cr2ws are one-root DAGs with this	|
| :white_check_mark: 	| have a pure chunk index column 	|  	| if people want that, they can switch to ListView 	|

## Navigation and dependencies :

| - 	| Following references (CPtr, CHandle, CSoft) 	| Commit/PR 	| Note 	|
|:-:	|:-:	|-	|-	|
| :white_check_mark: 	| Move from a chunk ref to the chunk 	|  b192ff5e0e29276a9debc36ebf7d4348039e9898	|  ~~Lacks frmChunkList update so far~~ implemented in #242	|
|  	| Move from a file ref to the file 	|  | Could use the modexplorer "add file dependencies"? 	|

**Comment by rfuzzo** [comment]
most pressing issue is virtual parenting issues, re-indexing:
steps to reproduce: 
go into characters\base_entities\arachas_base\arachas_base.w2ent 
'> CHardAttachmnet#12 > parentSlot > right click: Delete Chunk Target 
Chunks go missing in the TreeView, but not in the ListView of the Chunk List
that means the virtual parent re-indexing is not working

**Comment by Maxzor** [comment]
> I just had an idea: could it be that all "unknown byes" = all data not serialized from the class
> is data that is automatically created?
> 
> for example, the components array of CEntities is such a buffer (and it has all references to the CComponent children of the class) so it would make sense to not let the user edit it but create it automatically upon serialization
> 
> same for AttachMentsReferences, etc etc, 
> all stuff that maybe was never intended to be edited in Redkit directly, but that gets created from existing data in a file
> @rfuzzo 
> I think you nailed it, the components array of centity just is a convenience towards the actual dependency files, without having to dig the full chunk hierarchy. It tries to flatten this latter and strives to avoid recursion
> It must have been created by an intern? It fucks up all the parentID and is one of the big reasons the virtualparentchunkid is useful on our side
> smells/stinks like code overhaul gone wrong
So : disable Components editing

**Comment by Maxzor** [comment]
- [ ] disable Components editing
> I just had an idea: could it be that all "unknown byes" = all data not serialized from the class
> is data that is automatically created?
> 
> for example, the components array of CEntities is such a buffer (and it has all references to the CComponent children of the class) so it would make sense to not let the user edit it but create it automatically upon serialization
> 
> same for AttachMentsReferences, etc etc, 
> all stuff that maybe was never intended to be edited in Redkit directly, but that gets created from existing data in a file
> @rfuzzo 
> I think you nailed it, the components array of centity just is a convenience towards the actual dependency files, without having to dig the full chunk hierarchy. It tries to flatten this latter and strives to avoid recursion
> It must have been created by an intern? It fucks up all the parentID and is one of the big reasons the virtualparentchunkid is useful on our side
> smells/stinks like code overhaul gone wrong

**Comment by Maxzor** [comment]
CR2W file types that have multi referrers :
```sql
   fileextension   |           referrername            |   nb   | direction 
-------------------+-----------------------------------+--------+-----------
 {spawntree}       | params                            |    970 | {down,up}
 {w2beh}           | cachedAddedInputNode              |    181 | {down,up}
 {w2beh}           | cachedAdditiveNode                |    224 | {down,up}
 {w2beh}           | cachedAngleVariableNode           |     12 | {down,up}
 {w2beh}           | cachedAnimInputNode               |    120 | {down,up}
 {w2beh}           | cachedBaseInputNode               |    347 | {down,up}
 {w2beh}           | cachedCompareParentInput          |     23 | {down,up}
 {w2beh}           | cachedControlNode                 |     32 | {down,up}
 {w2beh}           | cachedControlValueNode            |   6195 | {down,up}
 {w2beh}           | cachedControlVariableNode         |   1091 | {down,up}
 {w2beh}           | cachedControlVariableNode_A       |      8 | {down,up}
 {w2beh}           | cachedControlVariableNode_B       |      8 | {down,up}
 {w2beh}           | cachedCustomInputNodes            |    838 | {down,up}
 {w2beh}           | cachedDecSpeedNode                |     20 | {down,up}
 {w2beh}           | cachedDirectionNode               |      9 | {down,up}
 {w2beh}           | cachedDurationValueNode           |      8 | {down,up}
 {w2beh}           | cachedEndStateNode                |  15290 | {down,up}
 {w2beh}           | cachedFalseInputNode              |    479 | {down,up}
 {w2beh}           | cachedFirstInputNode              |   2494 | {down,up}
 {w2beh}           | cachedFloatInputNodes             |     31 | {down,up}
 {w2beh}           | cachedForcePropNode               |     64 | {down,up}
 {w2beh}           | cachedForceTimeNode               |    274 | {down,up}
 {w2beh}           | cachedHorizontalAdditiveInputNode |     88 | {down,up}
 {w2beh}           | cachedIncSpeedNode                |     17 | {down,up}
 {w2beh}           | cachedInjectorNode                |      6 | {down,up}
 {w2beh}           | cachedInputANode                  |     11 | {down,up}
 {w2beh}           | cachedInputBNode                  |     11 | {down,up}
 {w2beh}           | cachedInputNode                   |  14437 | {down,up}
 {w2beh}           | cachedInputNode_A                 |      8 | {down,up}
 {w2beh}           | cachedInputNodes                  |  25759 | {down,up}
 {w2beh}           | cachedLookAtTargetDirMSInputNode  |      3 | {down,up}
 {w2beh}           | cachedLookAtVariableNode          |    120 | {down,up}
 {w2beh}           | cachedNodes                       |     43 | {down,up}
 {w2beh}           | cachedOneNode                     |     24 | {down,up}
 {w2beh}           | cachedOverrideInputNode           |    329 | {down,up}
 {w2beh}           | cachedParentInput                 |   4713 | {down,up}
 {w2beh}           | cachedParentValueNode             |   2437 | {down,up}
 {w2beh}           | cachedParentVectorValueNode       |      4 | {down,up}
 {w2beh}           | cachedRootBoneImpulseVariable     |    214 | {down,up}
 {w2beh}           | cachedSecondInputNode             |   2064 | {down,up}
 {w2beh}           | cachedSelNode                     |     24 | {down,up}
 {w2beh}           | cachedShiftVariableNode           |      6 | {down,up}
 {w2beh}           | cachedSpeedNode                   |      9 | {down,up}
 {w2beh}           | cachedSpeedTimeNode               |   2040 | {down,up}
 {w2beh}           | cachedStartStateNode              |  13719 | {down,up}
 {w2beh}           | cachedStateTransitions            |  13719 | {down,up}
 {w2beh}           | cachedTargetNode                  |     19 | {down,up}
 {w2beh}           | cachedTargetPositionNode          |     23 | {down,up}
 {w2beh}           | cachedTargetPosNode               |      4 | {down,up}
 {w2beh}           | cachedTestedValue                 |    257 | {down,up}
 {w2beh}           | cachedThresholdNode               |      9 | {down,up}
 {w2beh}           | cachedTrueInputNode               |    502 | {down,up}
 {w2beh}           | cachedTwoNode                     |     24 | {down,up}
 {w2beh}           | cachedValueNode                   |    513 | {down,up}
 {w2beh}           | cachedVariableNode                |   2019 | {down,up}
 {w2beh}           | cachedVerticalAdditiveInputNode   |     54 | {down,up}
 {w2beh}           | cachedWeightVariableNode          |      5 | {down,up}
 {w2beh}           | Outputnode                        |  11356 | {down,up}
 {w2cent,w2ent}    | AttachmentsReference              |  41055 | {down,up}
 {w2cent,w2ent}    | child                             |  40624 | {down,up}
 {w2cent,w2ent}    | transformParent                   |  40943 | {down,up}
 {w2ent}           | reactions                         |     44 | {down,up}
 {w2phase}         | entry                             |    267 | {down,up}
 {w2phase}         | manualObjective                   |     77 | {down,up}
 {w2phase}         | mappinEntry                       |    537 | {down,up}
 {w2phase}         | objectiveEntry                    |     23 | {down,up}
 {w2phase}         | questEntry                        |   1301 | {down,up}
 {w2phase,w2quest} | ock                               | 179053 | {down,up}
 {w2scene}         | interceptSections                 |     70 | {down,up}
 {w2scene}         | linkedElements                    |  67399 | {down,up}
 {w2scene}         | nextLinkElement                   |  67399 | {down,up}
(71 lignes)


```

**Comment by Maxzor** [comment]
As per the above list, CR2W file types where tree view makes no sense, and where a graphviz is necessary.
This is already the case, but the graph viz needs polishing.
`spawntree, w2beh, w2phase, w2quest, w2scene`

The other multi-ref file types can be handled with treelistview : `w2cent, w2ent`.

**Comment by Maxzor** [comment]
For w2[c]ent :
```sql
 count |    referrer_name     | Direction 
-------+----------------------+-----------
  1910 | AttachmentsReference | down
 39145 | AttachmentsReference | up
 38714 | child                | down
  1910 | child                | up
    22 | reactions            | down
    22 | reactions            | up
  1804 | transformParent      | down
 39139 | transformParent      | up

```

**Comment by Maxzor** [comment]
I still see missing :
- Moving chunk/prop-in-array up/down
- Drag and drop chunk/prop-in-array
- Scripted native visibly different
- Unit tests
- (puny) no pink default for font color in light theme

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
