### ISSUE TITLE
After v0.7 is closed there is still a WolvenKit.exe process running 

### ISSUE THREAD

**Issue by duffremle** [WolvenKit/WolvenKit#241]
**Describe the bug**
I noticed that after I close down v0.7 that there are still WolvenKit.exe processes running if I open Task Manager.

[Edit] Today I noticed that closing WolvenKit leaves just 1 WolvenKit.exe process running, but if it's opened & closed multiple times (over an afternoon or whatever) a WolvenKit.exe process will be left running for each time it was opened. That must be how the screenshot has multiple WolvenKit.exe processes left running.

**To Reproduce**
Just run it and then close out of it

**Expected behavior**
There shouldnt be any processes left running.

**Screenshots**
![0 2018 08 21 version program shut down still 5 (see the edit below) wkit processes running](https://user-images.githubusercontent.com/71484892/93694451-72d6a580-fad1-11ea-806e-066a67d36e81.jpg)

**Desktop (please complete the following information):**
 - OS: win 7
 - Browser firefox
 - Version 80

**Comment by Traderain** [comment]
@rfuzzo Any idea what process is it? Maybe we could create a list to hold the currently running thread's reference in MainController and on FormClosing what for them/kill them.

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
