### ISSUE TITLE
Support serialization to and from common text formats

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#255]
# (De)serialization support for common text formats
What I can think of now is:
- [ ] Yaml - maybe radish compliant?
  - [ ] Read
  - [ ] Write
  - [ ] Test
- [ ] Csv
  - [ ] Read
  - [ ] Write
  - [ ] Test
- [ ] Json
  - [ ] Read
  - [ ] Write
  - [ ] Test  
***
This would help a lot with designing complex editors and should be a priority and we should probably make some unit tests for this as well maybe we could allow editing files like the visual studio wpf designer where you edit the text and the cr2w is previewed. idk, looking for comments. I'll probably have time to implement this soon since I wana tackle #79 but this is a prerequisite I think.

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by rfuzzo** [comment]
this is implemented in RED4, but will work for RED3 once we support tw3 again.
