### ISSUE TITLE
adjusting of phoneme timings for better lipsync generation

### ISSUE THREAD

**Issue by ghost** [WolvenKit/WolvenKit#27]
As a voice asset modder I want to adjust the lipsync timings of new voicelines to tune the results.

Automatically extracted phoneme timings need to be adjusted most of the time before generating the lipsync animations. This is a time consuming process  (see https://www.youtube.com/watch?v=oI6PvgqE-wM)

- load configuration from #24 and show the list with info about available phoneme timings
- on selection of one voiceline, backup the original timings and show a "adjust timings" view with:
  - audio wave form 
  - associated timings (from the csv file)
  - used text (see below for ascii art)
  - optional: the originally extracted timings
- in timings view:
  - playback of audio with play position cursor
  - zoom of waveform (+/- keys as most simple solution)
  - scrolling of position
  - timings line must be linked with zoom and scrolling operations
  - interactive moving/shrinking/expanding of phoneme blocks (which adjusts the timings)
- save updated to timings in the same csv format for the generation of lipsync

**Comment by rmemr** [comment]
adjust timings view, something like this:

![timings](https://cloud.githubusercontent.com/assets/24299060/23581049/5f3120e4-010d-11e7-8206-27e9c76c2b7c.png)

- the phonemes bar could have colored blocks to represent the score of the extraction
- every block represents the timespan of a phoneme, adjusting the position/size readjust the timings
