### ISSUE TITLE
Cyberpunk 2077 basic support

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#286]
We need to investiagate and update this but at first:
- [x] bundle? extractor, packer would be first priority
***
We should try to document what changed since w3 and what can we reuse with little or no changes.
![image](https://user-images.githubusercontent.com/6411732/101355465-e4372080-3896-11eb-84d5-b6234f4a99bb.png)

**Comment by Traderain** [comment]
So they are "KARK" archives: https://gist.github.com/rfuzzo/2b4e366b6551934337d804ead5b36744
https://github.com/rfuzzo/CP77Tools

**Comment by nulloutput** [comment]
CR2W files are version 195 in Cyberpunk 2077:

![unknown](https://user-images.githubusercontent.com/45448513/101441142-57c94400-3910-11eb-8a55-cdad2961c3f5.png)
![asdfasdf](https://user-images.githubusercontent.com/45448513/101441205-7f201100-3910-11eb-92b3-f049605c78ef.png)

I've extracted and decompressed the files but extraction is currently meaningless without the folder and filenames, which are nowhere to be found.  The archive format either relies on data currently lacking from the preloads (e.g. external string tables) or the archive format is entirely hash-based when it comes to file lookups.

**Comment by nulloutput** [comment]
Here is a selection of CR2W files from `basegame_1_engine.archive`

[extract.zip](https://github.com/Traderain/Wolven-kit/files/5656999/extract.zip)

**Comment by Maxzor** [comment]
maybe metadatastores if this is still a thing will come at release

**Comment by IceReaper** [comment]
Just woke up to find this. Nice progress! I posted on xentax yesterday too, i think i had some additional information like the filetime in my code too, feel free to take what you miss.

**Comment by nulloutput** [comment]
There are also a lot of files with a header signature of `04 00 07 00` that look just like CR2W at a glance, which make up almost half the compressed files in `basegame_1_engine.archive`

[extract4070.zip](https://github.com/Traderain/Wolven-kit/files/5657370/extract4070.zip)

**Comment by rfuzzo** [comment]
just a bit more info on the .archive format. the first table
```table1entry:
        seq:
          - id: start
            size: 16
          - id: somebool
            type: u4
          - id: startindex
            type: u4
          - id: nextindex
            type: u4
          - id: unk4
            type: u4
          - id: unk5
            type: u4
          - id: end
            size: 20```
has indices for the second, offset table. so one file can have different chunks of KARK (and sometimes not KARK) bytes. 
not exactly sure what the reason is. but the startindex and the nextindex gives you the range of byte-offsets for one file...

**Comment by 4K11R4** [comment]
Hello,

     Using rfuzzo's CyberPunk2077 tools I was able to decompress the .archive files. I targeted the: " basegame_5_video.archive " file as it was obviously holding video data for menu / effects / in game video adverts / etc. The files all begin with: 4B 42 32 6A or KB2j.

     They are Bink / Bink2 video files that can be played back via the RadTools. (http://www.radgametools.com/bnkdown.htm) Hope this can help in finding the file types. Got to start somewhere...
![NODATA](https://user-images.githubusercontent.com/75670089/101470282-a835a700-38fa-11eb-9229-77a55f8e0149.png)

**Comment by rfuzzo** [comment]
> 
> 
> Here is a selection of CR2W files from `basegame_1_engine.archive`
> 
> [extract.zip](https://github.com/Traderain/Wolven-kit/files/5656999/extract.zip)

@nulloutput  hej can you tell me how you decompressed the files?

**Comment by DartPower** [comment]
Very good idea.
And...
Can you also use this? 
https://github.com/rfuzzo/CP77Tools

**Comment by 4K11R4** [comment]
Hello,

     This should help. I mean it is right there in the filename. " oodle_dictionary.bin "
[oodle_dictionary.zip](https://github.com/Traderain/Wolven-kit/files/5669868/oodle_dictionary.zip)

**Comment by redrib** [comment]
> Hello,
> 
> ```
>  Using rfuzzo's CyberPunk2077 tools I was able to decompress the .archive files. I targeted the: " basegame_5_video.archive " file as it was obviously holding video data for menu / effects / in game video adverts / etc. The files all begin with: 4B 42 32 6A or KB2j.
> 
>  They are Bink / Bink2 video files that can be played back via the RadTools. (http://www.radgametools.com/bnkdown.htm) Hope this can help in finding the file types. Got to start somewhere...
> ```
> 
> ![NODATA](https://user-images.githubusercontent.com/75670089/101470282-a835a700-38fa-11eb-9229-77a55f8e0149.png)

have u managed to find the ingame ad posters? or ads in general. If it isnt too much to ask could u put it somewhere on github.. 
im not that familiar with rfuzzo's tool. 

I wanna make a mod with those posters!!

thanks.. kind regards.

**Comment by larrykoubiak** [comment]
Hello everyone, landed here trying to understand the format of the files.
I'll take some time to go through all the work that is already done. Just wanted to share my (very quick and dirty) python script to extract the files purely from guesswork (hence all the "unk" variables).
I did some dirty "type detection" to make the video and audio usable directly.
It's probably not of great value to you guys but just in case :D 

https://pastebin.com/RFeA6U23

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by martinsstuff** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Github](https://trello.com/c/V52duEWM/16-github)

> This card may be on a private board. You may be able to view it by logging in.

**Comment by tryadelion** [comment]
Is there any branch/fork where CP2077 executable can be chosen?

**Comment by Traderain** [comment]
We are still working on it so not yet.

**Comment by tryadelion** [comment]
if there's anything i can do to help, i'll be glad to. can handle my way trough C#. i'm specially confused (given i never modded a CDPR game before) about all their custom ( and witcher-2-prefixed ) formats like .w2mi, etc.

**Comment by Traderain** [comment]
@tryadelion If you are willing to help we are currently reworking the old app in WPF, you can help with converting the old winforms forms in WPF with Catel MVVM (#169 )

**Comment by tryadelion** [comment]
@Traderain  maybe late to the party, but wouldn't a cross-platform thingy with native .net/cs/c++ support (flutter desktop, etc... ) put less strain to design and be more future proof, UI-side-speaking? i'll try to lend a hand on that issue though. thanks for the link

**Comment by Traderain** [comment]
> @Traderain maybe late to the party, but wouldn't a cross-platform thingy with native .net/cs/c++ support (flutter desktop, etc... ) put less strain to design and be more future proof, UI-side-speaking? i'll try to lend a hand on that issue though. thanks for the link

Well, there is a bunch of code already in .net and rewriting everything in let's say rust and remaking the whole UI in QT wouldn't really satisfy the work required. Most of us are comfortable with c# and .net already and with a bit of work it can work very well.

**Comment by NHodgesVFX** [comment]
What about https://github.com/AvaloniaUI/Avalonia

**Comment by Jack01101** [comment]
> 
> 
> Hello,
> 
> ```
>  Using rfuzzo's CyberPunk2077 tools I was able to decompress the .archive files. I targeted the: " basegame_5_video.archive " file as it was obviously holding video data for menu / effects / in game video adverts / etc. The files all begin with: 4B 42 32 6A or KB2j.
> 
>  They are Bink / Bink2 video files that can be played back via the RadTools. (http://www.radgametools.com/bnkdown.htm) Hope this can help in finding the file types. Got to start somewhere...
> ```
> 
> ![NODATA](https://user-images.githubusercontent.com/75670089/101470282-a835a700-38fa-11eb-9229-77a55f8e0149.png)

Hello,
I know this is a little out of left field, but I was wondering if you could link me the "basegame_5_video.archive" _archive_. Mine seems to be having some issues, I would really appreciate the help.

Kindest regards,
-J

![image](https://user-images.githubusercontent.com/74255545/103547815-2c9d2a80-4ea5-11eb-9bbb-d57f705770c7.png)

**Comment by Traderain** [comment]
> > Hello,
> > ```
> >  Using rfuzzo's CyberPunk2077 tools I was able to decompress the .archive files. I targeted the: " basegame_5_video.archive " file as it was obviously holding video data for menu / effects / in game video adverts / etc. The files all begin with: 4B 42 32 6A or KB2j.
> > 
> >  They are Bink / Bink2 video files that can be played back via the RadTools. (http://www.radgametools.com/bnkdown.htm) Hope this can help in finding the file types. Got to start somewhere...
> > ```
> > 
> > 
> > ![NODATA](https://user-images.githubusercontent.com/75670089/101470282-a835a700-38fa-11eb-9229-77a55f8e0149.png)
> 
> Hello,
> I know this is a little out of left field, but I was wondering if you could link me the "basegame_5_video.archive" _archive_. Mine seems to be having some issues, I would really appreciate the help.
> 
> Kindest regards,
> -J
> 
> ![image](https://user-images.githubusercontent.com/74255545/103547815-2c9d2a80-4ea5-11eb-9bbb-d57f705770c7.png)

Verify file integrity on steam. Gog probably has something like that too.

**Comment by Jack01101** [comment]
Hi!
Thanks a lot for the reply. The file verification doesn't seem to be cutting it for some reason, I don't know much about these things, but it either just doesn't do anything or the file it is supposed to verify with is also broken. I'm not exactly the brightest bulb in the coffin so I thought cutting it across the field and just replacing the file manually would be easier.

Thanks,
-J

**Comment by Traderain** [comment]
We are not far from releasing the initial version with cyberpunk support :)
Here is a little sneak peek:
![image](https://user-images.githubusercontent.com/6411732/106537806-604a8f00-64fb-11eb-97f9-202f6f87c662.png)

**Comment by Traderain** [comment]
We are releasing a build with basic support for Cyberpunk 2077 tomorrow.
