### ISSUE TITLE
Game selector

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#287]
To support multiple games we need a way for the user to choose what game they prefer to edit, something like OpenIV would suffice:
![image](https://user-images.githubusercontent.com/6411732/101487655-c634f300-395e-11eb-94fd-3e2dac7cf001.png)

**Comment by rfuzzo** [comment]
yeah that or do it a la Visual Studio and have .w3modproj and .cp77modproj files
and do the selection according to the loaded project.

**Comment by rfuzzo** [comment]
also, if you do that, could be work with the WPF fork of WolvenKit?

**Comment by Traderain** [comment]
> yeah that or do it a la Visual Studio and have .w3modproj and .cp77modproj files
> and do the selection according to the loaded project.

oh thats a much better idea

**Comment by Traderain** [comment]
> also, if you do that, could we work with the WPF fork of WolvenKit?

Yeah we should try get the asset browser running in that and merge it and work from that

**Comment by Maxzor** [comment]
I think that, if redengine classes, archive structure, file hierarchy, are different enough, a fork of wolvenkit makes sense to not carry too much legacy from w3

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)

**Comment by Offline-R503B** [comment]
@Traderain This can be closed?
