### ISSUE TITLE
Unable to clone repo due to LFS bandwidth overage

### ISSUE THREAD

**Issue by specik** [WolvenKit/Wolvenkit#291]
**Describe the bug**
Unable to clone repo due to LFS bandwidth overage

`Error downloading object: WolvenKit.Irrlicht/lib/Debug/libfbxsdk-md.lib (2bdaa6d): Smudge error: Error downloading WolvenKit.Irrlicht/lib/Debug/libfbxsdk-md.lib (2bdaa6dbf2193a82300cf2242c03b2b328218041b6ad45628649d0fc010b2f77): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`

**To Reproduce**
1. Try to clone repo
2. Witness error

**Expected behavior**
Should be able to clone repo

**Comment by Traderain** [comment]
Hey, thanks for the report. I am trying to figure out something because the recent interest instanly depletes my git LFS  quota hence the error. Here are the required files: https://outwa.it/lib.zip I am working on a better solution.
