### ISSUE TITLE
Cache file parsing

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#30]
- [ ] Texture
  - [x] Reading
  - [ ] Writing
- [ ] Collision
  - [x] Reading
  - [ ] Writing
- [ ] Shader
  - [x] Reading
  - [ ] Writing
- [x] Sound
  - [x] Reading
  - [x] Writing
- [ ] Dep
  - [x] Reading
  - [ ] Writing
- [ ] Streaming
  - [x] Reading
  - [ ] Writing
There needs to be a bundleexplorer like browser for these files to or somehow unify it with bundleexplorer.

**Comment by Traderain** [comment]
1a17282f0d64a5031cb40199ee448043abe3278f does the basic parsing of Texture.cache but since #11 's texture converter is not fixed yet it can't be actually used.

**Comment by Traderain** [comment]
ae1f27a53eb91114107ac6ba2a6ed22b159b49ee does the basic reading of sound.cache and texture.cache

**Comment by Traderain** [comment]
Shader and dep etc. cache is only binary data and the game can be asked to recompile those. So similarly to redcripts unless we find a really good reason to parse them it is unnecessary to research them.

**Comment by Traderain** [comment]
Soundcache is implemented in 028803b07b58371607b359ee6a7d01c54cf56544.

**Comment by Traderain** [comment]
CollisionCache:
```python
Int32    MW "CC3W"
Int32    Version 9
Int64     Unk
Int32    InfoOffset
Int32    NumberOfFiles
Int32    FileNameTableStartOffset
Int32    SizeOfNameTable
Int32    BufferSize
Int32    Fnv1A64Hash(NamesTable+InfoTable)

br.BaseStream.Seek(InfoOffset,SeekOrigin.Begin);
for(int i = 0; i < NumberOfFiles;i++)
{
    Int64    Unk1 //Maybe always null?
    Int64    NameOffset
    Int32    Offset
    Int32    Length
    Int64    Unknown2
    Int64    Unknown3
    Int64    Unknown4
    Int64    Unknown5
    Int64    Unknown6
    Int64    CompressionType
}
```
Files inside it are .p3d/.nxb files compressed with Zlib.
https://community.bistudio.com/wiki/P3D_File_Format_-_ODOLV4x
https://github.com/H-uru/libhsplasma/blob/master/core/PRP/Physics/plPXPhysical.cpp#L146
https://forum.worldofplayers.de/forum/threads/1361749-Tool-CSMeshCooker-%28Collision-Shapes%29?s=70c493a4c12414a81e77e3fb38439a6e
This helps with #5 .

**Comment by rfuzzo** [comment]
Collision.cache item:

```
NameOffset = br.ReadUInt64(),
Unk1 = br.ReadUInt64(),       //NULL?
PageOFfset = br.ReadUInt32(),
ZSize = br.ReadUInt32(),
Size = (long)br.ReadUInt64(),
Unk2= br.ReadBytes(16),    // Some hash or GUID
Unk3 = br.ReadBytes(16),     // Some hash or GUID
Comtype = br.ReadUInt64()
```
