### ISSUE TITLE
Asset browser file format icons

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#303]
Cyberpunk 2077:
- [x] actionanimdb - Animation
- [x] acousticdata - Audio
- [x] aiarch - Pathfinding/AI
- [x] animgraph - Animation graph
- [x] anims - Animation
- [x] app - Configuration
- [x] archetypes - No idea
- [x] areas - Terrain related
- [x] audio_metadata - Audio
- [x] audiovehcurveset - Audio
- [x] behavior - Behvaiour graph
- [x] bikecurveset - No idea? Probably vehicles?
- [x] bk2 - Bink video
- [x] bnk - Bink video
- [x] camcurveset - Camera curve preset
- [x] cfoliage - Trees, etc foliage
- [x] charcustpreset - Character editor preset
- [x] cminimap - Minimap
- [x] community - Quest related
- [x] conversations - Cutscene related
- [x] cooked_mlsetup - No idea
- [x] cookedanims - Animation
- [x] cookedapp - Configuration
- [x] credits - Configs for the credits
- [x] csv - Normal csv file
- [x] cubemap - 6 sided cube texture
- [x] curveset - Set of curves for something
- [x] dat - data
- [x] devices - No idea
- [x] dtex - No idea
- [x] effect - No idea
- [x] ent - Entity data
- [x] env - Enviroment settings
- [x] envparam - Enviroment settings
- [x] envprobe - Enviroment settings
- [x] es - No idea
- [x] facialcustom - No idea
- [x] facialsetup - No idea
- [x] fb2tl - No idea
- [x] fnt - Font
- [x] folbrush - Foliage brush
- [x] foldest - Destructable foliage element
- [x] fp - No idea
- [x] gamedef - Game main configuration file
- [x] garmentlayerparams - No idea
- [x] genericanimdb - No idea
- [x] No idea - Terrain
- [x] gidata - TODO
- [x] gradient - No idea
- [x] hitrepresentation - No idea
- [x] hp - No idea
- [ ] ies - No idea
- [ ] inkanim - UI Animation
- [ ] inkatlas - UI Texture atlas
- [ ] inkcharcustomization - UI character stuff
- [ ] inkfontfamily - UI Font
- [ ] inkfullscreencomposition - UI
- [ ] inkgamesettings - UI Settings
- [ ] inkhud - UI
- [ ] inklayers - UI
- [ ] inkmenu - UI
- [ ] inkshapecollection - UI
- [ ] inkstyle - UI
- [ ] inktypography - UI
- [ ] inkwidget - UI
- [x] interaction - UI
- [x] journal - Quest info
- [x] journaldesc - Quest info
- [x] json - Json file
- [x] lane_connections - Traffic?
- [x] lane_polygons - Traffic?
- [x] lane_spots - Traffic?
- [ ] lights - Lightning data
- [ ] lipmap - Lighting info
- [ ] location - Map location?
- [ ] locopaths - Player animation something?
- [ ] loot - No idea
- [ ] mappins - Pins on the map
- [ ] mesh - Meshes
- [ ] mi - Material instance for models
- [ ] mlmask - Models
- [ ] mlsetup - Models
- [ ] mltemplate - Models
- [ ] morphtarget - Boob physics etc :D
- [ ] mt - TODO
- [ ] navmesh - AI navigation info
- [ ] null_areas - No idea
- [ ] opusinfo - Audio
- [ ] opuspak - Audio
- [ ] particle - Particle effect
- [ ] phys - Nvidia PhysX stuff
- [ ] physicalscene - Nvidia PhysX stuff
- [ ] physmatlib - Nvidia PhysX stuff
- [ ] poimappins - Map pin
- [ ] psrep - TODO
- [ ] quest - Quest
- [ ] questphase - Quest progression
- [ ] regionset - TODO
- [ ] remt - No idea
- [ ] reslist - Resource list
- [ ] rig - Model skeleton rigging info
- [ ] scene - Cutscene
- [ ] scenerid - Cutscene info
- [ ] scenesversions - Cutscene versioning
- [ ] smartobject - No idea
- [ ] smartobjects - No idea
- [ ] sp - No idea
- [ ] spatial_representation - TODO
- [ ] streamingquerydata - Terrain
- [ ] streamingsector - Terrain
- [ ] streamingsector_inplace - Terrain
- [ ] streamingworld - Terrain
- [ ] terrainsetup - Terrain
- [ ] texarray - Multiple textures
- [ ] traffic_collisions - TODO
- [ ] traffic_persistent - TODO
- [ ] voicetags - TODO
- [ ] w2mesh - Model mesh
- [ ] w2mi - Materials for models
- [ ] wem - Audio file
- [ ] workspot - No idea
- [ ] xbm - Texture
- [ ] xcube - Texture

Witcher 3:
- [ ] XML	XML File	xml file can be opened in text editors.
- [ ] XBM	CR2W file	Fully parsed altought some stuff is not yet correct?
- [ ] Wizdef	CR2W file	Parsed fully since there is only one of this and doesnt contain anything might be a test file
- [ ] W3Simplex	CR2W file	Parsed fully contains simplex data
- [ ] W3Occulsion	CR2W file	Little stuff is missing contains occulsion data
- [ ] W3Fac	CR2W file	Missing a lot contains skeleton and MimicFace
- [ ] W3Dyng	CR2W file	Missing a lot contains dyng resource and sekeleton
- [ ] W3App	CR2W file	Parsed fully contains appearances
- [ ] W2W	CR2W file	Missing a lot contains info about how a level is set up
- [ ] W2Ter	CR2W file	Little stuff is missing contains terrain info
- [ ] W2Steer	CR2W file	Parsed fully contains movement and steering commands
- [ ] W2Sf	CR2W file	Parsed fully contains Switchable foliage
- [ ] W2Scene	CR2W file	Parsed fully contains conversation/scene
- [ ] W2Rig	CR2W file	Contains rig
- [ ] W2Ragdoll	CR2W file	Parsed fully lot contains ragdoll data/begaviour
- [ ] W2Quest	CR2W file	Parsed fully contains a quest
- [ ] W2Qm	CR2W file	Parsed fully contains the pins a world
- [ ] W2Phase	CR2W file	Parsed fully contains quest progress
- [ ] W2P	CR2W file	Missing a lot contains particle system
- [ ] W2Mi	CR2W file	Parsed fully contains material instance
- [ ] W2Mg	CR2W file	Parsed fully contains material graph
- [ ] W2Mesh	CR2W file	Missing a lot contains a mesh(es?)
- [ ] W2L	CR2W file	Little stuff is missing contains level data
- [ ] W2Job	CR2W file	Parsed fully contains an action/job for an NPC
- [ ] W2Je	CR2W file	Parsed fully contains collection of journal entries
- [ ] W2Fnt	CR2W file	Missing a lot contains a font
- [ ] W2Ent	CR2W file	Little stuff is missing contains entity data
- [ ] W2Em	CR2W file	Parsed fully contains map pins info
- [ ] VBrush	CR2W file	Parsed fully contains a vegetation brush(es)
- [ ] Usm	Multiplexed video file	Needs to be demultiplexed to view as a video file
- [ ] Textarray	CR2W file	Missing a lot contains a textarray
- [ ] Subs	Text file	Can be opened with any ordinary text editor
- [ ] Srt	Unknown	Can't parse it (Might be SRT Tree or Speedtree?)
- [ ] Spawntree	CR2W file	Parsed fully contains spawning data
- [ ] Sav	Save file	Parsed fully but not implemented yet and for some random reason there is one in game archives
- [ ] Redwpset	CR2W file	Missing a lot of stuff contains waypoint collection
- [ ] Redswf	CR2W file	Swf stuff and dds images
- [ ] Redicsv	CR2W file	Missing a lot contains a 2d array of data
- [ ] Redgame	CR2W file	Parsed fully contains info about game resource
- [ ] Redfur	CR2W file	Parsed fully contains Hairworks info probably
- [ ] Redexp	CR2W file?	Missing a lot of stuff contains Areas
- [ ] Reddlc	CR2W file	Parsed fully contains dlc info
- [ ] Reddest	CR2W file	Little stuff is missing contains Apex destruction info
- [ ] Redcloth	CR2W file	Parsed fully contains Apex cloth
- [ ] Redapex	CR2W file	Parsed fully contains Apex destruction info
- [ ] Popup	CR2W file	Parsed fully contains info about a popup
- [ ] Navtile	Unknown	Not parsed, not even listed by wcc_lite (no idea)
- [ ] Navmesh	Unknown	Not parsed (Probably Navmesh info?)
- [ ] Naviobstacles	Unknown	Not parsed (probably info about obstacles for NPCs)
- [ ] Navgraph	Unknown	Not parsed (no idea)
- [ ] Navconfig	Unknown	Not parsed (maybe pathfinder config for the ai?)
- [ ] Menu	CR2W file	Fully parsed contains info about a menu element
- [ ] Journal	CR2W file	Fully parsed contains info about a journal entry
- [ ] Hud	CR2W file	Fully parsed contains info about hud elements
- [ ] Guiconfig	CR2W file	Fully parsed contains info about hud elements
- [ ] Grassmask	CR2W file	Missing a lot of stuff contains grassmasks
- [ ] Formation	CR2W file	Fully parsed contains (ai preset? behaviour?)
- [ ] Flyr	CR2W file	Fully parsed contains tree info
- [x] Env	CR2W file	Fully parsed contains enviroment info
- [x] Csv	Csv file	Can be opened in Microsoft Excel
- [x] Cellmap	CR2W file	Missing a lot of stuff contains Cellmap
- [x] Buffer	Unknown	Animation and model data

**Comment by Offline-R503B** [comment]
Suggestions : 
1 : Each icon could have a grey variant or we could do this during runtime with a grayscale effect from handycontrols to offer a "colorful" and a "grey" iconpack for the end user.
2 : Icon for the AssetBrowser itself and future tools.

**Comment by waitxd** [comment]
All icons have to be in vector format (SVG) for proper high DPI monitors support.

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Icons](https://trello.com/c/AeBmmDBu/63-icons)

**Comment by Offline-R503B** [comment]
This is almost done there are only about 18 icons left which PNDR is doing not going to check each box. 
Will close this once the last are in.

**Comment by Offline-R503B** [comment]
afaik all of these are in.
