### ISSUE TITLE
New logo, splash image etc.

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#304]
With the redesign we should rethink the overall look of the app we should have a new:
- [x] Icon for the actual program
- [x] Logo for the program
- [ ] Splash image when loading the app
- [ ] Couple header images atc we can use to show-off the app
- [ ] "Frame" where we can put a screenshot in the middle about hte app with some description

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logo,SplashImage Etc](https://trello.com/c/f7zmY8DP/73-logosplashimage-etc)

**Comment by Traderain** [comment]
We wont be renaming this project. That was for the discord, website etc

**Comment by ja-to** [comment]
Iconography and brand images for next-gen WolvenKit have been completed by homesick. Brand resources are available in the 2077 Discord.
