### ISSUE TITLE
Uncooking support for various file extensions

### ISSUE THREAD

**Issue by TheFusion21** [WolvenKit/WolvenKit#314]
- [ ] mi files
- [x] mlmask files
- [x] texarray files
- [x] cubemap files
- [x] envprobe files

**Comment by ja-to** [comment]
MI files cannot be uncooked because they are a proprietary REDengine format without a "raw" analogue. However we can now encode/decode them into json files with the WolvenKit 8.2 release. 

All of these files types are now "exportable"
