### ISSUE TITLE
Can't find a file from archivecashes

### ISSUE THREAD

**Issue by JediKnightChan** [WolvenKit/WolvenKit#318]
Hey, can't find file base\media\fluff\scenes\safe_n_sound\lipsync\en\safe_n_sound_01\jingle.anims,12556520970865043674 nor in the whole game folder neither in basegame 4 gamedata archive. What's wrong with it and what is the hash algorythm anyway?

**Comment by rfuzzo** [comment]
hashes are almost resolved, implemented a unused hash feature
