### ISSUE TITLE
Unit-test CR2W reading/writing

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/Wolvenkit#321]
Now that all REDEngine classes are included in the CP77.Cr2w.dll, we need to unit-test the parsing and writing. 
Unit-test should do the following:

- [x] **TestMethods for each file extension** (.ent, .xbm, .mi, .mesh etc). https://github.com/WolvenKit/CP77Tools/blob/ea64254f9329ec7250ca9a255973bb253804344c/CP77.MSTests/Cr2wUnitTest.cs#L61

- [ ] Each TestMethod should **loop through all memory-extracted files from all vanilla archives.** https://github.com/WolvenKit/CP77Tools/blob/ea64254f9329ec7250ca9a255973bb253804344c/CP77.MSTests/Cr2wUnitTest.cs#L69

- [x] Each TestMethod should have a **Reading-test**, which checks if the whole file can be read without error and if there are any "unknown bytes" left (bytes not parsed by the parser)

- [x] Each TestMethod should have a **Writing-test**, which checks if the whole file can be written without error and also it needs to check if the written file is binary-equal to the original file.

**Comment by Traderain** [comment]
Can we close this? @rfuzzo

**Comment by rfuzzo** [comment]
yes indeed.
