### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/Wolvenkit#324]
Currently we have a bunch of warnings which pollute building the project. It would make the whole building experience much nicer if they would get fixed.

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Warnings](https://trello.com/c/XVnfFBUU/114-fix-warnings)

**Comment by phrisk** [comment]
This is now fixed in the `dev` branch

> Note: `TreatWarningsAsErrors` has been switched on for **all** projects in the Wolvenkit solution. Introducing new warnings will now cause a build failure, which should guide contributors to fix them prior to PR/Merge 👍

**Comment by Traderain** [comment]
Great, I think this can be closed now. Btw you can write it in PRs: ``closes #324`` and it will close it automatically when accepted :)
