### ISSUE TITLE
Unsupported in Visual Studio 2019

### ISSUE THREAD

**Issue by ZucriyAmsuna** [WolvenKit/Wolvenkit#332]
**Description**
Visual Studio 2019 complains about the entire project being incompatible.

**To Reproduce**
1. Download the .zip of the entire project, and extract it.
2. Open Visual Studio 2019, and select the option to open a project or solution.
3. Choose either WolvenKit.sln or CP2077Tools.sln.
4. ???
5. Profit.

**Error Text**

> Unsupported
> This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
> For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
> 	 - CP77Tools, "C:\. . .\Wolvenkit-master\CP77Tools\CP77Tools.csproj"

**PC Specifications**
 - OS: Win10 Home, 64-bit
 - Visual Studio 2019, newly installed, .NET 5 newly installed (SDK 5.0.102 and ASP.NET Core Runtime 5.0.2)

**Comment by rfuzzo** [comment]
try opening the solution on the dev branch @ZucriyAmsuna

**Comment by ZucriyAmsuna** [comment]
@rfuzzo No change. Still incompatible.

This is a completely new install of Visual Studio 2019. I haven't really used it in six or so years, and I never opened someone else's project like this before. It's entirely possible I'm missing something, although I don't know why VS would make it harder to simply open another project that was made with the same version of the program.

Is there an extension I'm missing? I did not download any of those besides NuGetRecommender (apparently). How about a specific workload, like Universal Windows Platform development or .NET desktop development? It'll take forever, but I'll download a few of these now.

**Comment by rfuzzo** [comment]
you need NET5.0, but you can install this with the VS - get tools an features.

**Comment by ZucriyAmsuna** [comment]
I had to install the .NET desktop development workload, not just .NET 5.0.

Problem solved!
