### ISSUE TITLE
CR2W might be native 1-based indexing

### ISSUE THREAD

**Issue by DKingAlpha** [WolvenKit/Wolvenkit#333]
CR2W might be native 1-based indexing, and `CR2WTable.itemCount` could be `CR2WTable.maxItemIndex`.

I have been reimplementing CR2W parser in c++ referencing the CR2W part of wolvenkit, and I read the comment in your CR2W* structs. With some tests, I believe the reference indicies in CR2W are natively starting from 1.

Furthermore, `CR2WTable.itemCount` is not the item count. If it was, the dump of `[0, CR2WTable.itemCount)` would be
```
========== RADR Archive ID: lang_zh-cn_text ==========
--------- Extract compressed   : 1752735238780574 ---------
// type, file offset, some fields
[Name] 0000000000000173 , 0
[Name] 000000000000017B JsonResource, 7f0547ef
[Name] 0000000000000183 cookingPlatform, 96995708
[Name] 000000000000018B ECookingPlatform, 798ab6d7
[Name] 0000000000000193 PLATFORM_PC, 23ae7c92
[Name] 000000000000019B root, f0c467c5
[Name] 00000000000001A3 handle:ISerializable, 1414dca9
[Name] 00000000000001AB localizationPersistenceSubtitleEntries, dec4b351
[Name] 00000000000001B3 entries, 845a253
[Name] 00000000000001BB array:localizationPersistenceSubtitleEntry, 2ff393a8
[Name] 00000000000001C3 stringId, 2ad3d565
[Name] 00000000000001CB CRUID, f954c1a2
[Name] 00000000000001D3 femaleVariant, 4db8fbda
[Name] 00000000000001DB String, d4eb6238
[Name] 00000000000001E3 , 0                                    // overlap 1 ! should remove
[Property] 00000000000001E3 className: , propertyName:         // overlap 1 !
[Property] 00000000000001F3 className: JsonResource, propertyName:             // overlap 2 ! should remove
[Export]: 00000000000001F3 JsonResource#0                                      // overlap 2 !
[Export]: 000000000000020B localizationPersistenceSubtitleEntries#1
[Export]: 0000000000000223 #2
```

So the field of CR2WTable.itemCount can be easier to explain if named as maxItemIndex, which makes `[1, CR2WTable.maxItemIndex)`, trimming the last overlapping one. This method requires less error handling and index conversion in WolvenKit.

**Comment by rfuzzo** [comment]
interesting, thank you. is that the file hash? 1752735238780574

**Comment by DKingAlpha** [comment]
1752735238780574 is [RedArchiveEntry.id](https://github.com/DKingAlpha/ArchiveDump/blob/905d84a8ae40695b3e3021ec8643ff0d8b82dce2/ArchiveDump/RADR.hpp#L39)

**Comment by DKingAlpha** [comment]
@rfuzzo  my bad. it was my IteratableStructs implementation wrong. Nothing needs to be changed in WolvenKit, sorry.
I am going to close this issue.
