### ISSUE TITLE
Uncooking basegame_4_gamedata.archive with cp77tools not possible

### ISSUE THREAD

**Issue by Kintler11** [WolvenKit/Wolvenkit#338]
When trying to uncook basegame_4_gamedata.archive  w/o main arguments i.e (`uncook -p basegame_4_gamedata.archive `), it says "Failed to read cr2w file:".

Also when trying to uncook textures from basegame_4_gamedata.archive i.e (`uncook -p basegame_4_gamedata.archive --uext dds -w *.xbm`) it throws an unhandled exception. (View attachment)
![bug](https://user-images.githubusercontent.com/54033468/106900844-b0923e80-66ff-11eb-90e9-c251717828a4.png)

**Comment by stkterry** [comment]
I'm experiencing the same issue.  Crashes out right at 41-42% with the same errors.  Also failing to read cr2w files in the process of running.

**Comment by rfuzzo** [comment]
Thank you for the report. Will be fixed soon.

**Comment by rfuzzo** [comment]
This is fixed now here:
https://github.com/WolvenKit/CP77Tools/releases/tag/v.1.1.0.5
