### ISSUE TITLE
Cr2w Writing

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#340]
# CP77.cr2w Parsing + Writing

... ah shit, here we go again...

Complete writing of all cr2w serialized files with unknown bytes again:

## Failed Writes

- [x] inkatlas  | 4 fiels where names table has an incorrect hash for a string
- [x] mi | one file with a missing import
- [x] questphase | 1 file with broken enum
- [x] w2mesh 1 file with broken embedd
- [x] journal  1file
- [ ] json Not Run			
- [ ] morphtarget Not Run			
- [ ] scene Not Run			
- [ ] smartobjects Not Run			
- [ ] streamingsector Not Run			
- [ ] streamingsector_inplace Not Run	
- [ ] bin Failed Stale	53.4 Successful Writes: 111 / 126. 
- [ ] animgraph Failed Stale	3.9 Successful Writes: 194 / 403. 		
- [x] streamingworld Not Run			
- [x] traffic_persistent Not Run				
- [x] w2mi Not Run			
- [x] wem Not Run			
- [x] xbm Not Run			
- [x] behavior Failed Stale	11.6 Successful Writes: 200 / 201. 
- [x] mesh Failed Stale	21.6 Successful Writes: 0 / 90543. 
- [x] devices Failed Stale	24.5 Successful Writes: 1 / 4. 
- [x] cookedapp Failed Stale	51.3 Successful Writes: 0 / 4588. 
- [x] scenerid Failed Stale	4.1 Successful Writes: 661 / 666. 
- [x] effect Running	8.3 Successful Writes: 2934 / 2938. 
- [x] cooked_mlsetup Failed Stale	30.5 Successful Writes: 0 / 1.

**Comment by WopsS** [comment]
Base on PR https://github.com/WolvenKit/Wolvenkit/pull/362, the following table should apply now.

| Name                    | Succeeded | Difference | Expected to succeed |
|-------------------------|-----------|------------|---------------------|
| animgraph               | 340       | +146       | 403                 |
| bin                     | 47        | -65        | 126                 |
| cookedapp               | 0         | 0          | 4588                |
| ent                     | 15778     | -          | 16001               |
| hitrepresentation       | 0         | -          | 11                  |
| inkatlas                | 785       | 0          | 789                 |
| journal                 | 0         | 0          | 1                   |
| json                    | 58188     | -          | 58662               |
| lipmap                  | 0         | -          | 1                   |
| mesh                    | 0         | 0          | 90543               |
| mi                      | 6269      | 0          | 6270                |
| morphtarget             | 8         | -          | 127                 |
| physicalscene           | 0         | -          | 52                  |
| questphase              | 2565      | 0          | 2567                |
| scene                   | 4833      | -          | 6555                |
| smartobjects            | 99        | -          | 1084                |
| streamingsector         | 182       | -          | 18918               |
| streamingsector_inplace | 0         | -          | 2728                |
| w2mesh                  | 0         | -346       | 346                 |
| xbm                     | 41873     | -          | 42067               |

Tests not present in the tables meant they succeeded.

**Comment by rfuzzo** [comment]
is this resolved?
