### ISSUE TITLE
Export - uext option always select first element in enum

### ISSUE THREAD

**Issue by Akiway** [WolvenKit/WolvenKit#342]
## Describe the bug
Using CP77 Tools function Export, the uext option doesn't take in consideration the value passed. It always take the first element of the EUncookExtension.

### To Reproduce
1. Open the console and write `export -p <PATH_TO_XBM> --uext png`
2. It only generates a dds file.
3. In the code, switch lines 104 and 105 (WolvenKit.Common/DDS/TextconvWrapper.cs) so the tga is the first element in the enum list.
4. Execute again `export -p <PATH_TO_XBM> --uext png`
5. It generates a dds plus a tga.

It doesn't matter the value you put.
This value changement happens somewhere right after the arguments got parsed, the ConsoleFunctions.ExportTask already receive the wrong value.

### Expected behavior
The function should use the value passed by the user instead of rewriting it.

### Screenshots
Debug result at line 128 `rootCommand.InvokeAsync(parsed.ToArray()).Wait();`:
![image](https://user-images.githubusercontent.com/23312133/107156119-acbf2000-697c-11eb-9dbe-10bff1fd06fa.png)

And when the ExportTask is invoked:
![image](https://user-images.githubusercontent.com/23312133/107156231-6f0ec700-697d-11eb-9aff-ff05bf66a8b9.png)

That's how far I was able to debug this issue. Haven't found the exact line affecting this.

### System informations:
 - OS: Win10
 - CP77 Tools Version: current dev branch

**Comment by rfuzzo** [comment]
this is fixed in the 1.4.2
