### ISSUE TITLE
BundleExplorer overhaul

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#35]
- [x] Rename to asset browser
- [x] Different view modes
- [x] Add cache files,w3speech etc.
- [ ] Asset preview
  - [ ] 3d models
  - [ ] Sounds
  - [ ] Images
  - [ ] text files
  - [ ] movies
- [x] Convert it to be purely event based so it can be kept open and import stuff as you need it.

Cooking needs to be eleminated to implement this so texture.cache/soundspc.cache etc. writers need to be implemented for this.

**Comment by Traderain** [comment]
Asset preview could be achieved with [IPreviewHandler](https://msdn.microsoft.com/en-us/library/bb775315.aspx)

**Comment by rfuzzo** [comment]
Related requests:
-[] make asset browser dockable #100 
-[] enhance the search #76 
-[] Pagination of results

**Comment by rfuzzo** [comment]
outdated with Wolvenkit 8
