### ISSUE TITLE
Better CI

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#359]
Revamp the current CI:
- [x] Nightly releases with net 5 publish
- [x] public releases to the #latest githbub release on pushes to master
- [x] Check every commit in dev,master,PRs so they can be compiled and work
- [ ] #494

**Comment by rfuzzo** [comment]
go back to normal CI since hard-coded project references are moved to nugets with #447

**Comment by rfuzzo** [comment]
Here is my proposed CI

 ### On PR submitted
- [ ] check on dev
- [ ] check on main

 ### On PR merged
- [ ] draft release on main

### Scheduled
- [ ] Nightly builds on dev (daily)

### Manual trigger

- [ ] build nugets
- [ ] draft console release

**Comment by rfuzzo** [comment]
- [ ]  use nugets to speed up the CI
