### ISSUE TITLE
Unify TW3 and CP77 Consoles - incorrect User/Game Path.

### ISSUE THREAD

**Issue by Backporter** [WolvenKit/WolvenKit#360]
If the user does not have that game path or username this should fail,
solution:
dynamically get username(use Environment.UserName) and game path(from the registry or have the user point to it)
issues:
https://github.com/WolvenKit/Wolvenkit/blob/9f507a4871dc40c56d3223f399ed4bb341e4d543/WolvenKit.Console/Program.cs#L107
https://github.com/WolvenKit/Wolvenkit/blob/9f507a4871dc40c56d3223f399ed4bb341e4d543/WolvenKit.Console/Program.cs#L99

**Comment by rfuzzo** [comment]
Thank you! This is a good issue to think about if we should incorporate the old tw3 console into the new cp77 console.

**Comment by simon-brooke** [comment]
Given that different users will have bought the game via Steam, GOG or on DVD, and each of these options will mean a different file location, is the best thing to do to add configuration options for game locations, or to have a small configuration file with paths to search?

After all, most users will have the games in one of

1. C:\GOG Games\XXXX
2. C:\Program Files (x86)\GOG Galaxy\Games\XXXX
3. C:\Program Files (x86)\Steam\SteamApps\common\XXXX

and it wouldn't be a big deal to programmatically search these locations to locate installations (I notice I have three separate installations of 'The Witcher 3 Wild Hunt' on this machine!)

**Comment by Backporter** [comment]
(sorry for formatting... on mobile) its best to just get the paths from the registry or have the user select the path and store it inside the config, hardcoding paths are bout to cause issues, especially for advanced PC users that have it setup vastly different, those paths would still be broken for me because games are on another drive(E:/Steam/steamapps/common/), if its not added soon i could add it.

**Comment by Traderain** [comment]
This already works in the settings-wizard branch with crawling the registry.

**Comment by Backporter** [comment]
than in that case everything should be good to go 😃

**Comment by rfuzzo** [comment]
> This already works in the settings-wizard branch with crawling the registry.
> […](#)

TODO: We need to fix an issue with the crawler where users didn’t update the environmental variables and moved or deleted the game.

**Comment by Traderain** [comment]
> > This already works in the settings-wizard branch with crawling the registry.
> > […](#)
> 
> TODO: We need to fix an issue with the crawler where users didn’t update the environmental variables and moved or deleted the game.

Isn't it checked if the file exists? I may remember it incorrectly.

**Comment by rfuzzo** [comment]
> > > This already works in the settings-wizard branch with crawling the registry.
> > > […](#)
> > 
> > 
> > TODO: We need to fix an issue with the crawler where users didn’t update the environmental variables and moved or deleted the game.
> 
> Isn't it checked if the file exists? I may remember it incorrectly.

https://cdn.discordapp.com/attachments/717720094196760760/811866504927772692/unknown.png

this still breaks as far as I know
