### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#367]
Create an installer with wix for the project (https://wixtoolset.org/):
- Download .net if needed
- Install the program
- Associate files with wkit icon

**Comment by Offline-R503B** [comment]
WebView2 Distribution should happen here too.

**Comment by rfuzzo** [comment]
We also need to implement file opening with Wolvenkit for (3)

**Comment by Moonded** [comment]
Installer is being handled by Zathedeadgamer using installforge

**Comment by N00bWizard** [comment]
Installer is made and functions as intended. Will keep updating tho.

**Comment by N00bWizard** [comment]
Installer works as intended and is ready for deployment. Fixes & addtions will be added with time. 
please close issue. Thanks.

**Comment by Offline-R503B** [comment]
Closing issue : Installer functions well.

A future idea could be to swap to installshield.

Other than that we all guud
