### ISSUE TITLE
Compiled releases in .Net 5.0

### ISSUE THREAD

**Issue by MrGrymReaper** [WolvenKit/WolvenKit#374]
From what you are saying your getting close to basic Cyberpunk 2077 supporting release, as part of this or a future release. I also noticed that you are looking at cross platform support for the editing suite in case of future platform support by game.

As part of this is it possible please for the code to be compiled against the .Net Core version 5.0.3 (or above) as this is an open source form of .Net and is cross platform? Which should make it easier to work around, report bugs and contribute fixes developed for the framework as part of this project.

**Comment by rfuzzo** [comment]
Hi! Yes, we are using NET5 so it is theoretically cross-platform friendly.
However, the UI is in WPF, so it's windows-only.
BUT therer is a cross-platform console (which I already run on OSX and windows)

**Comment by MrGrymReaper** [comment]
Thanks for noting that. I have bought during last year a copy of Cyberpunk 2077 so have it myself. I'm looking to learn Lua so I can then script for Cyberpunk 2077. So are looking closely at your editor tool as I may become a modder (scripter). I'm not really a modeller and texturer artist its more coding, sometime story for me.

**Comment by rfuzzo** [comment]
WolvenKit.CLI is x-platform NET5
