### ISSUE TITLE
Apex files (redfur,redcloth)

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#43]
So in theory according to @erxv redfur files could be converted to apx. Since there are no unknownbytes in it. All we need to do is figure out that hashing algorythm used by apx so the files are recognized by apex and serialize the values to the weird xml apex recognizes. There needs to be an exporter and in importer as well.

- [x] Exporter
- [ ] Importer

**Comment by Traderain** [comment]
- This is what NVIDIA uses to serialize xml files: https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/3dfe2108cfab31ba3ee5527e217d0d8e99a51162/APEX_1.4/NvParameterized/src/XmlSerializer.cpp
- And this to read them: https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/3dfe2108cfab31ba3ee5527e217d0d8e99a51162/APEX_1.4/NvParameterized/src/XmlDeserializer.cpp

**Comment by SkacikPL** [comment]
wcc_lite has importer for apx and apb files (hairworks/cloth/destructibles) it's essentially all same file type but game forcibly expects apx for hair and apb for cloth/destructibles. Wcc import expected apb seems to be compatible with publicly available creation tools however apx seems to be expecting 1.0 hairworks type file which is not publicly available.

**Comment by Traderain** [comment]
@SkacikPL So you can import an apb file succesfullly with it?

**Comment by SkacikPL** [comment]
Yes, wcc won't throw a shit fit when you attempt to do that. Other question is whether it would work, given proper testing would require a brand new asset made from ground up with proper rigging and skinning which is something nobody tested.

As far as import _itself_ goes, you can import apb files with no issues using wcc_lite using currently available nvidia tools and plugins. It's only apx that can't be imported.

**Comment by Traderain** [comment]
Alright but the apx importing problem roots from that we don't have a version 1.0 file right?

**Comment by SkacikPL** [comment]
Yeah, apx is the XML variant of apex file type so technically it can't be _that_ hard to get it right or downgrade it to 1.0 compliant version. However there are no public samples so all that's left is guessing or blindly cutting down 1.1 and newer samples till it imports.

**Comment by Traderain** [comment]
So the file format of apb is defined here: https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/3dfe2108cfab31ba3ee5527e217d0d8e99a51162/APEX_1.4/NvParameterized/include/ApbDefinitions.h It can be used to make a converter.

**Comment by Traderain** [comment]
Apex format documentation: [Uploading PhysX_APEX_architecture_design_File Formats - engwiki.pdf…]()

**Comment by redwoodgroves** [comment]
Wondering if there is still being work done with hairworks files. Or if you still think it's going to be possible? Thanks

**Comment by SkacikPL** [comment]
Technically both are possible with more or less hassle.
IIRC WKit has nearly finalized APEX import but i don't think it's 100% ready yet.

**Comment by Traderain** [comment]
It kinda works but I got really fustrated with how the vertexes and such
work so I lost interest for a bit but I plan to finish it.

**Comment by redwoodgroves** [comment]
Well that is great news. Good luck. I'm very excited to make some hairs 😁

**Comment by Traderain** [comment]
Do we still need this?

**Comment by ja-to** [comment]
Fuzzo completely solved the apb/redcloth pipeline. Cloth files (apb) are imported by the Import Utility, and WolvenKit correctly builds collision cache and handles the cooked redcloth in the background. WolvenKit now also reads the collision cache from installed game and can export to raw apb.

Redfur can be handled correctly, but we don't have a tool to import/encode it. rmemr already has a really nice solution to encode redfur from apx format with an additional definition YML for all the in-game properties. I think his project is closed source, but it should be (according to Fuzzo) relatively easy to write a custom non-wcc import function.

**Comment by Traderain** [comment]
> Fuzzo completely solved the apb/redcloth pipeline. Cloth files (apb) are imported by the Import Utility, and WolvenKit correctly builds collision cache and handles the cooked redcloth in the background. WolvenKit now also reads the collision cache from installed game and can export to raw apb.
> 
> Redfur can be handled correctly, but we don't have a tool to import/encode it. rmemr already has a really nice solution to encode redfur from apx format with an additional definition YML for all the in-game properties. I think his project is closed source, but it should be (according to Fuzzo) relatively easy to write a custom non-wcc import function.

Hm that seems doable. a form where you select the apx+some fields for the aditional features.
