### ISSUE TITLE
Asset Browser stuck in infinite loading loop

### ISSUE THREAD

**Issue by DankRafft** [WolvenKit/WolvenKit#430]
**Describe the bug**
When creating a mod for TW3 asset browser being stuck in an infinite "Loading Game Files..." loop. I tried both the installer and the portable version, same problem.

**To Reproduce**
1. Install WolvenKit
2. Open WolvenKit
3. Create new TW3 project
4. Open asset browser

**Expected behavior**
Asset browser should list all game assets so I can import them into a project/mod.

**Screenshots**
![2021-04-12 (1)](https://user-images.githubusercontent.com/28791324/114417705-1c869c80-9bb2-11eb-9310-4b6889c0e5d6.png)
![2021-04-12 (2)](https://user-images.githubusercontent.com/28791324/114418499-da118f80-9bb2-11eb-8316-10b3ac747da2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20h2 b19042.906
 - Browser: Microsoft Edge v89.0.774.75

**Comment by rfuzzo** [comment]
this should be fixed in develop branch

**Comment by darman96** [comment]
Is there an ETA on when this should be fixed?

**Comment by TheMissionary** [comment]
0.8.0.1
Still at a standstill here.  Exactly as described by the OP.

**Comment by Traderain** [comment]
> 0.8.0.1
> Still at a standstill here. Exactly as described by the OP.

Gonna fix it this week, sorry for the delays.

**Comment by rfuzzo** [comment]
fixed
