### ISSUE TITLE
Audio compression issue (repacking .wem files)

### ISSUE THREAD

**Issue by magnesiumdreamz** [WolvenKit/WolvenKit#435]
Hi there, thanks for the Tools! I've been having issues compressing .wem files with this tool, such that when I compress more than 1 .wem files, my archives cannot decompress. I get exceptions with errors like "Buffer size doesn't match size in info table. 561285 vs 3067871". Furthermore, when I try to compress 1 file, which is able to decompress using CP77Tools, the file is unable to be loaded when I play CP77 and results in a crash. All of this makes me think that there is a problem with the compression of those file-types. I  am by no means an expert, but I'm going to try playing with oodle and I'll keep you posted if I find out some clues.

**Comment by rfuzzo** [comment]
fixed in latest versions
