### ISSUE TITLE
Texture Modding Notes

### ISSUE THREAD

**Issue by zoeymithra** [WolvenKit/WolvenKit#437]
During work on a mod, I switched to using a higher resolution textures.  Larger file sizes broke the beta pack function.

Summary 
Beta: 1.  Tried rebuilding the archive.
              Took a long long time, and packing also took a long time and produced a huge broken in game but slightly working file.   Brokenness was related seemingly to the normal texture map.  
         2.  Got the original normal map, and only changed the difuse map.  
              Rebuild took a shorter time but still forever, pack went into some kind of race condition that had to be canceled as was consuming 35gb of ram on the machine.

Stable Version.  
        1. Worked, was slower than with smaller files when making the large archives, but completed in regular time.  Archives were correct.
        2. Next day after reboot windows 10 thought the stable version was a villain.
            Fixed by remaking the program directory, and moving build files away.

No errors logged during any of the rebuild or pack operations. 

Long explanation (original notes.)
Using the beta, the process of rebuild/pack, basically went off and took much longer than expected, and created a huge archive that was broken in game, but loaded.  The Beta was able to create proper archives with smaller files, but pooped out when the files got big (final archive size was > 80mb.)  The current stable 1.0.5? was able to correctly build the archives.    In a seemingly unrelated incident, the next day after a reboot the stable version wouldn't run with a windows 10 access is denied.  Rebuilding the program directories from scratch and separating the build elements from the program directory tree fixed this.  I feel like because the beta program had been pointed at a build directory inside the stable version directory tree and created some kind of corrupted file, that it triggered windows 10  security access against the stable version.  Glean what you can from this report.  I know it isn't QA material.  I have some log files related the access failures on uncooks of .json files, and other such stuff, if they'd help, but again those are seemingly unrelated.  

Size, and performance notes: 
Anecdotally, when using RLE compression on some of the tga files, the beta seemed to go faster during the rebuild, but the pack operation went into some kind of race condition.  The compression reduced the overall size of the archive file by 30mb.  The correctly created archive is 83mb, the one created by the beta was over 270mb.  During another attempt the process it got into a state where it was quickly consuming 67% of the memory on a 64gb mem machine and increasing fast.  That attempt was canceled, so I don't know how big that archive would have been. It appeared to be a memory leak of some kind. Memory quickly went back to 12% after the program was killed, so it had been using 35gb of ram and gaining fast, like 1-2% per second at that point.  I feel like the total run time of the time it succeeded with a large broken file result was over a minute, when normally it completes in seconds, or at most 10 seconds. 

Hope this helps..

-Zoey

**Comment by ja-to** [comment]
The texture modding pipeline has been refactored with WolvenKit and is far more robust and reliable than this report on CP77 Tools. We do not currently support importing non-DDS files as XBM with WolvenKit 8.2, but this should be a separate issue on it's own.
