### ISSUE TITLE
Asset Browser overhaul

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#453]
Asset browser:

- [x] add multi-file select ("add all files of folder")
- [x] breadcrumb

think about uncooking support from the AB

**Comment by Offline-R503B** [comment]
- [ ] Context Menu (For files in Asset Browser.)
- [ ] Make "BreadCrumb" , Left Navigator and grid interact together. (If grid view is in a different folder the bc and navigator should be in the same folder )

**Comment by Offline-R503B** [comment]
- [ ] Properly refresh AB on project load.

**Comment by rfuzzo** [comment]
left to do:
