### ISSUE TITLE
Switching projects crashes

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#456]
something to do with syncfusion treegrid and dynamic data (possibly threading issues?)

**Comment by rfuzzo** [comment]
fixed in #450

**Comment by rfuzzo** [comment]
TODO
- [ ] retain expanded state across file delete/add

**Comment by Offline-R503B** [comment]
> TODO
> 
> * [ ]  retain expanded state across file delete/add

Open in separate issue so we can close this one ?
