### ISSUE TITLE
Settings Page Overhaul

### ISSUE THREAD

**Issue by Offline-R503B** [WolvenKit/WolvenKit#458]
I would like to overhaul the Settings page for more simplicity by using an SfAccordion and propertygrids.
End result would be to have only one settings page xaml file 👍 

UI tasks 
- [x] Convert tabs to accordion items.
- [x] Add property grids to accordion items.
- [x] Add items from all sub tab pages to their according propertygrid.
- [ ] Make settings more easy to access from the editor view.

Func Tasks

- [x]  Convert current logic to be used with new UI controls. 
- [x]  Add custom editor for paths. https://help.syncfusion.com/wpf/propertygrid/customeditor-support
- [ ]  Create models for PG's

**Comment by rfuzzo** [comment]
yes please!

**Comment by Traderain** [comment]
Assigned to @0matyesz0
