### ISSUE TITLE
Port old wiki from Github to Gitbooks.

### ISSUE THREAD

**Issue by Offline-R503B** [WolvenKit/WolvenKit#482]
As title,

The old github wiki should be copy pasted to the RED 3 wiki.
2 links on the old github wiki page redirecting to : 
1 : Wolvenkit (CP77) Wiki Mainpage
2 : Wolvenkit (TW3) (Legacy) (Direct link)  

## Expected result
No more Wiki on github.

**Comment by rfuzzo** [comment]
The github wiki is gone. here are the new links, I updated the wiki page

RED3 - The Witcher 3

    Wolvenkit 7: https://wiki.cybermods.net/wolvenkit-7/
    REDengine 3 research: https://wiki.cybermods.net/redengine3-research/

RED4 - Cyberpunk 2077

    Wolvenkit 8 + cp77tools: https://wiki.cybermods.net/wolvenkit
    REDengine 4 research: https://wiki.cybermods.net/redengine4-research/
