### ISSUE TITLE
Contextual fixes and QoL

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#491]
- [x] Toggle Previewing Files / Folders (sep toggle for each) in Ribbon
- [x] Add Context menu options from ab to ribbon?
- [x] Contextual Fix ?

**Comment by Offline-R503B** [comment]
- [ ] Fix audio player
- [ ] Homepage cleanup
- [ ] Bind app version
- [ ] Some slight cleanups
- [ ] Quickly bind Discord RPC To active Toolwindow (10 sec task)

**Comment by rfuzzo** [comment]
Update major versions from 0.8.2 —> 8.2.0

**Comment by Offline-R503B** [comment]
- [ ]  Disable ribbon items

**Comment by Offline-R503B** [comment]
- [ ] material depot stuff

**Comment by Offline-R503B** [comment]
- [ ] context menu project explorer

**Comment by Offline-R503B** [comment]
- [ ] Fix Multiple material depot dialogs

**Comment by Offline-R503B** [comment]
- [ ] add some raw icons

**Comment by Offline-R503B** [comment]
- [ ]  on first setup the paths don't update

**Comment by Offline-R503B** [comment]
- [ ] oodle sometimes doesn't copy for users, (Suggestion : after setting path 1st time check again if oodle present if not use set path to get oodle)

**Comment by Offline-R503B** [comment]
- [ ] Fix Video player if possible before release..

**Comment by Offline-R503B** [comment]
- [ ] remove old video player + dlls
- [ ] remove Naudio DLL's + Code
- [ ] add assetbrowser preview for fixed videoplayer

**Comment by Offline-R503B** [comment]
- [ ] Fix I/E initial height

**Comment by Offline-R503B** [comment]
Done
