### ISSUE TITLE
Add REDScript Syntax Highlighting.

### ISSUE THREAD

**Issue by Offline-R503B** [WolvenKit/WolvenKit#517]
For the code editor we need to use :

https://help.syncfusion.com/wpf/syntax-editor/language-support/custom-language-support
OR simpler described in : 
https://www.syncfusion.com/blogs/post/wpf-create-syntax-highlighter-in-5-minutes.aspx

Mostly I'd love some help with creating the Lexem Collection

**Comment by flibX0r** [comment]
Happy to jump on this as previously discussed

**Comment by jackhumbert** [comment]
I'm not sure how it'll end up being implemented here, but I customized a .swift tmLang for VS Code that may be able to be used/converted: https://github.com/jackhumbert/redscript-syntax-highlighting
