### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by Offline-R503B** [WolvenKit/WolvenKit#518]
To add the Code Editor we need to do the following :

- [ ] Clean up the UI 
- [ ] Resolve #517 
- [ ] Save as .red etc
- [ ] Testing

WIP Issue more will be added.

**Comment by rfuzzo** [comment]
Add a new File View like in VS with
- redscript file
- tweak file
- cr2w file

![image](https://user-images.githubusercontent.com/37657287/130248610-2734e9a8-e760-4d8c-a619-2fe30012cfa9.png)

**Comment by rfuzzo** [comment]
moved to #538
