### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by enumag** [WolvenKit/WolvenKit#547]
I installed the software and would like to use it. Unfortunately when it starts after a few seconds I see a window with some menus and such - presumably the standard interface of the software, but right after that it crashes completely and disappears. No error is shown. Is there some log file I could send you to figure out what's wrong?

OS: Windows 10
WolvenKit Version 8.2.2.0

**Comment by rfuzzo** [comment]
Do you have WebView2 installed? If no, this can lead to a silent crash on startup.

This issue is fixed in the upcoming version (tracked here:  #526 )

**Comment by enumag** [comment]
Yeah that's most likely it. Thanks!

**Comment by rfuzzo** [comment]
Thanks, I opened a new issue (#548 ) because I noticed that this problem should be better handled. Thank you for your report.
