### ISSUE TITLE
Mesh preview does not work with cyrillic characters username

### ISSUE THREAD

**Issue by StoneOfStones** [WolvenKit/WolvenKit#557]
**Describe the bug**
Title explanes.

**To Reproduce**
Create temporary guest user with username Пользователь and try to preview any mesh as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/3298683/130140184-125cbe7b-431d-47ae-9b2d-53d6446325c7.png)

**Desktop (please complete the following information):**
WolvenKit 8.2.2.0
Game version GOG 1.3

**Comment by HitmanHimself** [comment]
It could happen files aren't extracting properly If u have used wkit before patch 1.3 dropped, you may need to delete archive_cache.bin from appdata/roaming/redmodding/wolvenkit. Try that first?

**Comment by Traderain** [comment]
Needs to be tested

**Comment by map788** [comment]
https://github.com/WolvenKit/WolvenKit/discussions/700
I think link to this
