### ISSUE TITLE
Wolvenkit Extensions/Workloads

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#560]
A simple Visual-Studio-like workload logic: Choose from a list of plugins to install locally: 

Examples could be: 
- Red4Ext
- TWeakDbExt (needed when adding a tweak_delta files)
- Redscript (needed when adding .redscript files)
- CET
- ???

![image](https://user-images.githubusercontent.com/37657287/130296751-552f095c-0165-40e5-ad97-351bd9d01e39.png)

**Comment by Telpe** [comment]
With issue #316 in mind, An option could be creating a "default apps" list, for the file types.
Semi OS independent. 
If integrated editor app is build, it can be the default.

Ex. When opening a .lua file, a, perhaps themed, new window open, with the app of user choice or default. 

This suggestion may or may not be the same issue as OP, perhaps "plugins" and "external editors" could be useful to have at the same time.

**Comment by rfuzzo** [comment]
@Telpe currently, non-redengine files (like .lua) are opened externally defaulting to the OS-default. So if you set to open .lua files with VS Code, double-clicking on a .lua file in Wolvenkit also opens it in VS Code.

**Comment by rfuzzo** [comment]
implemented in v8.5
