### ISSUE TITLE
WolvenKit.CLI uncook task generates BMP and PNG files with incorrect filetypes (i.e. TIFF)

### ISSUE THREAD

**Issue by gammaparticle** [WolvenKit/WolvenKit#563]
**Describe the bug**
Uncooking game archives with WolvenKit.CLI produce:

- BMP files that have TIFF filetypes (by default, no --uext specified)
- PNG files that have TIFF filetypes (when --uext png is specified).

**To Reproduce**
As an example, uncook basegame_4_gamedata.archive:

1. To produce BMP files, execute:

`./WolvenKit.CLI.exe uncook -p "D:\Steam\steamapps\common\Cyberpunk 2077\archive\pc\content\basegame_4_gamedata.archive" -o "D:\CyberPunk4GameData"`

2. To produce PNG files, execute:

`./WolvenKit.CLI.exe uncook -p "D:\Steam\steamapps\common\Cyberpunk 2077\archive\pc\content\basegame_4_gamedata.archive" --uext png -o "D:\CyberPunk4GameData"`

3. Check filetype of .bmp and .png files in D:\CyberPunk4GameData\base by opening a Git Bash Shell (this is one way to confirm the bug - you can use other methods.  Git Bash Shell for Windows can be downloaded from https://git-scm.com/download/win).  
Run the command `file` against the a .bmp and .png file to check filetype:

![WKUncookbug](https://user-images.githubusercontent.com/575507/130347278-25bc03e5-a8bd-4dff-87af-67c67da100c7.png)

**Expected behavior**
To test for the correct filetype:

-  Executing `file` on .bmp files should produce: `PC bitmap, Windows 98/2000 and newer format, 512 x 512 x 32` (or similar bitmap description)
-  Executing `file` on .png files should produce: `PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced`

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (21H1)
 - Browser: Firefox
 - Version: 91.0.1

Note:  There is a PR (https://github.com/rfuzzo/DirectXTexSharp/pull/4) containing a potential fix for DirectXTexSharp:   
A new dll for WolvenKit should hopefully fix the bug here as well.

**Comment by HitmanHimself** [comment]
We are known of the issue, we'll try to fix it asap

**Comment by gammaparticle** [comment]
Yes, I originally brought up the issue on Discord.
I have a PR open in DirectXTexSharp (https://github.com/rfuzzo/DirectXTexSharp/pull/4) which contains a fix and is ready to merge.

This PR also fixes numerous compiler warnings that were introduced in the WolvenKit build from DirectXTexSharp sources which are now included as a submodule:
![Wkit_compiler_warnings](https://user-images.githubusercontent.com/575507/131348953-bb0bd76f-ba3a-45f0-8827-e1d5acff218e.png)

**Comment by rfuzzo** [comment]
thank you this is now merged. sorry for the delay

**Comment by gammaparticle** [comment]
No problem! ty!

Also, I had to execute `git submodule update --remote` to pull in the new submodule changes in WKit and rebuilt to test.

**Comment by gammaparticle** [comment]
Confirmed fix.
