### ISSUE TITLE
Crash to Desktop when generating material-repository

### ISSUE THREAD

**Issue by Jazzima** [WolvenKit/WolvenKit#568]
**Describe the bug**
WolvenKit stops responding and crashes to desktop after starting the Material Repository Generator.

**To Reproduce**
1. Open an existing project or create a new one.
2. Click on Options - Material-Repository Settings
3. Game Archives Path "C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\Cyberpunk2077.exe" and Materials Repository Path "C:\Users\jazz\Documents\Wolven\Mats"
4. Click Generate

**Expected behavior**
Materials Repository to be created.

**Attempts to fix/work around**
I've done the following to try and get it to work with no success.

1. Running as administrator.
2. Running in SafeMode.
3. Clean install of the game, Wolven Kit v8.2.2.0, .NET5, WebView2.
4. Manually copying oo2ext_7_win64.dll to WolvenKit installation folder.
5. The same as above using the 8.3.0-nightly.2021-08-22 Build.
6. The same as above on two seperate computers.

**Log**
The Crashreport text file generated in the log folder doesn't contain any information/blank document.

`10:50:10:596 => [INFO] [Orchestra.Services.ShellService] [7] Checking if software was correctly closed previously
10:50:11:607 => [INFO] [WolvenKit.Functionality.Services.ApplicationInitializationService] [7] Improving performance
10:50:13:634 => [INFO] [Orchestra.Services.ShellService] [7] Confirming that application was started successfully
10:50:21:854 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Initializing Discord RPC API
10:50:21:859 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Initializing Github API
10:50:21:868 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Calling base.OnStartup
10:50:21:868 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Initializing NodeNetwork.
10:50:21:868 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Initializing Notifications.
10:50:21:868 => [INFO] [WolvenKit.Functionality.Helpers.StaticReferences] [4] Check for new updates
10:52:45:266 => [INFO] [Orchestra.Services.RecentlyUsedItemsService] [16] Saving recently used items to 'C:\Users\jazz\AppData\Roaming\WolvenKit\WolvenKit\recentlyused.xml'
10:52:45:421 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [16] Loading archive Manager ... 
10:52:49:970 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [9] Finished loading archive manager.
10:53:55:671 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .hp: Found 83 entries to uncook
10:53:55:732 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .hp: Unbundled 83 files.
10:53:55:732 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .fp: Found 28 entries to uncook
10:53:55:768 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .fp: Unbundled 28 files.
10:53:55:768 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .sp: Found 3 entries to uncook
10:53:55:771 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .sp: Unbundled 3 files.
10:53:55:771 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .mltemplate: Found 383 entries to uncook
10:53:55:900 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .mltemplate: Unbundled 383 files.
10:53:55:901 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .w2mi: Found 362 entries to uncook
10:53:55:977 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .w2mi: Unbundled 362 files.
10:53:55:977 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .texarray: Found 7 entries to uncook
10:53:55:987 => [INFO] [WolvenKit.Common.Services.CatelLoggerService] [32] .texarray: Unbundled 7 files.
10:53:55:988 => [WARNING] [WolvenKit.Common.Services.CatelLoggerService] [32] .mlsetup: Found 13553 entries to uncook
`

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installed on	‎14/‎10/‎2020
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by rfuzzo** [comment]
thank you for your report. we are working on a release candidate for patch 1.3. 

In the meantime, you can check out our nightly builds here: https://github.com/WolvenKit/WolvenKit-nightly-releases

and: you don't need to create the material repository manually (unless you want to), because the depot is meant to be slowly filled over time whenever you export a mesh.
