### ISSUE TITLE
Crash after launch if it can't connect online

### ISSUE THREAD

**Issue by chocmake** [WolvenKit/WolvenKit#569]
**Describe the bug**
WolvenKit crashes about 5-10 seconds after launch, seemingly if it can't connect online. About a second after displaying the 'Featured showcase' widget.

**To Reproduce**
1. Download the WolvenKit zipped (portable) version from the latest release (v8.2.2.0 at the time of writing) and unzip to a directory with write permissions, as per the [steps](https://wiki.redmodding.org/wolvenkit/getting-started/installation) on the wiki (my game install isn't in a directory that requires admin write privileges, either, fwiw).
2. Install the .NET and WebView2 dependencies. Restarted Windows just to be sure though this doesn't seem to be necessary.
3. Prevent WolvenKit from accessing the internet (in my case via firewall restriction as I normally do for various programs, though I also wasn't connected online).
4. Launch WolvenKit.

**Expected behavior**
That it wouldn't crash after startup when offline or when prevented via firewall restriction.

**Desktop (please complete the following information):**
 - OS: W10 Pro (2004)

**Comment by rfuzzo** [comment]
This bug is already fixed in the latest beta release and will be fixed int the next release.

**Comment by chocmake** [comment]
Just tested 8.3.0-nightly.2021-08-25 and still encountered this however I've it seems to only affects the program when the system is offline.

If I launch when the system is connected online (even if there's a firewall rule applied to the binary) WolvenKit manages to the load the Youtube video in the 'Featured Showcase' and doesn't crash. However if I disconnect from the internet entirely the crash shortly after crash is reproducible each launch.

**Comment by rfuzzo** [comment]
Thanks 😑 I thought I fixed the offline crash… I’ll have a look again

**Comment by chocmake** [comment]
> This is fixed in the latest master build - I tested it.

Do you mean the existing v8.2.2.0 or the new 8.3.0-nightly.2021-08-27? As I tested the latter version to the same result (my process was delete the program directory and Roaming profile directory as per wiki).

Also disabled the firewall rules with the same result (system offline = crash, system online = works fine).

Is there something else that may be causing this discrepancy of testing results? I only run default Windows Defender in terms of say AV.

**Comment by rfuzzo** [comment]
I tested it on the latest 8.3 nightlies, yes. (and on the pre-release) I went offline, opened wkit and it started correctly - with the browser-elements all showing "you're not connected to the internet".

maybe this has nothing to do with being offline?

**Comment by chocmake** [comment]
These were the exact dependencies I installed, from the pages pointed to in Releases, fwiw. Not sure what else I could look for.

- WebView 2 - Evergreen Standalone Installer (x64) - `MicrosoftEdgeWebView2RuntimeInstallerX64.exe`
- .NET Desktop Runtime 5.0.9 (x64) - `windowsdesktop-runtime-5.0.9-win-x64.exe`

**Comment by rfuzzo** [comment]
hmm, I don't really know. Newer nightlies install webview2 automatically if not present, so that's not the problem. The only thing needed is the .NET Runtime 5.0.9, but you have the correct one too...
