### ISSUE TITLE
Quest Graph Editor

### ISSUE THREAD

**Issue by extract** [WolvenKit/WolvenKit#575]
Add quest graph viewer/editor. I think it was part of W3 WolvenKit but I have not used it.

I find it a bit tricky to edit quests with the lack of proper editor. Currently, only chunks are printed.

Thank you

**Comment by rfuzzo** [comment]
yes.

**Comment by rfuzzo** [comment]
In all seriousness: we don't have an issue tracking this. So this is good.

**Comment by Traderain** [comment]
Actually #4

**Comment by HitmanHimself** [comment]
we need a general purpose graph editor anyways, there are more file formats that could take advantage of such an editor

**Comment by extract** [comment]
Yeah, actually the more I looked into the structure I see that a lot of files have that type of node/graph structure. Just a beginners misunderstanding on my part.

**Comment by rfuzzo** [comment]
closing as duplicate of #4
