### ISSUE TITLE
Uncooking archives, namely basegame_4_gamedata.archive and basegame_4_appearance.archive, with WolvenKit.CLI result in errors

### ISSUE THREAD

**Issue by gammaparticle** [WolvenKit/WolvenKit#581]
**Describe the bug**
1. Uncooking `basegame_4_gamedata.archive` results in multiple errors of the following types:

- .NET number values such as positive and negative infinity cannot be written as valid JSON.
- Buffer[0] ByteLength: 0 must be greater or equal to 1
- Accessor[6] memory: Value[#####] is out of bounds #####. (Parameter 'memory')

2. Uncooking `basegame_4_appearance.archive` results in multiple errors of the following types:

-   .NET number values such as positive and negative infinity cannot be written as valid JSON.
- <absolute filename of *.morphtarget> And unexpected error occured while uncooking: Value cannot be null. (Parameter 'path1')
- Object reference not set to an instance of an object.

**To Reproduce**
To reproduce [1] above, execute: 
` ./WolvenKit.CLI.exe uncook <chosen (optional) extention)> -p "D:\SteamLibrary\steamapps\common\Cyberpunk 2077\archive\pc\content\basegame_4_gamedata.archive" -o <your output directory>`

To reproduce [2] above, execute: 
`./WolvenKit.CLI.exe uncook <chosen (optional) extention)> -p "D:\SteamLibrary\steamapps\common\Cyberpunk 2077\archive\pc\content\basegame_4_appearance.archive" -o <your output directory>`

**Expected behavior**
No Error lines of output should occur during the uncook process of WolvenKit.CLI.

**Screenshots**
[1]
![uncook-basegame-4-gamedata-errors](https://user-images.githubusercontent.com/575507/132106938-01cf8579-b6c7-48fa-b9f8-72c9c8085298.png)

[2]
![appearance-archive-errors](https://user-images.githubusercontent.com/575507/132106957-a079f072-0921-4809-96cd-cfc0a044c040.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 
 - Browser: Firefox
 - Version: 21H1

**Comment by gammaparticle** [comment]
Updating issue status as I go before creating PR.

Began with basegame-4-appearance.archive errors [2] since uncooking this resulted in the most errors: 

The multiple path1 errors when uncooking the basegame-4-appearance.archive were caused by a null modfolderpath passed in to a call to Path.Combine() which threw a System.ArgumentNullExcpetion. Replacing the upstream parameter which contained the correct modpath resolved those errors, cutting them overall to a remaining few.

![path1bug-appearance-archive-fix](https://user-images.githubusercontent.com/575507/132127331-385c1711-84b7-4f08-9569-11b140b5a872.png)


Continuing with the rest of the fixes.

**Comment by rfuzzo** [comment]
that's great! in general, we probably need to find a way in the future to better separate the Console commands from the app commands? e.g. never try passing modfolderpath or the likes to the console which doesn't know the concept of a local mod project.

**Comment by gammaparticle** [comment]
Ah. Good point, will definitely keep this in mind.

**Comment by gammaparticle** [comment]
Created PR #584 for the fix of error "Value cannot be null. (Parameter 'path1')".

Had originally planned a PR with a group of fixes, but that could result in significant delays and I didn't want to sit on this fix while resolving others.  

Best to roll them out one at time when completed.

**Comment by gammaparticle** [comment]
Fixed another error that was introduced during the latest updates:

![EndOfStreamException-appearance-archive](https://user-images.githubusercontent.com/575507/132287243-d0941790-6753-4a86-aa73-8f1243268f20.png)

In ContainRawTargets(), the exception is thrown with read attempts past the end of diffsbuffer and mappingbuffer.
End-of-stream checks have been added for these two buffers.

PR #584 has been updated to include these commits.

**Comment by rfuzzo** [comment]
great stuff, should we close this or do you want to keep it open?

**Comment by HitmanHimself** [comment]
mesh errors are remaining

**Comment by gammaparticle** [comment]
As Hitman said, we still need to resolve the remaining errors.

**Comment by gammaparticle** [comment]
Update: I have a possible solution that I'm currently testing on .mesh files that were unable to export to .GLB due to invalid values passed in to the JSON chunk of the GLB file which in turn resulted in `System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON` errors.

![JSON-GLB](https://user-images.githubusercontent.com/575507/132567080-308af63f-002d-4b65-849b-028271e344a7.png)

**Comment by HitmanHimself** [comment]
a lot of meshes are there in gamefiles which are broken(like NaN normals tangents uv coordinates etc.) have been fixed (recalculated) by gltf library using TryFix Export some others cannot be fixed where face indices get out of bounds for read vertice (unless we try some other methods with buffer offset calculation and indices max value to get vertex count, which is not ideal and fuzzy so we shall leave those meshes as it is considering them to broken and unfixable)  
![unknown](https://user-images.githubusercontent.com/76775663/132866404-36ce2894-188e-4d12-91e4-e47edd9c0e16.png)

**Comment by HitmanHimself** [comment]
for exporting skinned morphtargets i grabbed the boneNames from baseMesh of the morphtarget however there are some morphtargets which have more or less bonePositions in rendBlob with wrong order of bones compared to the base mesh so we don't have a proper way to find the bone names yet. also the rendblob in morphtarget isn't always same as the rendblob in baseMesh(which is the very first reason i discovered the problem of bad boneNames etc.)

**Comment by gammaparticle** [comment]
I was able to resolve the System.ArgumentException error (due to attempts to write -infinity or (+)infinity as valid JSON to the .glb) for (at least) the following meshes so that a .glb file was generated:  

- base\vehicles\standard\v_standard2_archer_hella\entities\meshes\v_standard2_archer_hella__int01_v_console_01.mesh
- base\characters\garment\npc_blob\meshes\npc_blob_districts_02.mesh
- base\characters\garment\npc_blob\meshes\npc_blob_districts_02_short.mesh
- base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.mesh
- base\vehicles\sport\v_sport1_quadra_turbo\entities\meshes\v_sport1_quadra_turbo__int01_concole_b_01.mesh
- base\characters\garment\light_crowd\torso\t1_004_tshirt__longsleeve_lc\t1_004_wa_tshirt__tanktop_lc.mesh

The resulting .glb files don't appear to be broken except for one which displays only the bottom half of the jacket: 

- base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.glb


I was unable to resolve the System.ArgumentException (no .glb files were generated) for the .mesh files below:

- base\characters\main_npc\silverhand\t2_001_ma_jacket__silverhand_alternative_cloth_proxy.mesh
- base\characters\main_npc\steve\t2_002_ma_jacket__steve_cloth_proxy.mesh
- base\characters\main_npc\hanako\t2_001_wa_jacket__hanako_cloth_proxy.mesh
- base\characters\main_npc\evelyn\t2_001_wa_jacket__evelyn_coat_cloth_proxy.mesh

The following shows the bottom portion of remaining errors from uncooking the `basegame_4_appearance.archive`:

![GLBExport](https://user-images.githubusercontent.com/575507/132978127-e08c761d-962c-48af-9602-f43dace4561b.png)
 
Creating a PR.

**Comment by HitmanHimself** [comment]
> I was able to resolve the System.ArgumentException error (due to attempts to write -infinity or (+)infinity as valid JSON to the .glb) for (at least) the following meshes so that a .glb file was generated:
> 
> * base\vehicles\standard\v_standard2_archer_hella\entities\meshes\v_standard2_archer_hella__int01_v_console_01.mesh
> * base\characters\garment\npc_blob\meshes\npc_blob_districts_02.mesh
> * base\characters\garment\npc_blob\meshes\npc_blob_districts_02_short.mesh
> * base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.mesh
> * base\vehicles\sport\v_sport1_quadra_turbo\entities\meshes\v_sport1_quadra_turbo__int01_concole_b_01.mesh
> * base\characters\garment\light_crowd\torso\t1_004_tshirt__longsleeve_lc\t1_004_wa_tshirt__tanktop_lc.mesh
> 
> The resulting .glb files don't appear to be broken except for one which displays only the bottom half of the jacket:
> 
> * base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.glb
> 
> I was unable to resolve the System.ArgumentException (no .glb files were generated) for the .mesh files below:
> 
> * base\characters\main_npc\silverhand\t2_001_ma_jacket__silverhand_alternative_cloth_proxy.mesh
> * base\characters\main_npc\steve\t2_002_ma_jacket__steve_cloth_proxy.mesh
> * base\characters\main_npc\hanako\t2_001_wa_jacket__hanako_cloth_proxy.mesh
> * base\characters\main_npc\evelyn\t2_001_wa_jacket__evelyn_coat_cloth_proxy.mesh
> 
> The following shows the bottom portion of remaining errors from uncooking the `basegame_4_appearance.archive`:
> 
> ![GLBExport](https://user-images.githubusercontent.com/575507/132978127-e08c761d-962c-48af-9602-f43dace4561b.png)
> 
> Creating a PR.

i have fixed them

**Comment by gammaparticle** [comment]
> 
> 
> > I was able to resolve the System.ArgumentException error (due to attempts to write -infinity or (+)infinity as valid JSON to the .glb) for (at least) the following meshes so that a .glb file was generated:
> > 
> > * base\vehicles\standard\v_standard2_archer_hella\entities\meshes\v_standard2_archer_hella__int01_v_console_01.mesh
> > * base\characters\garment\npc_blob\meshes\npc_blob_districts_02.mesh
> > * base\characters\garment\npc_blob\meshes\npc_blob_districts_02_short.mesh
> > * base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.mesh
> > * base\vehicles\sport\v_sport1_quadra_turbo\entities\meshes\v_sport1_quadra_turbo__int01_concole_b_01.mesh
> > * base\characters\garment\light_crowd\torso\t1_004_tshirt__longsleeve_lc\t1_004_wa_tshirt__tanktop_lc.mesh
> > 
> > The resulting .glb files don't appear to be broken except for one which displays only the bottom half of the jacket:
> > 
> > * base\characters\main_npc\maman_brigitte\t2_001_wa_jacket__maman_brigitte_cloth_proxy.glb
> > 
> > I was unable to resolve the System.ArgumentException (no .glb files were generated) for the .mesh files below:
> > 
> > * base\characters\main_npc\silverhand\t2_001_ma_jacket__silverhand_alternative_cloth_proxy.mesh
> > * base\characters\main_npc\steve\t2_002_ma_jacket__steve_cloth_proxy.mesh
> > * base\characters\main_npc\hanako\t2_001_wa_jacket__hanako_cloth_proxy.mesh
> > * base\characters\main_npc\evelyn\t2_001_wa_jacket__evelyn_coat_cloth_proxy.mesh
> > 
> > The following shows the bottom portion of remaining errors from uncooking the `basegame_4_appearance.archive`:
> > ![GLBExport](https://user-images.githubusercontent.com/575507/132978127-e08c761d-962c-48af-9602-f43dace4561b.png)
> > Creating a PR.
> 
> i have fixed them

Are saying you fixed the remaining four errors? or all 10 specified above (I fixed all in my branch except for the remaining 4).

And if so, did you fix the errors in `basegame_4_gamedata.archive`?  

If all of the above are fixed, let me know and I can close the issue.

**Comment by HitmanHimself** [comment]
i ran unit test for all the archives and i have specified some cannot be fixed(actually can be but its a bad way to do it inviting other problems) https://github.com/WolvenKit/WolvenKit/issues/581#issuecomment-916932045
![unkown](https://cdn.discordapp.com/attachments/717720094196760760/885880778792251443/unknown.png)

**Comment by gammaparticle** [comment]
Yes, I saw the comment, but wasn't sure if it was referring to the specific errors (-inf and +inf only) in the appearance archive (the focus of this issue). 

My partial fix is OBE.

Closing this issue.
