### ISSUE TITLE
Folder Search CTD

### ISSUE THREAD

**Issue by Walrus159** [WolvenKit/WolvenKit#588]
Using the folder search function causes WK to crash. File search works fine.

![image](https://user-images.githubusercontent.com/90599995/133043316-9549eb30-0d1e-4f57-af3d-fc6c049c9568.png)

first noticed: Wolven Kit 8.3.2
last tested: WolvenKit-8.3.3-nightly.2021-09-10

OS and other things that I doubt actually matter...
Windows 10 home x64 21H1
Both english and cyrillic language packs installed... Наверно поэтому? Гыыыы
I7 7700/h270 chipset/16 GB DDR3 dual channel/GTX 1070

**Comment by Traderain** [comment]
Needs testing
