### ISSUE TITLE
Latest version that support Witcher 3

### ISSUE THREAD

**Issue by Felina-Lain** [WolvenKit/WolvenKit#590]
Hello

I was wondering if the latest stable version available for download (8.3.2) still support the Witcher 3, because when I start it, it ask for cyberpunk.exe and I just can't get it to take Witcher 3 files

If it doesn't, do you remember which was the last release you had which accepted Witcher 3 files?

Thank you very much, have a nice day

**Comment by Felina-Lain** [comment]
Quite alright, thanks for answering!
I had the nexus version, but I wanted to know if it was the latest, in case there was a better one
Thanks for the fork too, I'll keep an eye on it! ^^

**Comment by rfuzzo** [comment]
nexus isn't the latest. ther link I gave you is one version higher (0.7) nexus is (0.6)

**Comment by Traderain** [comment]
Working on it here: https://github.com/WolvenKit/WolvenKit-7
