### ISSUE TITLE
xml menu creator gui

### ISSUE THREAD

**Issue by erxv** [WolvenKit/WolvenKit#6]
GUI for generating menus.

**Comment by Traderain** [comment]
Closing for now. Can be reopened if we want to make a fancy ui for it.

**Comment by Traderain** [comment]
This should be upgraded so people can actually use it (its pretty black magic to use atm):
 - have a proper display of the menu
 - make it create strings and such on demand
 - make it more failsafe, its pretty easy to break at the moment

**Comment by Traderain** [comment]
So the way this currenty works is horrible:
![image](https://user-images.githubusercontent.com/6411732/44915511-6721b600-ad33-11e8-9f3f-fa2a657f7cc9.png)
Something like this should be sufficient:
![image](https://user-images.githubusercontent.com/6411732/44915640-c41d6c00-ad33-11e8-9d6a-b680fea5c770.png)
Everything should be assembled with some clickable buttons or something so its not cacncer.
We need to upgrade the string thing so its much easier here or at least incorporate the string picker.
