### ISSUE TITLE
Proposal for small changes to mlmask/masklist

### ISSUE THREAD

**Issue by ja-to** [WolvenKit/WolvenKit#602]
**Issue:** WolvenKit supports mlmask I/O, but the feature is somewhat hidden.

**Cause:** When exporting mlmask files, the array of internal images can be dumped to a series of Raw textures, which is very intuitive. However, to re-import the textures back into a packed mlmask, use of the custom **masklist** format is required. While there's no issue technically speaking, the only way WolvenKit users will ever learn about this feature is from the Wiki.

**Proposal:** When exporting mlmask files, I believe WolvenKit should create a **masklist** file nested directly with the Raw texture array. With this proposal implemented, the Import/Export grid would automatically populate with the masklist file, which is significantly more intuitive.

**Benefits:**
1. Turnaround time for Import/Export with mlmask/mask list is reduced to virtually 0 seconds.
2. Significant UX gains. It's currently impossible to import new mlmasks without finding the specific Wiki section.

**Additional Thoughts:**
Currently the masklist file uses absolute paths, which has some distinct benefits. However, I believe we should at least consider using texture paths relative to the masklist file. Masklist and their Raw textures would be significantly more robust and easier to handle within and between mod projects.

Information about mlmask files is available here on our Wiki:
https://wiki.redmodding.org/wolvenkit/wolvenkit-app/editor/import-export/textures#mlmask

**Comment by rfuzzo** [comment]
yes great idea!
