### ISSUE TITLE
Font/UI scaling

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#604]
**Is your feature request related to a problem? Please describe.**
First World Problems incarnate: On my 4k monitor, the font of WolvenKit is all but unreadable.

**Describe the solution you'd like**
UI scaling! It would be grand to have it configurable via settings dialogue.

**Describe alternatives you've considered**
- I thought about font scaling in case UI scaling is complex, but that will likely mess up the entire UI. 
- I've looked around in case one of the config-looking files had a value for this, but didn't find anything.
- Lowering the resolution feels kind of meh.

**Additional context**
If you really need a screenshot, I can provide one later today if you tell me to :)

**Comment by manavortex** [comment]
Hey, 
the one before today's update. I'll upload a screenshot later - with the recommended 150% element size on 4k resolution, I find the UI extremely hard to read. :)

**Comment by manavortex** [comment]
![image](https://user-images.githubusercontent.com/965785/139919239-cbf3c49d-b759-4759-bdc1-8cbac85f7db6.png)
I'm aware of the fact that it's an issue with my eyes being bad, but the way I find the program comfortable to operate would have me set monitor scaling from 150 to 175%. It would be lovely if you could address it at some point.

**Comment by Traderain** [comment]
Needs to be tested
