### ISSUE TITLE
Mesh Import for Architecture and MultiMesh Models is Broken

### ISSUE THREAD

**Issue by TheMindVirus** [WolvenKit/WolvenKit#625]
**Describe the bug**
The Modding Workflow for generating heavy construction and architectural mods is broken where it is working for smaller,
more simple models.

**To Reproduce**
1. Open WolvenKit and `Create a new project`
2. In the Asset Browser, find `base\environment\architecture\pacifica\pacifica_stadium.mesh`
3. Click the checkbox to select the item, right click and select `Add selected items to project`
4. In the `View` Tab open the `Import/Export` view, select `Export` and tick the checkbox for the object
5. Optionally configure export settings and click `Process Selected`
6. Open the exported `.glb` file in Blender and edit it in any way (remove armatures and starting items as this may also break it)
 - If you're using the custom python plugin you will need to export `WithMaterials` and select `PNG` twice in different places
7. After Editing the Mesh, Save it and Export to `.glb` (Important!: In export settings under `Geometry` make sure `Tangents` is checked)
- If you don't enable exporting `Tangents`, WolvenKit will complain at you (you might try to use the "TryFix" option but it will break)
8. Move the `.glb` back to where the exported file was in your project directory (use the `Project Explorer` to find where this is)
9. In the `Import/Export` view, select `Import`, check the checkbox for the item and click `Process Selected`
10. In the `General` Tab click `Pack Project` and `Save All`
- To make sure it saved correctly, click the `Asset Browser` sub-window, open the `Actions` tab and select `Toggle Mod Asset Browser`
- Now look for your mod within the list and inspect the outputted files. If some are missing then CP77Tools has stripped them
- Click `Toggle Mod Asset Browser` again to return to the default view
11. Start the game and attempt to import your modded item or architecture into the save game.
- The updating of the mod was done when you clicked `Pack All` and will update every time you click it.
- To remove the mod, remove its .archive file from %CP77_PATH%\archive\pc\mod or %CP77_MODS%

**Expected behavior**
Modified Item or Building appears in the game as it appeared in the editor that modified and sculpted it with desired engine tweaks.
The screenshots below show items just about appearing as they were edited but not buildings and complex models.

**Screenshots**
![error](https://user-images.githubusercontent.com/8195854/145737715-a5b82ad5-beac-4e42-84f9-90d09ec6fdcf.png)
![melded](https://user-images.githubusercontent.com/8195854/145737856-8a2b1c4c-a08a-4f1f-92d3-de3e4d1d165b.png)
![Cyberpunk2077_2021-12-13_00-20-06](https://user-images.githubusercontent.com/8195854/145737753-c7b6f35c-96d3-489f-85d2-a15b49322aa0.png)
![weirdstadium](https://user-images.githubusercontent.com/8195854/145737760-9a643122-91dd-42ce-9cf8-e0872bfcabf6.png)

**Machine:**
 Windows 10 Steam GOG Edition
 Intel Xeon E5 & NVidia GTX 1060
 
 **Eventual Goal:**
To Mod the Pacifica Stadium with a custom-made interior for custom games (online/offline)
![cyberpunk-1639265392892-9311](https://user-images.githubusercontent.com/8195854/145737805-a0294fe0-58ee-4317-91ce-ac0cc1a60a5c.jpg)
(Image Source: https://wallup.net/cyberpunk-mass-effect-mass-effect-3/)

**Comment by ja-to** [comment]
Architecture/world models within REDengine are significantly different compared to character assets. More than likely the stadium is using another mesh, proxies, or some cached/cooked meshes. If there was a failure with WolvenKit's mesh we can typically expect a CTD or some other glaring issue.

**Comment by TheMindVirus** [comment]
> Architecture/world models within REDengine are significantly different compared to character assets. More than likely the stadium is using another mesh, proxies, or some cached/cooked meshes. If there was a failure with WolvenKit's mesh we can typically expect a CTD or some other glaring issue.

The Crash To Desktop occurs when importing the mesh with a custom entity file which works fine for items but not for that particular mesh (even the version with separate buffer file and buffer file present in the archive). Otherwise there is no CTD and it loads normally but without any of the modifications made by the archive.

The Resolution was to import the meshes as .glb into blender and use them to further modify a working item's mesh, but even then the name conflict results in application of mystery modifiers from the first mesh (as pictured above) or the sub-mesh not appearing at all (perhaps being outside the culling range of the first sub-mesh).

RED Engine / WolvenKit / LimeKit / CR2WTools / CP77Tools need to stop treating sub-meshes as if they were the same as the first mesh in the collection and perhaps treat them more like Unity (-_-) processes sub-meshes with the right add-on scripts.

Here's what I did for Unity to add a "Merge Sub-meshes" tool but I've yet to make its counterpart "Split Sub-meshes" Tool: https://github.com/TheMindVirus/matrixbrutenoir/blob/e62fff4947b170a1de711e6383031acfc10e1e32/Tools.cs#L39
I've noticed instead of sub-meshes in the archives you have "sibling-meshes" in the form of other .mesh files alongside the main one in certain archives. (e.g. the folder next to base\environment\architecture\pacifica\pacifica_stadium.mesh)

**Comment by TheMindVirus** [comment]
Call it progress, I loaded in the `pacifica_stadium.mesh` model using the `int_accessories_001__johnnysguitar.ent` entity.
Both were built-in to the game and any attempt to create custom versions (even identical) resulted in game crashes.
It really doesn't like its own entity files or ones from mods. These errors might come from Cyber Engine Tweaks (de)spawners.

![Cyberpunk2077 2022-01-11 13-12-18](https://user-images.githubusercontent.com/8195854/148949590-9c782125-6326-4a88-ba3a-5ef1daede20c.png)

I did also want to mod in some custom optics cyberware.
The sprites for them were a little tricky to find in the folder structure.

![LegendaryOptics](https://user-images.githubusercontent.com/8195854/148950301-76da4667-143d-41f2-9b65-d26506ce360b.gif)

I made them into an advert instead because I have separate RAD Bink Video Tools and compressors installed.
It does ruin the quality and integrity of the video files somewhat but at least it sort of works...?

![Cyberpunk2077 2022-01-09 16-01-57](https://user-images.githubusercontent.com/8195854/148950775-7f8794b7-29d4-4069-a579-423ad1993b07.png)

I also tried to import them in the same way as the stadium model above, but again some mystery modifiers
from Johnny's Guitar made their way onto the gameObject and messed up the scaling somewhat with some amusing results.

![Cyberpunk2077 2022-01-09 15-14-13](https://user-images.githubusercontent.com/8195854/148951143-52483855-a371-4fa8-a73e-4d6fb83b1a53.png)

...more like the Toclafane from Doctor Who than custom optics but there they are...

**Comment by ja-to** [comment]
I'm closing this issue because it's still unclear what the issue with the stadium mesh is. Based on your findings it appears likely that the Stadium is setup/loaded in such a way that invalidates the typical mesh workflow, or the wrong mesh is being edited. Remember that mesh files can be directly embedded within other W2RC files.

For discussion, related or unrelated to the original issue, consider chatting with the community on Discord.

**Comment by TheMindVirus** [comment]
> I'm closing this issue because it's still unclear what the issue with the stadium mesh is. Based on your findings it appears likely that the Stadium is setup/loaded in such a way that invalidates the typical mesh workflow, or the wrong mesh is being edited. Remember that mesh files can be directly embedded within other W2RC files.
> 
> For discussion, related or unrelated to the original issue, consider chatting with the community on Discord.

Additional to the findings above, I received constant error messages from WolvenKit and Noesis about meshes having invalid Tangent data (and visibly when loaded in some invalid normals). This thread seems to concur:
https://forum.unity.com/threads/cant-calculate-tangents-because-mesh-doesnt-contain-normals.747638/

There are some other restrictions that WolvenKit's "TryFix" approach attempts to solve (if manually selected vs "Strict" mode).
These include a vertex count limit of 60000, material name uniqueness violations and the naming convention for submeshes:
```
[FBX]
submesh0
submesh1
submesh2
[mesh]
submesh_00_LOD_1
submesh_01_LOD_1
```

All of this has to map correctly for it to load in properly.
Mods which include .ent entity files which are identical to the original also cause game crashes when loaded by object spawners quoting the following reason:
```
Error reason: Assert
Expression: <Unknown>
Message: ArchiveAsyncSource: Unknown file segment for read at offset 535, size 0
File: e:\r6.release\dev\src\common\resource\src\serializationasyncsourceimpl.cpp(742)
```
I assure you that the correct paths have been followed to the correct meshes and it works with the only difference being the in-built entity file being used instead of the replacement one from the .archive from WolvenKit.

I hope this information helps you debug the issues surrounding meshes.
