### ISSUE TITLE
Materials Repository Generator fails with duplicate entries

### ISSUE THREAD

**Issue by fscan** [WolvenKit/WolvenKit#682]
Hi,

When the same item appears in multiple archives, MaterialsRepositoryDialog.GenerateMaterialRepo fails because it tries to write the exported files in Parallel.ForEach.

Example:
"base\characters\common\skin\old_mat_instances\skin_ma_c__fpp_arms.mi" exists in "basegame_4_appearance.archive" and "memoryresident_1_general.archive"

-> System.IO.IOException: 'The process cannot access the file ...'

Changing the Parallel.ForEach into normal foreach loops fixes the immediate issue, the question is if the correct one is written.

**Comment by fscan** [comment]
Also, later on for *.mlmask:
WolvenKit.Modkit.RED4.Uncook.cs:70  -> Create .mlmaskfile
WolvenKit.Modkit.RED4.MlmaskTools:82 -> Create Directory with same name

This is on branch fix/8.5.0-rc-fixes .. i tried this branch because of the errors i got exporting.

**Comment by rfuzzo** [comment]
cannot reproduce in main
