### ISSUE TITLE
Search function makes WolvenKit freeze

### ISSUE THREAD

**Issue by TheChilliPL** [WolvenKit/WolvenKit#687]
**Describe the bug**
WolvenKit freezes and needs to be force-stopped when trying to search through the game files

**To Reproduce**
1. Open any project
2. Search for anything using one of the text boxes in the pane with the game file browser

**Expected behavior**
It should search through the game files

**Screenshots**
![image](https://user-images.githubusercontent.com/18823939/155891744-1c940e43-95b5-44fb-aabc-d74573b3bd2d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 8.4.3

**Comment by ADawesomeguy** [comment]
I'm unable to replicate this on Windows 10. Is there any other information that you could maybe provide?

**Comment by TheChilliPL** [comment]
No idea, it happens literally every time I use the search bar just above the list of files

**Comment by rfuzzo** [comment]
this search bar has been removed in the current version (8.5)
