### ISSUE TITLE
CLI settings exception when headless on Linux

### ISSUE THREAD

**Issue by ADawesomeguy** [WolvenKit/WolvenKit#694]
**Describe the bug**
On Windows it just tries to open the file with whatever but on Linux (headless for sure, haven't tested one with a DE) it just throws an exception.

**To Reproduce**
1. Run `./WolvenKit.CLI settings`

**Expected behavior**
We should probably make it like GitHub CLI where on Linux it defaults to EDITOR and falls back to Nano.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Rocky Linux 8
 - Version: custom build

**Comment by ADawesomeguy** [comment]
@rfuzzo is it possible for you to assign me so I can remember to do this or not because I'm not a part of the org?

**Comment by rfuzzo** [comment]
added you
