### ISSUE TITLE
Typos, grammar errors etc.

### ISSUE THREAD

**Issue by Traderain** [WolvenKit/WolvenKit#70]
There are many grammar error and typos in the project. If you find any please comment them here.
Also here we can track stuff related to this.

**Comment by mattstates** [comment]
I will create a PR with some updates.

**Comment by ja-to** [comment]
I believe we can close this issue, it's approaching four years old and the application has been rebuilt from the ground up. I think spelling and grammar should be design guidelines rather than a persistent issue.
