### ISSUE TITLE
Editing the appearanceResource within WKit 8.5 RC1 is bugged.

### ISSUE THREAD

**Issue by ruchirlives** [WolvenKit/WolvenKit#705]
**Describe the bug**
Editing the appearanceResource field within an appearance in an ent template within WKit 8.5 RC1 is bugged.
Editing the field doesn't allow the file to be saved.

**Expected behavior**
File saves as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/141431/158269079-c2661aee-b1bc-4202-bf76-d7554b91a34d.png)
![image](https://user-images.githubusercontent.com/141431/158269132-e27372e5-0233-43f9-b060-93585f5dfbfa.png)

**Comment by ADawesomeguy** [comment]
Quick Markdown formatting tip: add the image like this: \!\[\]\(link\).

**Comment by rfuzzo** [comment]
this works on 8.6 dev version. tested with judy.ent
