### ISSUE TITLE
Nothing happens on opening

### ISSUE THREAD

**Issue by Plutonium-239** [WolvenKit/WolvenKit#709]
**Describe the bug**
On running wolvenkit.exe, it starts up, shows the cool splash screen (great work on that btw) and then just fades out. Nothing happens, even on waiting at least 3 minutes. Have to kill the process from task manager. 
I have installed .NET 6 runtime.

**To Reproduce**
1. Open wolvenkit.exe
2. Admire splash screen again
3. Wait as it fades and nothing happens after

**Desktop (please complete the following information):**
 - OS: Windows 10, 21H1
 - Version: Latest available at current time (8.5.1)

**Comment by dogspit134** [comment]
I'm having the same issue. It just sits in the background in task manager and uses around 600MB of memory, no CPU usage or anything else.

**Comment by november1911** [comment]
https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/tag/8.5.0-nightly.2022-02-10

works for me, the others dont

**Comment by dogspit134** [comment]
Thank you! It works for me as well

**Comment by Plutonium-239** [comment]
It seems like none of the nightly builds after that one are working, same error as above.

**Comment by rfuzzo** [comment]
This is fixed now on version 8.5.2

**Comment by JumLee** [comment]
Nightly has been fixed (thank you) however console continues to crash on launch.

**Comment by ADawesomeguy** [comment]
Console is more my speed, what’s exactly the issue?
