### ISSUE TITLE
Add Launch Options And Improve Toolbar Pack/Install/Launch Features

### ISSUE THREAD

**Issue by effs** [WolvenKit/WolvenKit#718]
Continuing off #702/#704 as this requires some reworking of the toolbar and the launch options are a major addition.

## Toolbar

Simple implementation looks like this:

![image](https://user-images.githubusercontent.com/13802421/157657192-b2eb1258-1954-4c59-9a4b-f300e7f3bf03.png)

…But it needs a better control than the SplitButton implementation in sf (weirdly uncustomizable as you can see with the black text) or MahApps (doesn’t actually do what splitbuttons do). I’ll see if it’s possible to import the WinUI3 SplitButton as an XAML Island… or just write a very simple Button + Menu with some cross-triggers.

Leastwise, I would prefer to have the most-used option directly clickable with the dropdown for additional options. (Could even make the most-used dynamic, or last-used?) If anyone has better suggestions, more than welcome!

## Launch options

@ADawesomeguy compiled a list of the command-line options:
```
unattended
forceRawTweakDB
profiler
windowCaption
scriptVersion
tweakdbBlobPath
scriptsBlobPath
pvdDumpToFile
renderPreset
forceLowSettings
qualityLevel (RTX)
texQualityLevel
meshQualityLevel
interopstartingport
watchdogTimeout
automator
```

This needs:

- [ ] Support in Settings to either add one set of switches, or
- [x] Actual 'launch profile' support (named + opt set), and both need
- [ ] Validation of the selections (and could do some more validation on settings save/load too)

Additionally if using launch profiles

- [ ] UI to select the profile to use (maybe default with a _secondary_ sub-action dropdown?)

**Comment by jackhumbert** [comment]
Here's some additional ones I was able to find. The `-` is necessary, and I've only tested a handful of them:

```
-engine=
  serverServerGameEngine
  serverDebugServerGameEngine
  FunctionalTestsServerEngine
  HeadfullTestServerEngine
  HeadllessTestServerEngine
  BackendGameEngine
-multiplayerServer
-multiplayerClient
-ignoreInput
-ignoreGamepads
-hudNoParallel
-noInputIcons
-newInkLayersEnabled
-mpMenu
-noFullscreenUI
-noHUD
-forceLoadAllMeshAppearances
-breakOnPoolDefault
-profileio
-disableioopt=
  IOLRUCache
  BufferInlineData
  MergeOps
  CancelOps
  KeepAliveForGameCache
-autoMemDump
-memoryDumpOuput
-disableRayTracing
-disableRayTracedReflection
-disableRayTracedTransparentReflection
-rayTracingAmbientOcclusionRayNumber
-dlss
-dlssQuality
-dlssSharpness
-width=*
-height=*
-fullscreen
-window
-windowed
-borderless
-hdrMode=*
-hdr
-x=*
-y=*
-monitor=*
-fpsClamp=*
-EMMFilter
-debugVerifyWorld
-benchmarkOutput
-benchmark
-slowHDD
-forceCPOControlScheme
-gamepadID=?
-forceCPOControlScheme
-debugShortTrialVersion
-functionalTestsMode
-gameDefinition
-playerVoiceoverType=?
-noBinksOnLoadingScreens
-debugIcons
-noDLSS
-position=*,*
-playerRecordID=?
-playerNickname=?
-ftBuildWithShelve
-ftBuildProcessName
-ftBuildNum
-ftHostIP
-ftHostName
-ftGameDataAccessMode
-ftEngineInstanceGUID
-ftTestFilter
-allowQuickCompression
-gameServicesWrapper=
  GameServicesSteam.dll
  GameServicesEpic.dll
  GameServicesGOG.dll
-datacenter=?
-groupToken=?
-gameVersion=?
-gpuFlag=
  debug
  debugNoBreak
  forceAsync
  noAsync
  forceCommittedResources
  debugGBV
  forceAftermath
  noAftermath
  forceAftermathDebug
  noAftermathDebug
  forceRayTracing
  noRayTracing
  noSmallBufferPools
-noGpuBreadcrumbs
-rawstartingport=*
```

**Comment by rfuzzo** [comment]
what's a good UI for that? I can think of:

S) in the **S**ettings (like we already have a the commandline arguments) - maybe add a checkbox dropdown which populates the commandline there.

L) a **L**aunch popup when starting the game - not bad, maybe add one more dropdown to the launch options called "Start game with arguments"

P) **P**rofiles like in VS - might be overkill, since nobody really will use these from Wkit anyways

**Comment by effs** [comment]
The big question is whether they will be used. Maybe if there's commonly used settings they can be added as checkboxes to the regular launch command, and the less common ones could be hidden behind a dropdown as checkboxes with the most recent selection persisted. You could save these as profiles but if they're not gonna be used and not the main point of the app, then they're just gonna clutter and confuse the UI for no real reason.

**Comment by ADawesomeguy** [comment]
Would it be possible to have something like Steam launch commands but have the known commands autofill or something?

**Comment by rfuzzo** [comment]
Basic launch profile UI is done with #921 rest is moved to milestone 8.7.1
