### ISSUE TITLE
All the highlights: checkboxes and text have turned black permanently. 

### ISSUE THREAD

**Issue by Precache** [WolvenKit/WolvenKit#721]
**Describe the bug**
While using 8.4.3 the previously red highlighted check boxes and text all turned black. Making them nigh impossible to see. Reinstalling and upgrading to 8.5.2 did not fix the problem.

**To Reproduce**
Happens ALL(100% 24/7) the time to me now. 

**Expected behavior**
Check boxes and highlight text should be red.

**Screenshots**
In the screenshot "boss" and "common" are selected, but it's impossible to tell, because the check mark is black not red. This occurs on all check boxes, radio buttons, and highlight text, but not tabs.

![blackhighlights](https://user-images.githubusercontent.com/16966194/157821585-91d317cb-5756-4c6e-9314-2ffcc36721b9.PNG)

**Desktop (please complete the following information):**
 - OS: win10 home
 - Version 8.4.3 and 8.5.2

**Comment by Precache** [comment]
Here you can see that the highlight color is set to red, but appears black.

![settings](https://user-images.githubusercontent.com/16966194/157823242-ab08727b-d8a0-4607-9df5-f1d2769daa99.PNG)
![radio](https://user-images.githubusercontent.com/16966194/1578232
![selected](https://user-images.githubusercontent.com/16966194/157823284-291d26ba-2fcc-4c7a-b0f1-1f5a3c9ab6a9.PNG)
53-b3a49cb2-1a8b-4bce-b522-c0c77486cf2b.PNG)

**Comment by rfuzzo** [comment]
cannot reproduce on main
