### ISSUE TITLE
Overwriting asset file makes WolvenKit lose track of it

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#727]
**Describe the bug**
Overwriting a project asset makes it vanish from both Import Tool and Project Explorer.  
I have found no way to bring it back but restarting WolvenKit and reopening the project. Opening a different project and switching back doesn't seem to be enough.  

**To Reproduce**
1. Open import tool. Have at least one asset (in my case, a tga) in the project structure that shows up on import tool.
2. Overwrite the file with an external application.
3. See error

**Expected behavior**
The asset should still be visible.

**Screenshots**
https://user-images.githubusercontent.com/965785/158059104-c3367536-3cab-4231-9466-b80fe104e989.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro 19042.1586
 - Browser: Chrome
 - Version: 8.5.3

**Workaround?**
Maybe add a "refresh" button?

**Comment by rfuzzo** [comment]
I cannot reproduce this, is this specific to Photoshop?

**Comment by manavortex** [comment]
No, I tried other programs as well. But I can't reproduce it either, so I suppose it's okay now! Probably something that was fixed when WK started tracking the file system?

Thank you for checking, I actually had forgotten about this.

**Comment by rfuzzo** [comment]
sorry that it took so long, and thank you for commenting!
