### ISSUE TITLE
QoL (UI) bugs/features

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#734]
QoL (UI) bugs/features
### asset browser: 

- [x] mod asset browser search doesn't work
- [x] general make the AB better
- [x] make the AB search better (more options)

### project explorer:

- [ ] the file watcher breaks randomly

### cr2w editor

- [x] "preview" column: with the first string/cname property of a class - for better navigation
- [ ] #1009

### Home page

- [ ] sort recent projects by last used

**Comment by rfuzzo** [comment]
Project Explorer:
- [ ] "open in windows explorer" doesn't work in the flat file view

**Comment by seberoth** [comment]
**Home page**

- [ ] Stop Project icons from randomly changing colors

**Comment by effs** [comment]
"Better" -> "working" in some cases :)

![image](https://user-images.githubusercontent.com/13802421/160259029-a499ea03-6fcf-4471-b796-b3b4b0586f79.png)

![image](https://user-images.githubusercontent.com/13802421/160259057-8afcf503-344e-4924-bf7d-46232bc7b34f.png)

**Comment by effs** [comment]
I'll see if I can work on the search..
