### ISSUE TITLE
Bug: Mesh (glb format) import/export submeshes out of order

### ISSUE THREAD

**Issue by Halvkyrie** [WolvenKit/WolvenKit#737]
Bug: Mesh (glb format) import/export submeshes out of order

Seemingly, Importing a glb file to a mesh file will make them end up in a different order than they originally were. Reverse?. This is problematic for editing existing mesh files. submesh_00_LOD_1 ends up being submesh_10_LOD_1 etc.

Wkit built from develop branch a few hours ago (16.03.2022)

**Comment by jackhumbert** [comment]
What mesh file did you notice this with?

**Comment by Halvkyrie** [comment]
> 

Hi! I was attempting to import/export v_sportbike2_arch_nemesis__ext01_body_a_01.mesh

seemingly it happened both with an untouched glb, and with the glb i'd edited. I can provide the edited glb should you want it.

**Comment by seberoth** [comment]
Fixed with #790
