### ISSUE TITLE
Clipboard crash

### ISSUE THREAD

**Issue by ruchirlives** [WolvenKit/WolvenKit#744]
**Describe the bug**
Copying to clipboard within the app crashes WKit for some users intermittently
Happens in all builds from stable to nightly

**To Reproduce**
1. Click on any entry in Asset or Project Browser
2. Right click and select Copy or Copy relative path
3. See error

**Expected behavior**
No crash consistently

Platform:
Windows x64

Suggestions:
Known issue with .net Windows clipboard interaction
Might be resolved by using Clipboard.SetDataObject(data) instead of Clipboard.SetText(data) within code.

**Comment by jackhumbert** [comment]
Do you happen to have the error log from this crash? I haven't been able to reproduce it.

**Comment by ruchirlives** [comment]
I’ve got a print out on The Discord channel https://discord.com/channels/717692382849663036/808086068023918603/953771521107701810

**Comment by ruchirlives** [comment]
Hi. I think I've fixed this bug within WKit's code. I'll submit a pull request.

**Comment by ruchirlives** [comment]
> Hi. I think I've fixed this bug within WKit's code. I'll submit a pull request.

https://github.com/WolvenKit/WolvenKit/pull/758

**Comment by ruchirlives** [comment]
Fixed. Thx
