### ISSUE TITLE
constant crashing

### ISSUE THREAD

**Issue by Wolf538** [WolvenKit/WolvenKit#746]
**Describe the bug**
I open wolvenkit.exe it opens fine and runs great i try and open an existing project or create a new one and it crashes without fail every time 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to wolvenkit.exe and launch it 
2. Click on create new or open existing project 
3. wait for it to try and load the assets 
4. it crashes and closes itself down 

**Expected behaviour**
from what iv seen online and been told it should open fine and let me go through the game files and edit the meshes of models etc 

**Screenshots**
no screenshot but i have a video 
https://youtu.be/-tmwetMWUes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser operaGX
 - Version 64-86

**Comment by jackhumbert** [comment]
If you go to "Settings" on the left-hand side before opening/creating a project, can you see that the game's directory has been set and is correct?

**Comment by rfuzzo** [comment]
cannot reproduce on main
