### ISSUE TITLE
"Create Item In Array" instantly crashes WKit

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#751]
**Describe the bug**
Clicking on the "Create Item In Array" in mesh -> localMaterialBuffer -> rawData -> any CMaterialInstance -> array:CKeyValuePair
instantly crashes WKit. Tested with "base\characters\main_npc\takemura\h0_001_ma_a__takemura\t0_000_ma_base__takemura.mesh" and "base\characters\main_npc\oda\h0_001_ma_a__oda\h0_001_ma_a__oda.mesh"

**To Reproduce**
1. Add either of the mesh mentioned above to the project
2. Open the mesh
3. Expand localMaterialBuffer -> rawData -> any CMaterialInstance -> array:CKeyValuePair
4. Click on "Create Item In Array"
5. WKit crashed

**Expected behavior**
It adds a new KeyValuePair

**Screenshots**
![image](https://user-images.githubusercontent.com/20621809/159505418-b79e0fc6-ad87-41fc-b0a8-660c2e50ed7e.png)

 - WKit Version: nightly 2022-03-21

**Comment by seberoth** [comment]
Yeah, need some special handling for those.
Need some kind of dialog to choose which value type should be used on creation.
