### ISSUE TITLE
Mesh editing import not always reliable ; causes mismatched textures 

### ISSUE THREAD

**Issue by n02b-anthicated** [WolvenKit/WolvenKit#755]
**Describe the bug**
Exporting the glb from this works fine. Haven't tried it with FBX, but doing it through noesis instead fixes the issue for me so I use noesis for the specific files this happens on.

This has happened on cargo computer pants, militech pants, rogue pants, cowboy boots, and tight jeans, all the PWA version.

**To Reproduce**

1. Export the mesh to glb
2. Refit the glb ( I was doing refits for this )
3. Import to game
4. Nullify garmentsupport necessary to prevent crashing ingame. Not a feature of wkit, done through 010 editor.
5. Load up game and equip item

**Expected behavior**
The materials get mismatched and don't load properly on the items. I can't replicate this by doing it through noesis. Haven't checked to see if this is because it was done in glb / if it works properly if I use a differnet file type with wkit. I did verify the submesh order was exactly as the original.

**Screenshots**
Screenshots of militech pants and cargo computer pants after refitting. 

![( 5246 )](https://user-images.githubusercontent.com/101440516/160539931-5d089511-17cc-4784-bdbe-9bf6df4f5baa.png)
![( 5245 )](https://user-images.githubusercontent.com/101440516/160540025-055c1927-a3e4-4c6b-8e5b-d628f0d8542b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 
 - Version WKIt version 8.6.0-nightly.2022-03-24

**Comment by Halvkyrie** [comment]
Hi! While I can't be 100% certain about this because i'm a noob, this definitely looks to be a result of [issue#737](https://github.com/WolvenKit/WolvenKit/issues/737) that I've mentioned previously where raw -> redengine mesh import causes a mismatch in the submesh order . And that's only more evident because the materials used for the mesh are mapped to each submesh name.

**Comment by n02b-anthicated** [comment]
Not a bug ; reorganized stuff was explained by seberoth some time ago in discord. This issue occurs when you use an exported GLB from a different version of Wkit before the change was made.
