### ISSUE TITLE
Crashed Inkwigdet & xbm files

### ISSUE THREAD

**Issue by map788** [WolvenKit/WolvenKit#756]
**Describe the bug**
After import file inkwigdet and xbm wkit crashed

**To Reproduce**
1.Import XBM & inkwigdet from new item tutorial
2. open editing,
3. crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Ya.Browser
 - Version: WolvenKit-8.6.0-nightly.2022-03-24

Imported files
[5_item_template.zip](https://github.com/WolvenKit/WolvenKit/files/8374463/5_item_template.zip)
[shitjack_01.zip](https://github.com/WolvenKit/WolvenKit/files/8374465/shitjack_01.zip)

**Comment by map788** [comment]
[applog20220329.txt](https://github.com/WolvenKit/WolvenKit/files/8374480/applog20220329.txt)

**Comment by map788** [comment]
![image](https://user-images.githubusercontent.com/4691706/160818065-4a08747e-0529-46ca-8aa9-cb547e0ff34b.png)
update crashed when convert dds in xbm & result

**Comment by map788** [comment]
last crashlog
[applog20220330.txt](https://github.com/WolvenKit/WolvenKit/files/8379903/applog20220330.txt)

**Comment by seberoth** [comment]
For the inkatlas: This file is malformed, can't do anything about it
For the xbm: The xbm file is malformed to (format and compression is missing) so neither opening it or importing the png/dds with keep file will work.

Importing as new file for the png worked before and importing the dds as new file should work with the latest commit
