### ISSUE TITLE
CurveEditor is broken

### ISSUE THREAD

**Issue by seberoth** [WolvenKit/WolvenKit#768]
The following issues are known:

- If the property is null, the elementType can't be detected [CurveEditorWindow.xaml.cs#L33](https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit/Views/Editors/CurveEditorWindow.xaml.cs#L33)
- Adding points to an existing curve, only displays its changes after saving and reloading the cr2w file
- Saving a HDRColor curve clears all points on save

**Comment by richard-kelly** [comment]
Additional issue: X and Y (time and value) values are swapped in the editor. Here is the puppet_powerLevelToHealth curve in puppet_power_level_to_health_hard.curveset

![curve](https://user-images.githubusercontent.com/15858718/163668676-50ee2288-8af5-4e3e-bee7-f8c10a421de8.PNG)

The values 1-50, shown here as "values" are the input to the curve, and the "time" values are the output.

**Comment by seberoth** [comment]
Fixed with #790
