### ISSUE TITLE
Inconsistencies with filepaths in mesh material buffer

### ISSUE THREAD

**Issue by keysuspect** [WolvenKit/WolvenKit#770]
Note, this doesn't always happen with all meshes, but it mainly seems to happen with the player body mesh. If I edit the filepaths in the localmaterialbuffer to custom ones, the changes will at some point get reverted.

1. Change a filepath in the player body mesh, e.g. the GlobalNormal.
2. Launch game.

I expected my referenced custom materials to show up in game after packing and installing my project. Instead, when I launch my game, no changes seem to be in effect. I close my game and open the project again, and see that the filepaths I input have reverted back to what they were before I changed them.

 - OS: Windows 11
 - Browser: Chrome

**Comment by ja-to** [comment]
I tested this issue on the follow mesh:

`base\vehicles\sportbike\v_sportbike1_yaiba_kusanagi\entities\meshes\v_sportbike1_yaiba_kusanagi__ext01_trunk_01.mesh`

I opened the file with WolvenKit, and edited a `MultilayerSetup` path within the `localmaterialbuffer`. After saving and reloading the file, the change was correctly saved.

This appears to be resolved.
