### ISSUE TITLE
Change search to within installed mod archives assets when switched to it

### ISSUE THREAD

**Issue by 86maylin** [WolvenKit/WolvenKit#779]
**Is your feature request related to a problem? Please describe.**
When viewing installed mod archives content, currently it ignores the mod archives assets and only searches in the basegame assets, which makes it a bit tedious to do things like find mod conflicts and search for specific things. 

**Describe the solution you'd like**
It'll be pretty handy to switch the scope of the search bar to only search within the installed mod folder when it's set to view installed mod archives. 

**Additional context**
![image](https://user-images.githubusercontent.com/20621809/164582646-b6fae8c0-37b1-4064-89a2-5514e419ddbf.png)

**Comment by effs** [comment]
This functionality is in #734, I'll clean it up so it can go into develop rather than having to use yet another branch!

**Comment by seberoth** [comment]
Fixed with #790
