### ISSUE TITLE
Copying and pasting a chunkmask value causes game to crash

### ISSUE THREAD

**Issue by dmel642** [WolvenKit/WolvenKit#785]
EDITED: In nightly build 8.6 04-29, when copying and pasting a chunkmask value, for example 18446744073709551615 into a t0_*_body appearance, the game crashes. However, if I manually check all of the boxes, the game doesn't crash.

**Comment by dmel642** [comment]
Update: If you're having trouble reproducing, use Appearance Menu Mod to spawn a homeless female. You'll notice the game crashes as soon as that happens.

**Comment by seberoth** [comment]
Still cant reproduce it :(
Here is the homeless woman with appearance `homeless_wa_01` where I deleted all `entGarmentSkinnedMeshComponent`
![grafik](https://user-images.githubusercontent.com/456881/166133572-f4e0bc8c-2f14-4d4f-ad06-0510e3d95da1.png)

**Comment by dmel642** [comment]
I've updated the issue to the exact bug that was the cause.

**Comment by seberoth** [comment]
Seems to only apply under certain conditions. Had the problem once, too but couldn't reproduce it since then.
