### ISSUE TITLE
WolvenKit.CLI.exe instantly closes after opened / (Required command was not provided)

### ISSUE THREAD

**Issue by Lithuaniann** [WolvenKit/WolvenKit#801]
**Describe the bug**

Hi, before I say anything about the bug just whant to point out that im new that I'm new in modding. Now about the bug.

So I installed the WolvenKit and played around with it a few days ago, but then deleted it and downloaded a newer version. Now when I open WolvenKit.CLI.exe command file it closes instantly. I can't tell whats going on. I'v been installing and uninstalling it for a couple of times and it might have to do something with the file you have to copy from the game files to WolvenKit folder. I (for example) mod for cyberpunk and seen in the tutorial that I have to copy this (oo2ext_7_win64.dll) from the game files to WolvenKit folder. The reason I' saying there could be a problem with this, it's because every time i re-installed the WolvenKit this file apeared in the folder a couple of seconds after I installed the Kit. 
I (partly) solved the problem by (shift + rightclicking In the WolvenKit folder and selecting "Open PowerShell window here").
Now It does open for me but at the start it shows me message that "required command was not provided" (I uploaded the screenshot below). It also shows the same when I open the file WolvenKit.CLI.exe and it shows me the command line for a few seconds after closing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: WolvenKit - Latest (8.6)

Screenshots:

PowerShell console:

![Screenshot_48](https://user-images.githubusercontent.com/106549020/171036903-58380118-4b9c-44b4-a901-2d4b906c7555.png)

WolvenKit console:

![Screenshot_51](https://user-images.githubusercontent.com/106549020/171037936-4b4a30b7-c528-4c5f-abfc-68a8ac248679.png)

**Comment by seberoth** [comment]
Thats not a bug, see #732

**Comment by Lithuaniann** [comment]
Ty
