### ISSUE TITLE
Crash when adding a file in Asset Browser and then switching to Project Explorer if those two views share same part of window

### ISSUE THREAD

**Issue by richard-kelly** [WolvenKit/WolvenKit#803]
When Asset Browser and Project Explorer are in the same window/widget-thing (so they are different tabs in the same area of the app), if you add a new file to the project and then click on Project Explorer tab to switch to it, the app exits.

1. Drag the Asset Browser and/or Project Explorer views so they are in the same area, making them tabs you can select from.
2. Click on the Asset Browser tab to show that view.
3. Navigate to any file not currently in the project, and add it to the project by right-clicking on it and selecting "Add selected items to project".
4. Click on the Project Explorer tab.

**Expected behavior**
The Project Explorer view should open normally.

This is what I mean by having both views in the same area:

![asset_browser](https://user-images.githubusercontent.com/15858718/172006026-f24ca48f-5cb4-4c8c-b3e5-72f1c22085f0.png)

I've poked around with the debugger but I don't know enough to fix it. Seems to happen in `this.WhenActivated()` in `ProjectExplorerView.xaml.cs`. There's no error message in the debug output.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043 Build 19043
 - Browser: Chrome
 - Version: 8.6.0-nightly.2022-06-04 (but this has been a bug for a long time in all versions I've tried)

**Comment by rfuzzo** [comment]
cannot reproduce in main

**Comment by richard-kelly** [comment]
@rfuzzo This seems to be fixed for me on main now (not sure why you reopened?)

**Comment by rfuzzo** [comment]
😅 I could reproduce it on main... and I have frankly no idea why it happens. I suspect some threading issue - but it happens inside suncfusion's dll.

**Comment by richard-kelly** [comment]
Oh weird! Maybe there are more conditions required for the bug than I though before, or it's been fixed in some cases.

**Comment by poirierlouis** [comment]
I tried the steps with:
- a debug build
  - an existing project
- a release build
  - an empty project
  - an existing project

In all cases, I had no trouble opening the Project Explorer.
Tested with: 8a5988ceff1ae1018ff9710c4246e28191568408.

Can it be closed?

fyi @seberoth @manavortex, I'm going over oldest issues to check/fix/close them...

**Comment by richard-kelly** [comment]
I still do these steps all the time and have not had a crash since I last posted.
