### ISSUE TITLE
Reinstalling CP2077 to a different folder causes crash on startup

### ISSUE THREAD

**Issue by jwcliff** [WolvenKit/WolvenKit#806]
I had to reinstall CP due to an error with GOG while updating, and stuck it on a new drive when I did. Wolvenkit now crashes on load with an unhandled exception and a message that it could not find part of a path for the tweakdb.bin in the applog.
Have confirmed its looking for the old install dir, which no longer exists.

## Steps to reproduce
install CP, run wolvenkit, reinstall CP to a different location, then try run wolvenkit.

## Actual Result
you get the splashscreen then a silent crash.

## Expected result
should load the app and complain that the path is invalid.

**Comment by jwcliff** [comment]
updating the path in %appdata%\REDModding\WolvenKit\config.json fixes it.

**Comment by ADawesomeguy** [comment]
Have you checked the error/crash log?

**Comment by rfuzzo** [comment]
yeah I know this bug

**Comment by jwcliff** [comment]
> Have you checked the error/crash log?

yeah, thats why I said "a message that it could not find part of a path for the tweakdb.bin in the applog" I  can post the actual log if that helps, its just on my other machine.
