### ISSUE TITLE
Unable to play video or audio without first adding to project

### ISSUE THREAD

**Issue by ADawesomeguy** [WolvenKit/WolvenKit#841]
The previews don't work unless you've added it to a project first. This is because of the way previews are handled (it only works with CR2W files)

With OGG conversion support added, it should just be one step away to convert using FFMPEG libs or some other tool and play in the built-in media player.

**Comment by rfuzzo** [comment]
Audio previews work on main now with [this commit](https://github.com/WolvenKit/WolvenKit/commit/bcf026e899a89990d215fb7fa7b0dee1926f723d).
