### ISSUE TITLE
Set the LOD filter OFF by default in the mesh export settings.

### ISSUE THREAD

**Issue by BeDuw** [WolvenKit/WolvenKit#851]
Previous versions of WK had the LOD filter off by default, nightly 8.7 does not

**Comment by ja-to** [comment]
I set the LOD filter to `off` by default for UX consistency. I believe it's better behavior from WolvenKit to export files "as-is" by default, as opposed to modifying the data.

However with #914 import & export settings are saved per-project when modified. The saved setting is persistent between WolvenKit sessions. So for example, if a mesh is exported with the LOD filter set `on` it should be remembered for all subsequent exports from a given WolvenKit project.
