### ISSUE TITLE
Meshes with LOD0 do not import into WolvenKit

### ISSUE THREAD

**Issue by dragonzkiller** [WolvenKit/WolvenKit#854]
**Describe the bug**
WolvenKit only supports LOD values 1, 2, 4, and 8. A few submeshes (particularly vehicles) have their LOD8 values listed as LOD0. When exported and reimported, WolvenKit will not import a submesh with LOD0.

**To Reproduce**
1. Open WolvenKit
2. Create new project or open a previous one
3. Export a vehicle with an LOD0 submesh (e.g. `base\vehicles\sport\v_sport2_quadra_type66_nomad\entities\meshes\v_sport2_quadra_type66_nomad__ext01_engine_01.mesh`)
4. Reimport the mesh

**Expected behavior**
WolvenKit should either handle the LOD0 as LOD8 or the import code should be updated to handle the few meshes with LOD0.

**Screenshot**
![image](https://user-images.githubusercontent.com/931177/177647040-79f720d9-8bbd-42a6-b0a2-b23ea4a2aafe.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 8.7 nightly

**Comment by Syrrr** [comment]
So importing a mesh and replacing any occurence of a LOD0 with LOD8 shouldn't break anything, correct?
