### ISSUE TITLE
Support (Or Require) A License & Show License When Utilizing Mods

### ISSUE THREAD

**Issue by effs** [WolvenKit/WolvenKit#859]
There's always some talk about what is and isn't appropriate use of mods. We have a (kind of a) solution in the form of licenses. Won't fix everything, but it's a good start, and mainly needs a nudge to start getting adopted.

- [ ] If there is a license file (conventional name), display it when user copies resources to their own project (and maybe highlight it in AB anyway - popping up every time you open it would be a bit much)
- [ ] Allow including a license file in a project
- [ ] Not quite but kinda require a license at some point?
- [ ] Suggest a CC license as default?
- [ ] Define some kind of a reasonable 'mod general license' if anyone happens to want to play lawyer
- [ ] ?

**Comment by rfuzzo** [comment]
Not in scope for Wolvenkit
