### ISSUE TITLE
WolvenKit crashes after setting up Game Executable path and Depot Path

### ISSUE THREAD

**Issue by MaciejReszotnik** [WolvenKit/WolvenKit#887]
**Describe the bug**
App crashes after setting up Game Executable path and Depot Path 

Prerequisites:
WolvenKit has not been launched in the system yet and folder AppData\Roaming\REDModding\WolvenKit does not exist

**To Reproduce**
1. Launch Wolven Kit
2. On the first window asking you to fill in Game Executable path and Depot Path leave default values
3. Click Finish button
4. Observe crash
5. Relaunch the application
6. Observe another crash after splash screen disappears

**Expected behavior**
Application launches and is usable after first screen

**Actual behavior** 
App crashes. The following log is generated within C:\Users\[user]\AppData\Roaming\REDModding\WolvenKit
[applog20220906.txt](https://github.com/WolvenKit/WolvenKit/files/9500682/applog20220906.txt)

*Excerpt from logs:*
2022-09-06 22:55:06.104 [DBG] WolvenKit update available: 8.6
2022-09-06 22:55:28.455 [ERR] Unhandled exception in WolvenKit v8.6.0.0
2022-09-06 22:55:28.461 [ERR] Message: The given key '3476913071' was not present in the dictionary.
Source: System.Private.CoreLib
StackTrace:    at WolvenKit.RED4.TweakDB.TweakDBReader.ReadRecords(Int32 offset, RecordsPool pool) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.TweakDB\TweakDBReader.cs:line 127
   at WolvenKit.RED4.TweakDB.TweakDBReader.ReadFile(TweakDB& file) in D:\a\WolvenKit\WolvenKit\WolvenKit.RED4.TweakDB\TweakDBReader.cs:line 82
   at WolvenKit.Common.Services.TweakDBService.LoadDB(String path) in D:\a\WolvenKit\WolvenKit\WolvenKit.Common\Services\TweakDBService.cs:line 42

Notes: If the folder C:\Users\[user]\AppData\Roaming\REDModding\WolvenKit is deleted app can be relaunched, but crashes as soon as as Depot Path is determined
Changing the Depot Path to other than default does not fix the issue

**Desktop (please complete the following information):**
 - OS: Win 10
 - Required software: .NET 6.0.8 Desktop Runtime has been installed on the computer
 The following list of runtimes is installed on the system:

The following list of runtimes is installed on the system:
dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Muse0** [comment]
Just experienced the same behavior.

Also running Windows 10 with only .NET 6.0.8 installed

dotnet --list-runtimes
Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

*Log Excerpt:*
2022-09-06 16:59:06.985 [ERR] Unhandled exception in WolvenKit v8.6.0.0
2022-09-06 16:59:07.011 [ERR] Message: The given key '3476913071' was not present in the dictionary.
Source: System.Private.CoreLib
...

*App log for first run and four additional runs:*
[applog20220906.txt](https://github.com/WolvenKit/WolvenKit/files/9501184/applog20220906.txt)

**Comment by arintoker** [comment]
I am also experiencing this same issue.

**Comment by maxmike181** [comment]
Same issue on Windows 11. App set to be allowed through all AV. Reinstalled .NET 6. No change

**Comment by seberoth** [comment]
That's because you try to use it with game version 1.6. Its not supported yet

**Comment by ja-to** [comment]
Some users have had success with launching the latest nightly version:

https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/tag/8.7.0-nightly.2022-08-21

However this version doesn't fully support game version 1.6 and does not contain REDmod features yet.

**Comment by maxmike181** [comment]
8.7 Nightly was the crashfix for me. Thanks!

**Comment by MaciejReszotnik** [comment]
> That's because you try to use it with game version 1.6. Its not supported yet

I see. Well, this is confusing since the official documentation CDPRed just released for RedMod tools encourages integration with Wolvenkit. It is puzzling how they released patch and documentation of the RedMod at the same time, but they did not ensure that both work together well.

**Comment by ja-to** [comment]
> 

Game version handling has been improved, the development/nightly build of WolvenKit doesn't suffer from the same game version crash.

In regards to not working together: WolvenKit is open-source. The REDmod integration features are already available if you compile WolvenKit yourself.

See Pull Request #886 

A pre-compiled nightly release will be available after this has been merged.

**Comment by MaciejReszotnik** [comment]
@ja-to 
 
Many thanks for clarifying stuff and stellar work on this project.
