### ISSUE TITLE
WolvenKit crashes after splash screen

### ISSUE THREAD

**Issue by roa-nyx** [WolvenKit/WolvenKit#888]
**Describe the bug**
WolvenKit displays splash screen but then crashes.

**To Reproduce**
1. Install WolvenKit into a folder (mine is here: `C:\_bin\WolvenKit`)
2. Double-click on `WolvenKit.exe` (in file explorer)
3. Wait for splash screen to disappear

**Expected behavior**
I expected WolvenKit to load a window. But instead after about 5-10 seconds the splash screen just disappears. No new window is opened.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 v21H2 (OS Build 19044.1889)
 - Browser Firefox 104.0.2 (up to date at time of writing)
 - Version (of what? The browser? Wolvenkit? Maybe worth updating instructions to make this more clear)
   - Using Wolvenkit 8.6 (marked latest at time of writing)
   - Using Cyberpunk 1.6 (released today) on Steam.
   - Using dotnet core 6.0.8

**Comment by roa-nyx** [comment]
Found another bug report explaining where to find the log files, I'm uploading it here. I'll rename this AppData folder and see if that helps.
[applog20220906.txt](https://github.com/WolvenKit/WolvenKit/files/9501692/applog20220906.txt)

**Comment by roa-nyx** [comment]
After renaming the WolvenKit AppData folder and rerunning WolvenKit it shows a dialog to request the Cyberpunk2077 executable path. After filling that in it just crashes. Attached the logs.

[applog20220906.txt](https://github.com/WolvenKit/WolvenKit/files/9501703/applog20220906.txt)

I feel this can be closed as this is now just a duplicate of this issue: https://github.com/WolvenKit/WolvenKit/issues/888

**Comment by ja-to** [comment]
See #887
