### ISSUE TITLE
REDmod support: Unable to install REDmod plugin.

### ISSUE THREAD

**Issue by nullfrctl** [WolvenKit/WolvenKit#889]
**Describe the bug**

**To Reproduce**
1. Go to 'Plugins'
2. Scroll down to 'RedMod'
3. Click on 'Install'

**Expected behavior**
Plugin installs without issues. Currently adds an error that persists forever, even if REDmod is installed on GOG or Steam

Could be fixed by adding a check if <root>/tools/redmod exists.

**Comment by rfuzzo** [comment]
fixed in #892
