### ISSUE TITLE
errors with meshes when exporting to .json

### ISSUE THREAD

**Issue by keysuspect** [WolvenKit/WolvenKit#896]
When trying to export most meshes, the log gives errors and no .json file is ever made. Specifically any body mesh, but many NPC items as well. The only one I could properly get to export to a .json file was this mesh: base\characters\main_npc\placide\t2_001_mb_jacket__placide.mesh

**To Reproduce**
1. Go to base\characters\common\base_bodies\woman_average\t0_000_wa_base__full.mesh and add the mesh to the project.
2. Right click and choose 'export to JSON'
4. Check log and see error

**Expected behavior**
WolvenKit will add a new .json file to the project.

**Desktop (please complete the following information):**
 - OS: 22000.918
 - Browser: Chrome
 - Version: Windows 11 Home
[log.txt](https://github.com/WolvenKit/WolvenKit/files/9539543/log.txt)

**Comment by rfuzzo** [comment]
This is fixed on main
