### ISSUE TITLE
Mesh exporting WithMaterials stopped working with custom meshes

### ISSUE THREAD

**Issue by xBaebsae** [WolvenKit/WolvenKit#898]
**Describe the bug**
When exporting a customized mesh using the WithMaterials Export option, Wkit reports it is ''not a cr2w file'' and doesn't proceed with the export. The exact same mesh exports fine using this option in the last stable 8.6 build. The material json obtained through 8.6 can also be imported using 8.7, only export is broken.

**To Reproduce**
1. Export a custom mesh using WithMaterials (eg. my custom base [here](https://drive.google.com/file/d/1i6Mky-Y6UxC9VCqYQWIKCaFMSMsGh__V/view?usp=sharing) )
2. See Wkit log for error details. 

**Expected behavior**
Exporting material jsons from custom meshes like in 8.6.

**Screenshots**
![Screenshot_10317](https://user-images.githubusercontent.com/113468873/189985627-71adb943-2b81-4999-8cb7-1b8d2747e82b.jpg)

**Desktop (please complete the following information):**
 - Win10
 - Version 8.7.0-nightly.2022-09-11 (noticed since nightly.2022-07-27)

**Comment by seberoth** [comment]
The error `not a cr2w file` is misleading here. Will chnage that in the future.
The error happens because the file `base\fx\shaders\device_diodt.mt` (used in `localMaterialBuffer`, material_emission_27 - 35) doesn't exists

**Comment by xBaebsae** [comment]
Is there a way to make wkit still print the paths into material json but instead of crashing, display warnings instead? I can only assume that's how it worked in 8.6 because it's all fine there. I'm sorry to be such a bother about this, i just can't do my hybrid workflow anymore because of the new patch.

**Comment by seberoth** [comment]
> Is there a way to make wkit still print the paths into material json but instead of crashing, display warnings instead?

Could do that from my side, but not sure how the blender plugins handles this. @dragonzkiller 

> I can only assume that's how it worked in 8.6 because it's all fine there

Nothing has changed in a while for mesh export. I assume, that the file existed in the 1.52 archives
