### ISSUE TITLE
Linux (GUI): Cannot "Pack & Install" projects

### ISSUE THREAD

**Issue by nullfrctl** [WolvenKit/WolvenKit#903]
**Describe the bug**
When clicking on "Pack & Install" with a project, WolvenKit does not complete the request.

**To Reproduce**
1. Go to a project
2. Click on "Pack & Install"
3. Wait a few seconds

**Expected behavior**
WolvenKit shows a small notification saying "... installed succesfully!" and the mod is modified in the destination.

**Screenshots**
![Pack & Install being clicked](https://media.discordapp.net/attachments/794475232764100648/1020119955313807390/Screenshot_from_2022-09-15_17-51-28.png)
..then..
![Nothing happening a few seconds afterwards](https://media.discordapp.net/attachments/794475232764100648/1020119956274298920/Screenshot_from_2022-09-15_17-51-37.png)
No change in last-modified date
![No change in last-modified date](https://user-images.githubusercontent.com/99456326/190528327-b46afc08-8b46-471e-98d7-8efb09d4a9a0.png)

**Desktop (please complete the following information):**
 - OS: Linux, Nobara 36 (GNOME). Wine 7.16
 - Browser: Firefox 104.0.1 (64-bit)
 - Version: 8.7.0-nightly.2022-09-15

**Comment by rfuzzo** [comment]
Linux is not really supported... Also only @ADawesomeguy has a lInux machine to debug this afaik.

**Comment by ADawesomeguy** [comment]
😳 ok I'll take a look.

**Comment by ADawesomeguy** [comment]
@nullfrctl what exactly is the error that it shows?

**Comment by nullfrctl** [comment]
Uhhh, crap, think I deleted wolvenkit from my linux install. Just been using KVM past few weeks. I'll close it.

**Comment by ADawesomeguy** [comment]
Alright, I'll see if I can figure it out later at some point.
