### ISSUE TITLE
Can't create items in array

### ISSUE THREAD

**Issue by nullfrctl** [WolvenKit/WolvenKit#910]
**Describe the bug**
When clicking the "Create Item In Array" button, WolvenKit adds a 0, but not a 1, and when clicking again, doesn't increase.

**To Reproduce**
1. Go to a project.
2. Click on a CR2W file
3. Scroll down to "Create Item In Array"

**Expected behavior**
WolvenKit adds an item in the array, and increases the count in brackets (like this: [12]) by one.

**Screenshots**
![Clicking "Create Item In Array"](https://user-images.githubusercontent.com/99456326/191748034-bae67039-1e7b-4d23-9262-461a1030dc3b.png)
![Adds a 0 to item count](https://user-images.githubusercontent.com/99456326/191748105-c15b797d-1e4d-4d16-9890-1c88f4a5e6de.png)
![Empty list view](https://user-images.githubusercontent.com/99456326/191748171-2e0754f7-5ad9-4093-a575-8b7f44796ecd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC 2019
 - Browser: Firefox 104.02
 - Version: Self-compiled (https://github.com/WolvenKit/WolvenKit/commit/d495d45571a79da9a0296131cef3bc8a97527e1e)

**Comment by blompie1983** [comment]
> **Describe the bug** When clicking the "Create Item In Array" button, WolvenKit adds a 0, but not a 1, and when clicking again, doesn't increase.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to a project.
> 2. Click on a CR2W file
> 3. Scroll down to "Create Item In Array"
> 4. See error
> 
> **Expected behavior** WolvenKit adds an item in the array, and increases the count in brackets (like this: [12]) by one.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![Clicking "Create Item In Array"](https://user-images.githubusercontent.com/99456326/191748034-bae67039-1e7b-4d23-9262-461a1030dc3b.png) ![Adds a 0 to item count](https://user-images.githubusercontent.com/99456326/191748105-c15b797d-1e4d-4d16-9890-1c88f4a5e6de.png) ![Empty list view](https://user-images.githubusercontent.com/99456326/191748171-2e0754f7-5ad9-4093-a575-8b7f44796ecd.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 LTSC 2019
> * Browser: Firefox 104.02
> * Version: Self-compiled ([d495d45](https://github.com/WolvenKit/WolvenKit/commit/d495d45571a79da9a0296131cef3bc8a97527e1e))

**Comment by blompie1983** [comment]
i like
