### ISSUE TITLE
unable to select paths at the start

### ISSUE THREAD

**Issue by 70V07** [WolvenKit/WolvenKit#912]
Windows 11 Home

Cyberpunk 2077

VolvenKit 8.7.0

is impossible select the executable path (nor the depot path), both button for select paths doesent work, and if I add manually the path in the box, the window still to remain to selection paths, and an *necessary indicator red circle still remain on exe path*, press finish doesent work, also the program after close the paths window still remain active in process

**Comment by Holydh** [comment]
Windows 10 Pro
CP2077
WolvenKit 8.7.0 nightly.2022-09-24

Same here. The buttons for selecting paths both don't work. And if I add them manually then clic on finish, the first clic nothing happens, when I click a second times, the window closes, I then can see some processor and disk activity in the task manager on the WolvenKit process for a few seconds, then nothing. Memory usage stays at 1333,5Mo and nothing more happens. I tried waiting for more than 10 minutes then ended up killing the process. I tried this two times. Same results.

Wolven Kit is on the same disk as windows (C:). The depot path is also on C: but the game is on another disk drive if that could be useful info for troubleshooting.

**Comment by Greedeater** [comment]
Exact same issue as Holydh, glad I'm not the only one.

**Comment by rfuzzo** [comment]
This is fixed in [Fixed a bug where the app would hang on first launch](https://github.com/WolvenKit/WolvenKit/commit/8aab34d3c0354676bc72daa05b09588fdcfe46b8)

and will be in today's nightly, sorry for the inconvenience.

**Comment by Mandraw** [comment]
This still happens with the new nightly

**Comment by Holydh** [comment]
> This is fixed in [Fixed a bug where the app would hang on first launch](https://github.com/WolvenKit/WolvenKit/commit/8aab34d3c0354676bc72daa05b09588fdcfe46b8)
> 
> and will be in today's nightly, sorry for the inconvenience.

Don't be sorry, that's what nightly builds are for ; ) Thanks for your amazing work !
Gonna try the new build now.
