### ISSUE TITLE
TweakXL support

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#922]
**Is your feature request related to a problem? Please describe.**
We support tweakXL .yaml files in mods but have no UI for it.

**Describe the solution you'd like**

- [x] Add a tweakXL yaml file option to the "Create New File View"
- [x] Add an "export tweak record" to the TweakBrowser
- [ ] optionally some REDmod compatibility

**Describe alternatives you've considered**

None. There is no alternative,

**Comment by dragonzkiller** [comment]
Just for tracking on here: I'm almost done with the second task, but posed a few questions in discord about implementation

**Comment by dragonzkiller** [comment]
Second step is pretty much done. We should have a finer breakdown of tasks required for actual support though. Here's a few more I can think of. I'm working on the first now.

- [ ] Editable TXL in `ChunkViewModel`
- [ ] Support for `!append` tags
- [ ] Optional: support for aliases
