### ISSUE TITLE
Script deployment support

### ISSUE THREAD

**Issue by keless** [WolvenKit/WolvenKit#926]
"The point is to have an all in one tool for creating mods for the games made with the engine."  https://redmodding.org/ description of WolvenKit

Currently if I have a /scripts folder in my WolvenKit Project, when I "pack + install" my project, it completely ignores the scripts folder.

I realize there are a number of different scripting solutions for Cyberpunk right now, and each requires a different configuration for deploying scripts. As a bare minimum it would be nice to have a configuration option per project to specify a folder to copy files from the project's scripts folder into.

For instance; when using RedScript, files and folders under < projectfolder >/scripts/*  should be copied into < gamefolder >/r6/scripts/< projectname >/*

It could be nice if a project could let you specify the type of scripting solution you intend to use (CET lua, RedScript .reds, REDMod .script, etc) and automatically know where to deploy based on that (and possibly check that the appropriate prerequisite mod framework CET/SCC/etc tools/mods are installed properly). 

Alternatively, a simple "copy <project>/scripts/ to: <path>" setting would also work.

This behavior would then be triggered whenever "Pack & Install" or "Install & Run" are executed.

**Comment by kwekmaster** [comment]
@rfuzzo -- forgot to mention. Taking this, please assign to me. Thanks.
