### ISSUE TITLE
Wolvenkit not launching after configuring cp2077.exe path

### ISSUE THREAD

**Issue by Ovenfresh** [WolvenKit/WolvenKit#936]
On first startup, Wolvenkit asks to select a path for the CP2077 exe. After setting this path, the application closes instantly. Trying to reopen the application starts the splash screen, which then, after a couple seconds, promptly closes again.

This has consistently occurred between re-unizipping the kit, on different folders, on different drives, with the same behaviour.

- I have checked, and i am on .net 6.0.4
- I don't know if there's any logging that i could share
- My Desktop is running win 10

**Comment by rfuzzo** [comment]
the current stable release is not updated for the game 1.6 version, 
please download the nightly build here:  https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/latest

**Comment by Ovenfresh** [comment]
I must've missed that somewhere. It works now, thanks! :-)
