### ISSUE TITLE
Add streaming sectors to the import/export list

### ISSUE THREAD

**Issue by jwcliff** [WolvenKit/WolvenKit#943]
Streaming sectors can be exported to json by right clicking in the project explorer, but don't appear in the import/export list, unlike ents that can be exported to json by either route.

Can we get streaming sectors to show up in the import/export to allow multiple easy export to json please?

**Comment by rfuzzo** [comment]
No sorry, import/export and convert to json are two very different things. 

.ents are also not supposed to show up in the import/export section unless they convert to something else than json. I'll have to verify that

**Comment by rfuzzo** [comment]
moved to #953
