### ISSUE TITLE
Exporting certain .streamingsector files

### ISSUE THREAD

**Issue by justarandomguyintheinternet** [WolvenKit/WolvenKit#952]
**Bug Description**
- `.json` export fails on some (But not all) sector files

**To Reproduce**
1. Import the `base\worlds\03_night_city\_compiled\batch_1\exterior_3_-17_0_0.streamingsector` file
2. Right click and press `Export to .json`
3. Export fails, error appears in the log (See screenshot)

**Expected behavior**
- The sector to get exported to a `.json` file

**Screenshots**
![](https://i.ibb.co/tZ5ccDP/image.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - WolvenKit Nightly 09.10

**Comment by seberoth** [comment]
Fixed in the next nightly
