### ISSUE TITLE
Json Convert UI

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit#953]
**Is your feature request related to a problem? Please describe.**
Json Conversions are (somewhat) more annoying to do than exports.

**Describe the solution you'd like**
A separate tool for json-conversions, where you can select from the files in your project.

**Describe alternatives you've considered**
Alternative is to do nothing.

**Comment by jwcliff** [comment]
This would be great to have, but just knowing about folder export has helped tonnes. Am adding a note that you can do that to the guide so more people can find it, as it seems lots of people haven't realised.

**Comment by jwcliff** [comment]
Hadn't found that switching to the flat list made it filterable by type before either, had been frustrated it wasn't filterable and not discovered that. That makes exporting a bunch way easier too, even if their not in the same folder.
