### ISSUE TITLE
Preview UVs are messed up

### ISSUE THREAD

**Issue by jwcliff** [WolvenKit/WolvenKit#962]
**Describe the bug**
The 3d preview materials are using incorrect UVs, (possibly from the flip?)
If you load a model in and do generate materials on the 3d preview their off, so for instance poster_d shows samurai instead of riot as the UV is in the wrong place on the atlas. 

**To Reproduce**
1. add poster_d  to a project, open it and do preview
2. click generate materials, you'll get a movie poster
3. Should be a club poster (see attached screenshots)

very obvious on a number of things, wire_fence_02_a_tall, kitsch_double_bed_a, delivery_crate_e.mesh

**Expected behavior**
UVs to be lined up and preview display correct materials

**Screenshots**
![image](https://user-images.githubusercontent.com/29640139/195392381-a00c226b-ea34-48ab-a05c-76c6baef3ef1.png)
![image](https://user-images.githubusercontent.com/29640139/195392482-66d6e1e8-d287-467b-860c-0abc0c93a10c.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Version 8.7.0-nightly.2022-10-12

**Comment by ja-to** [comment]
Should be fixed with #963 

This issue stems from changes to XBM behavior a few weeks ago. It might be worthwhile to clear temp files from `AppData/REDmodding/WolvenKit/Temp_OBJ` to avoid having non-flipped XBM's from before 09-26.
