### ISSUE TITLE
Project Explorer: Tree should remember collapse state of subfolder

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#970]
The project explorer tree defaults to having every node extended. 

**To Reproduce**
1. Have a project with a nested folder structure with several files, e.g.
```
base
  - characters
    - garment
      - gang_monk
        - legs
          - l1_094_skirt__monk_dress
            - l1_094_wa_skirt__monk_dress.mesh
      - citizen_formal
        - feet
          - s1_008_shoe__elegant
            - s1_008_ma_shoe__elegant.mesh
``` 
2. Collapse a subfolder, e.g. **garment**
3. Trigger a refresh of the file structure, either by hitting ↻ or by performing a file export/import 

**Expected behavior**
1. WolvenKit keeps track of the new file ✅
2. Folding states of tree nodes are persistent even after the reload ❌

**Actual behavior**
The tree folder nodes are recursively expanded, right down to the lowest level.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.7.0-nightly.2022-10-21

**Comment by manavortex** [comment]
If you could prioritize this, I'd be grateful :) This would be a huge improvement for me.

**Comment by seberoth** [comment]
Thats harder then it sounds like.
Needs major rewrite of the project explorer. Wasted 2 days on it, couldn't get it to work properly yet.

**Comment by manavortex** [comment]
Oof - how about just dumping the nodes' collapse state into a map before calling refresh, and then iterating over the map to apply the collapse state again? Might not be the clean rewrite, but seems to me as if it could work. (I still haven't looked at the code)

**Comment by seberoth** [comment]
Nope, doesn't work. Tried that first :P
SfTreeGrid is a bit...

**Comment by manavortex** [comment]
Oof - damn. You probably should have taken one of the 51913512 different implementations which wouldn't have had any of those issues... ':D
