### ISSUE TITLE
materialEntries: CMaterialInstance should display name based on 'index' property

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#985]
For adding materials to a mesh: when duplicating or inserting CMeshMaterialEntries into the `materialEntries`, the property `index` corresponds to the copy rather than the item's index. This is a problem, as the CMaterialInstance inside the `localMaterialBuffer` will display the `name` property of the item corresponding by item index, but the material that'll get loaded in-game is selected by `index` property. 

Example: 
![](https://camo.githubusercontent.com/e2fe94f8476a25c99de04e5da5dec3f8db8156833a9f4c120b5b1c1b46be2bc5/68747470733a2f2f692e696d6775722e636f6d2f413764446477472e706e67)

**Describe the solution you'd like**
The `index` property should be read-only and correspond to the element's position in the array. When the array is updated, all elements should refresh their positions.

**Additional context**
In the screenshot, I duplicate material `white_01` and rename it to `gold`. After closing and re-opening the mesh, CMaterialInstance #8 will now display its name as `gold`. However, the `gold` appearance, when loaded by the game, will use the CMaterialInstance with the index of #7.

**Comment by manavortex** [comment]
This might be relatively quick to implement. Took me quite some time to figure out!

**Comment by seberoth** [comment]
I mean, it has done what was expected. It copied the data...
The index in the data has nothing to do with the index of the item it is in. See this vanilla file:
![grafik](https://user-images.githubusercontent.com/456881/199265276-11fdd75e-3d57-4139-85df-c57e68f137d0.png)

There is a bug indeed, that the localMaterialBuffer displays the wrong name...

**Comment by manavortex** [comment]
Oh, wow. Then I have no idea what it even means. :D 

In that case, yeah, the localMaterialBuffer should use the name as defined by index! :)

**Comment by manavortex** [comment]
Fixed in [8.7.1-nightly.2022-11-04](https://github.com/WolvenKit/WolvenKit-nightly-releases/releases/tag/8.7.1-nightly.2022-11-04)
