### ISSUE TITLE
CMaterialnstance/CMaterialEntry: Can name update on blur?

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#988]
After updating a CMaterialEntry, the corresponding CMaterialInstance's displayed name will only be updated on closing and re-opening the file

**Describe the solution you'd like**
Is it possible to refresh the property on blur?

**Describe alternatives you've considered**
… maybe on save?

https://user-images.githubusercontent.com/965785/199987293-8772db83-c094-4db9-83e2-acebecb1aa24.mp4

**Comment by seberoth** [comment]
Yeah, I know...
Was to lazy to do it as I need to rewrite a lot.

Still on a to do list

**Comment by manavortex** [comment]
@seberoth This works for preloadLocalMaterialInstances, but not for localMaterialBuffer/materials. Should I reopen, or make another ticket?

**Comment by seberoth** [comment]
What? I didn't change anything in `preloadLocalMaterialInstances`.
If I change a name in `materialEntries`, it auto updates the name in `localMaterialBuffer/materials`

**Comment by manavortex** [comment]
Yeah, exactly - I forgot to include the other array, which is effectively doing the same thing, but for physics-enabled meshes (I _think_).
