### ISSUE TITLE
*.inkatlas: use File Information "Image"

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#992]
When selecting an *.inkatlas file, the "Image" part of the "File Information" preview is deactivated.
![image](https://user-images.githubusercontent.com/965785/200185993-299cd358-d537-4858-bf2d-75ca1b7996e0.png)

**Describe the solution you'd like**
It should show the "Part Mapping" view, perhaps readonly?

**Describe alternatives you've considered**
If that's not doable, it could show the currently active texture, if one is set

**Comment by seberoth** [comment]
Thats right, as *.inkatlas aren't images

**Comment by manavortex** [comment]
I know - but they point to images, and it would be handy to see which texture they're loading without opening them :)

**Comment by rfuzzo** [comment]
This could happen as a feature: more previews for different file types in the Properties View
