### ISSUE TITLE
Context menu entry for text files: "Open with system editor"?

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#993]
I love the fact that WKit is able to display .yaml files, but I much prefer editing them in Notepad++. Would it be possible to add a context menu entry to open them with the system editor instead? 

Optional: Maybe there could be a preference group to let the user toggle between WKit and external editor by file type / extension?

**Comment by rfuzzo** [comment]
I think I’ll add a textbox to the settings where you can add ignored extensions

**Comment by manavortex** [comment]
That's a good idea, too :))

**Comment by kwekmaster** [comment]
@rfuzzo -- I'm taking this -- please assign to me. Thank you.
