### ISSUE TITLE
Bug: can't edit/save yaml files

### ISSUE THREAD

**Issue by manavortex** [WolvenKit/WolvenKit#994]
**Describe the bug**
Changing .yaml files creates a .tmp file and then fails silently
[resources.zip](https://github.com/WolvenKit/WolvenKit/files/9946462/resources.zip)

**To Reproduce**
Preconditions:
1. Extract the attached archive
2. Open arasaka_attire_tweaks.yaml in WKit's editor

Bug 1:
1. Right-click on the last item (#94) and select "duplicate"
2. Error: No new item will show up. Instead, a tmp file will be generated.

Bug 2:
1. Select any item and change a value (e.g. ID of #1 to Items.kosode_shirt_blackblue_2)
2. Save the file
3. Error: The change will not be written. Instead, a tmp file will be generated.

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Version [8.7.1-nightly.2022-11-06](https://github.com/WolvenKit/WolvenKit/compare/8.7.1-nightly.2022-11-05...8.7.1-nightly.2022-11-06)

**Comment by dragonzkiller** [comment]
TXL is something I'm currently working on. For the time being, please use another editor such as VS Code or Notepad++

**Comment by dragonzkiller** [comment]
Actually. I'm going to close this in favor of #922. Since that's the main location for this. Please continue any comments there as we begin integrating support
